/**
 * Searchable glossary of every 3D label (built from scene/labelIndex.json, regenerated by scripts/label-index.ts
 * on each site build). Opens over the scene, so it also works in full screen; "Seen in" jumps to the module.
 */
import { useMemo, useState } from 'react';
import INDEX from './labelIndex.json';
import { useUI } from '../app/store';

interface Entry { title: string; desc: string; modules: string[]; aka: string[] }
const NAMES: Record<string, string> = { vent: 'Ventilator', abg: 'Blood gas', labs: 'Labs', lines: 'Lines', heart: 'Heart', abdomen: 'Abdomen', neuro: 'Brain' };
const norm = (s: string) => s.toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '');

export function Glossary({ onClose }: { onClose: () => void }) {
  const [q, setQ] = useState(''); const [mod, setMod] = useState<string | null>(null);
  const list = useMemo(() => {
    const t = norm(q.trim());
    return (INDEX as Entry[]).filter((e) => (!mod || e.modules.includes(mod)) && (!t || norm(`${e.title} ${e.aka.join(' ')} ${e.desc}`).includes(t)))
      .sort((a, b) => (t ? Number(!norm(a.title).startsWith(t)) - Number(!norm(b.title).startsWith(t)) : 0) || a.title.localeCompare(b.title));
  }, [q, mod]);
  return (
    <div className="gloss" role="dialog" aria-label="Glossary of labelled structures" onKeyDown={(e) => { if (e.key === 'Escape') onClose(); }}>
      <div className="gloss-h">
        <b>Glossary</b><span className="muted small">{list.length} of {INDEX.length} structures</span>
        <button type="button" className="linfo-x" aria-label="Close glossary" onClick={onClose}>×</button>
      </div>
      <input className="gloss-q" type="search" autoFocus placeholder="Search names and descriptions…" value={q} onChange={(e) => setQ(e.target.value)} aria-label="Search the glossary" />
      <div className="chips gloss-mods">
        <button type="button" className={`chip${!mod ? ' on' : ''}`} onClick={() => setMod(null)}>All</button>
        {Object.entries(NAMES).map(([k, n]) => <button type="button" key={k} className={`chip${mod === k ? ' on' : ''}`} onClick={() => setMod(mod === k ? null : k)}>{n}</button>)}
      </div>
      <ul className="gloss-list">
        {list.map((e) => (
          <li key={e.title + e.desc.slice(0, 20)}>
            <div><b>{e.title}</b>{e.aka.length > 0 && <span className="muted small"> · also “{e.aka.slice(0, 3).join('”, “')}”</span>}</div>
            <p>{e.desc}</p>
            <div className="gloss-seen"><span className="muted small">Seen in</span>{e.modules.map((m) => (
              <button type="button" key={m} className="linklike" onClick={() => { useUI.getState().set({ module: m as never }); onClose(); }}>{NAMES[m] ?? m}</button>))}</div>
          </li>
        ))}
        {!list.length && <li className="muted">Nothing matches “{q}”.</li>}
      </ul>
    </div>
  );
}
