/**
 * Plain-language descriptions for every 3D label (shown when a label is hovered, clicked or tapped).
 * Keys are `labelKey(visible text)`; labels whose text carries live numbers or states pass an explicit `info` key.
 * Written for this app, in our own words. Other modules can add entries with registerLabelInfo() (the cell model
 * registers its transporter descriptions).
 */
export function labelKey(text: string): string {
  let t = (text ?? '').toLowerCase().replace(/\s+/g, ' ').trim();
  t = t.split(' · ')[0];
  const d = t.search(/\s\d/); if (d > 0) t = t.slice(0, d); // a separate number ("Pressure bag 300 mmHg"), not "M1"
  return t.replace(/^[\s→←↑↓:–—-]+|[\s→←↑↓:–—!.,~-]+$/g, '').trim();
}

const G: Record<string, string> = {
  /* ── heart and great vessels ─────────────────────────────────────────────────────────────── */
  'right atrium': 'Collects venous blood from the body (via the superior and inferior venae cavae) and the heart itself. Its pressure is the central venous pressure.',
  'ra': 'Right atrium — receives venous blood from the body and passes it through the tricuspid valve to the right ventricle.',
  'right ventricle': 'Thin-walled pump that sends blood into the low-pressure lungs. It copes poorly with a sudden rise in pulmonary pressure (PE, high PEEP, ARDS).',
  'rv': 'Right ventricle — pumps blood into the pulmonary artery and lungs; thin-walled and sensitive to afterload.',
  'left atrium': 'Receives oxygenated blood from the pulmonary veins. Its pressure is what the wedge pressure estimates.',
  'la': 'Left atrium — receives oxygenated blood from the four pulmonary veins and fills the left ventricle through the mitral valve.',
  'left ventricle': 'Thick-walled pump that generates systemic pressure and pushes blood into the aorta.',
  'lv': 'Left ventricle — the high-pressure pump for the whole body; its wall is about three times thicker than the right ventricle’s.',
  'tricuspid valve': 'Three-leaflet valve between the right atrium and right ventricle. If it leaks, the CVP waveform shows tall v waves.',
  'ventricular septum': 'The muscular wall between the ventricles. It bows toward the left when the right ventricle is pressure- or volume-overloaded.',
  'aorta': 'The main artery leaving the left ventricle. Arterial lines and blood pressure measure the pressure in its branches.',
  'pulmonary artery': 'Carries deoxygenated blood from the right ventricle to the lungs. A pulmonary-artery catheter sits here.',
  'pulmonary veins': 'Four veins that return oxygenated blood from the lungs to the left atrium.',
  'superior vena cava': 'Drains the head, neck and arms into the right atrium. A central line’s tip belongs in its lower part, near the right atrium.',
  'svc': 'Superior vena cava — drains the upper body into the right atrium; the target vessel for a central line tip.',
  'inferior vena cava': 'Drains the legs and abdomen into the right atrium. On ultrasound its size and change with breathing reflect right-atrial pressure.',
  'ivc': 'Inferior vena cava — carries blood from the lower body to the right atrium, just right of the aorta.',
  'vsd': 'Ventricular septal defect — a hole in the septum between the ventricles. Flow normally runs left to right; it reverses if right-sided pressures exceed left.',
  'asd': 'Atrial septal defect — a hole between the atria. Usually a left-to-right shunt that loads the right heart.',
  'pfo': 'Patent foramen ovale — a flap-valve between the atria left over from fetal life. It opens right-to-left when right-atrial pressure exceeds left (e.g. high PEEP, PE).',
  'coarctation': 'Coarctation of the aorta — a narrowing at the isthmus, just beyond the left subclavian artery. Arms hypertensive, legs under-perfused; in a newborn the lower body may depend on the open duct.',
  'rvot obstruction': 'Right-ventricular outflow obstruction — in tetralogy the infundibulum under the pulmonary valve is narrowed (and can spasm). It decides how much blood reaches the lungs.',
  'overriding aorta': 'Overriding aorta — in tetralogy the aortic root sits over the VSD and the septal crest, so both ventricles eject into it.',
  'thick rv wall': 'Right-ventricular hypertrophy — the RV wall thickens when it has to pump at high pressure (outflow obstruction, pulmonary hypertension, a large VSD).',
  'rv hypertrophy': 'Right-ventricular hypertrophy — the RV wall thickens when it has to pump at high pressure (outflow obstruction, pulmonary hypertension, a large VSD).',
  'pda': 'Patent ductus arteriosus — the fetal channel between the pulmonary artery and aorta that normally closes after birth.',
  /* ── Lines module ─────────────────────────────────────────────────────────────────────────── */
  'cvc tip': 'Central line tip at the cavo-atrial junction (lower SVC). Here it reads true central venous pressure and is safe for vasopressors.',
  'cvc tip in the rv': 'The catheter has gone too far — into the right ventricle. Expect ectopics and a ventricular-shaped pressure trace; pull it back to the cavo-atrial junction.',
  'central line enters here': 'Puncture site for the right internal jugular approach: the straightest route to the SVC and right atrium.',
  'central line (right ij)': 'Central venous catheter in the right internal jugular vein, transduced to give the CVP trace on the monitor.',
  'radial arterial line': 'Cannula in the radial artery, transduced to give beat-to-beat blood pressure and easy blood sampling.',
  'arterial cannula': 'A 20-gauge cannula in the radial artery. Its trace is only as good as its patency, flush and zeroing.',
  'catheter clot': 'Clot at the cannula tip damps the trace: systolic falls, diastolic rises, and the dicrotic notch disappears. Aspirate and flush.',
  'right internal jugular vein': 'Large vein lateral to the carotid in the neck; the usual site for an ultrasound-guided central line.',
  'internal jugular vein': 'Drains the brain and face; lies beside the carotid artery and collapses with probe pressure.',
  'external jugular vein': 'Superficial neck vein crossing the sternocleidomastoid; its filling is a rough bedside sign of venous pressure.',
  'common carotid artery': 'Main artery of the neck, medial and deep to the internal jugular vein; pulsatile and not compressible.',
  'internal carotid artery': 'Branch of the common carotid that supplies most of the brain hemisphere.',
  'external carotid → superficial temporal': 'Supplies the face and scalp; its terminal branch, the superficial temporal, is felt in front of the ear.',
  'facial artery': 'Branch of the external carotid crossing the jaw in front of the masseter.',
  'facial vein': 'Drains the face into the internal jugular vein.',
  'subclavian → axillary vein': 'Runs under the clavicle into the arm; an alternative central-line site with lower infection risk but a pneumothorax risk.',
  'subclavian → axillary artery': 'Supplies the arm; it lies just behind the subclavian vein.',
  'subclavian artery': 'Supplies the arm; it lies just behind the subclavian vein.',
  'cephalic vein': 'Superficial vein on the outer (thumb) side of the arm.',
  'basilic vein': 'Superficial vein on the inner side of the arm; a common PICC route.',
  'median cubital vein': 'Links cephalic and basilic veins at the elbow — the usual venepuncture site.',
  'brachial artery': 'Main arm artery at the elbow crease; used for manual blood-pressure measurement.',
  'brachial vein': 'Deep vein paired with the brachial artery.',
  'radial artery': 'Wrist artery on the thumb side; the usual arterial-line and ABG site because the hand also has the ulnar supply.',
  'ulnar artery': 'Wrist artery on the little-finger side; the back-up supply to the hand when the radial artery is cannulated.',
  'femoral vein': 'Large vein in the groin, medial to the femoral artery; a quick central-access site in emergencies.',
  'femoral → popliteal vein': 'The deep vein of the thigh, continuing behind the knee as the popliteal vein; a common site for DVT.',
  'great saphenous vein': 'Long superficial vein on the inner leg, from the ankle to the groin.',
  'small saphenous vein': 'Superficial vein on the back of the calf, joining the popliteal vein.',
  'tibial veins': 'Deep veins of the calf, paired with the tibial arteries.',
  'common iliac artery': 'One of the two branches the aorta splits into at the level of the umbilicus.',
  'external iliac artery': 'Continues from the common iliac into the leg as the femoral artery.',
  'internal iliac artery': 'Supplies the pelvic organs; a source of bleeding in pelvic fractures.',
  'iliac veins': 'Drain the legs and pelvis into the inferior vena cava.',
  'femoral artery': 'Main leg artery in the groin; an alternative arterial-line site and a pulse to feel in shock.',
  'deep femoral (profunda) artery': 'Deep branch of the femoral artery supplying the thigh.',
  'popliteal artery': 'Artery behind the knee, continuing from the femoral.',
  'anterior tibial → dorsalis pedis': 'Runs down the front of the leg to the top of the foot, where the dorsalis pedis pulse is felt.',
  'posterior tibial artery': 'Runs behind the inner ankle bone, where its pulse is felt.',
  'portal vein': 'Carries blood from the gut and spleen to the liver; not a systemic vein.',
  'renal artery & vein': 'Supply and drainage of the kidney; the kidneys receive about a fifth of the cardiac output.',
  'celiac trunk / sma': 'The first two gut branches of the abdominal aorta: celiac (stomach, liver, spleen) and superior mesenteric (small bowel, right colon).',
  'phlebostatic axis': 'Fourth intercostal space, mid-axillary line — the level of the right atrium. Transducers are levelled here.',
  'transducer level': 'Where the transducer sits relative to the phlebostatic axis. Every 10 cm below the axis adds about 7.4 mmHg to the reading; above, it subtracts.',
  'transducers level with the axis': 'The transducers are at the level of the right atrium, so no hydrostatic error is added.',
  'transducers level': 'The transducers are at the level of the right atrium, so no hydrostatic error is added.',
  'pressure bag': 'Pressurised flush bag (about 300 mmHg) that keeps the line open with a slow continuous flush. Below about 250 mmHg blood can back up the line.',
  'stopcock open to air': 'The transducer is open to atmosphere, so the monitor reads zero. Turn the stopcock back to the patient.',
  /* ── abdomen ──────────────────────────────────────────────────────────────────────────────── */
  'liver': 'Largest solid organ, under the right ribs. Makes clotting factors and albumin, clears lactate and drugs; a common source of bleeding in blunt trauma.',
  'spleen': 'Under the left ribs; blood-filled and the organ most often injured in blunt abdominal trauma.',
  'stomach': 'Upper-left abdomen. Air in it is normal; air outside it (free air) means a perforation.',
  'pancreas': 'Lies behind the stomach across the spine. Inflamed in pancreatitis, it can leak fluid into the retroperitoneum.',
  'r kidney': 'Right kidney — retroperitoneal, so bleeding from it does not show on FAST.',
  'l kidney': 'Left kidney — retroperitoneal, behind the spleen and bowel.',
  'small bowel': 'About 6 m of bowel in the middle of the abdomen; obstruction or loss of blood supply (mesenteric ischaemia) makes it dilate and leak.',
  'colon': 'Large bowel framing the abdomen; it can perforate or lose its blood supply.',
  'bladder': 'In the pelvis. A full bladder is a good window for seeing pelvic free fluid on ultrasound.',
  'diaphragm': 'Dome-shaped muscle separating chest from abdomen; fluid is looked for just above and below it on ultrasound.',
  'morison’s pouch': 'The space between liver and right kidney — the lowest upper-abdominal space when supine, so free fluid collects here first.',
  'splenorenal': 'The space between spleen and left kidney, the left-upper-quadrant FAST window.',
  'pelvic fluid': 'Free fluid behind the bladder (or uterus) — the lowest part of the peritoneal cavity.',
  'retroperitoneal haematoma': 'Blood behind the peritoneum (e.g. from the aorta, kidney or pelvis). FAST cannot see it; CT can.',
  'aaa': 'Abdominal aortic aneurysm — the aorta wider than 3 cm. Rupture risk rises sharply with size.',
  'free air': 'Gas outside the bowel, under the diaphragm — a sign of perforation needing surgery.',
  /* ── lungs and airway ─────────────────────────────────────────────────────────────────────── */
  'secretions narrow the tube': 'Secretions inside the endotracheal tube raise airway resistance: peak pressure rises while plateau pressure stays the same.',
  'mucus plug': 'Mucus blocking a bronchus: the lung beyond it collapses and shunts blood, so oxygen falls.',
  'pleural air': 'Air between the lung and chest wall (pneumothorax). Under tension it compresses the lung and kinks venous return.',
  'dependent lung': 'The lowest lung regions (the back, when supine), where oedema and collapse concentrate under gravity.',
  'alveolar gas': 'The gas in the air sacs, where oxygen and carbon dioxide exchange with capillary blood.',
  'surfactant': 'A film that lowers surface tension so small alveoli stay open. Deficient in premature lungs and damaged in ARDS.',
  'lining fluid': 'Thin liquid layer on the alveolar surface. It thickens and floods in pulmonary oedema.',
  'type i cell': 'Very flat cell forming most of the alveolar wall — the thin barrier gas crosses.',
  'basement membrane': 'Shared support layer between the alveolar and capillary cells.',
  'interstitium': 'Space between alveolus and capillary. It swells with fluid in oedema and thickens in fibrosis, slowing gas diffusion.',
  'endothelium': 'The single cell layer lining blood vessels; it controls leak, tone and clotting.',
  'endothelium (vessel wall)': 'The single cell layer lining blood vessels; it controls leak, tone and clotting.',
  'plasma': 'The liquid part of blood, carrying dissolved gases, proteins, electrolytes and clotting factors.',
  'red cell': 'Red blood cell — carries oxygen bound to haemoglobin.',
  'red blood cell': 'Carries oxygen bound to haemoglobin and gives some of it up in the tissues.',
  'aerated alveolus': 'An open, ventilated air sac taking part in gas exchange.',
  'collapsed': 'Alveolus with no air (atelectasis): blood flowing past it is not oxygenated — shunt.',
  'flooded': 'Alveolus filled with fluid (oedema or pus): no gas exchange, a shunt that extra oxygen barely helps.',
  'low v/q': 'Alveolus that gets less air than blood. Oxygen falls but improves with supplemental oxygen.',
  'recruited': 'An alveolus reopened by pressure (PEEP or a recruitment manoeuvre).',
  'alveolar duct': 'Small airway leading into a cluster of alveoli.',
  'arteriole (from rv)': 'Pulmonary arteriole bringing deoxygenated blood from the right ventricle to the capillaries.',
  'venule (to la)': 'Pulmonary venule carrying oxygenated blood back toward the left atrium.',
  /* ── blood gas journey ────────────────────────────────────────────────────────────────────── */
  'ventilation: fresh gas in, co₂ out': 'Breathing replaces alveolar gas: it brings oxygen in and washes carbon dioxide out. CO₂ removal depends on minute ventilation.',
  'pulmonary arteriole: mixed venous blood': 'Blood returning from the whole body, low in oxygen and high in CO₂, arriving to be re-oxygenated.',
  'pulmonary venule: arterialised blood': 'Blood leaving the lung after gas exchange, now carrying oxygen at arterial levels.',
  'capillary: rbcs load o₂ in the first third of their transit': 'Red cells normally finish loading oxygen early in the capillary, leaving reserve time for exercise or thickened membranes.',
  'arteriole — an abg samples this blood': 'Arterial blood: an arterial blood gas measures the oxygen, CO₂ and acid–base status delivered to the tissues.',
  'venule — a vbg samples this blood': 'Venous blood: a venous gas tracks pH and CO₂ reasonably well but says little about oxygenation.',
  'renal vein: reclaimed / new hco₃⁻': 'The kidney returns filtered bicarbonate and makes new bicarbonate, correcting metabolic acidosis over hours to days.',
  'urine: h⁺ excreted as nh₄⁺ / h₂po₄⁻': 'Acid leaves the body in urine bound to ammonia and phosphate buffers.',
  /* ── brain ────────────────────────────────────────────────────────────────────────────────── */
  'a1': 'First segment of the anterior cerebral artery, from the carotid to the anterior communicating artery.',
  'acoa': 'Anterior communicating artery — joins the two anterior cerebral arteries; the commonest site of berry aneurysms.',
  'pcoa': 'Posterior communicating artery — links the carotid and posterior circulations in the circle of Willis.',
  'p1': 'First segment of the posterior cerebral artery, from the basilar tip.',
  'm1': 'Main trunk of the middle cerebral artery; its blockage causes a large hemispheric stroke.',
  'basilar': 'Basilar artery — formed by the two vertebral arteries; it supplies the brainstem and back of the brain.',
  'ica': 'Internal carotid artery — supplies the front and middle of the hemisphere.',
  'sca': 'Superior cerebellar artery — supplies the top of the cerebellum.',
  'mca': 'Middle cerebral artery — supplies most of the side of the hemisphere (face and arm motor areas, speech in the dominant side).',
  'aca': 'Anterior cerebral artery — supplies the inner surface of the hemisphere (leg motor area).',
  'pca': 'Posterior cerebral artery — supplies the occipital lobe (vision).',
  'internal carotid': 'Supplies the front and middle of the hemisphere and the eye.',
  'middle cerebral (m1)': 'Main trunk of the middle cerebral artery; its blockage causes a large hemispheric stroke.',
  'anterior cerebral': 'Supplies the inner surface of the hemisphere, including the leg motor area.',
  'posterior cerebral': 'Supplies the occipital lobe and vision.',
  'vertebral': 'Vertebral artery — runs up through the neck vertebrae; the two join to form the basilar artery.',
  'core and penumbra': 'Core: tissue already dead. Penumbra: tissue that is failing but salvageable if blood flow returns soon.',
  /* ── labs: organs and microscopic scenes ──────────────────────────────────────────────────── */
  'bone marrow': 'Makes red cells, white cells and platelets; counts fall when it is suppressed or replaced.',
  'brain': 'Uses about a fifth of the body’s oxygen and has no fuel stores, so it depends on steady flow and glucose.',
  'heart': 'Injured heart muscle releases troponin; a stretched heart releases natriuretic peptides.',
  'kidney': 'Filters about 180 L of plasma a day; creatinine and urea rise when filtration falls.',
  'afferent arteriole (blood in)': 'Brings blood into the glomerulus; it constricts or dilates to hold filtration steady.',
  'efferent arteriole (blood out)': 'Carries blood out of the glomerulus; its tone helps set filtration pressure.',
  'glomerulus (capillary loops)': 'A knot of capillaries where plasma is filtered into the tubule.',
  'bowman’s capsule': 'The cup around the glomerulus that collects the filtrate.',
  'tubule — filtrate → urine': 'Reabsorbs most of the filtrate — water, sodium, bicarbonate, glucose — and adjusts what stays as urine.',
  'hepatocytes (liver cells)': 'Liver cells that make proteins and clotting factors, process drugs and store glycogen.',
  'sinusoid (blood)': 'Leaky liver capillary where blood bathes the hepatocytes.',
  'bile canaliculus': 'Tiny channel between liver cells carrying bile toward the bile ducts.',
  'injured cells leak ast/alt': 'Damaged liver cells release their enzymes (AST, ALT) into the blood.',
  'cardiac muscle cells': 'Heart muscle cells, joined end to end so the beat spreads as one.',
  'striations (sarcomeres)': 'Repeating contractile units that give heart and skeletal muscle their striped look.',
  'blood around the cells': 'Capillary blood bringing oxygen and carrying released markers away.',
  'neuron cell body': 'The part of a nerve cell containing the nucleus.',
  'dendrites': 'Branches that receive signals from other nerve cells.',
  'nucleus': 'Holds the cell’s DNA and controls which proteins are made.',
  'mitochondria (make atp)': 'Make ATP from oxygen and fuel; without oxygen the cell falls back on inefficient glycolysis and makes lactate.',
  'na⁺/k⁺ pumps (in the membrane)': 'Use ATP to keep sodium out and potassium in, maintaining the resting potential and cell volume.',
  'fluid around the cell': 'Extracellular fluid — high in sodium and chloride, low in potassium.',
  'outside the cell': 'Extracellular fluid — high in sodium and chloride, low in potassium.',
  'extracellular fluid': 'The fluid outside cells (plasma and interstitial fluid): high sodium and chloride, low potassium.',
  'cytosol': 'The fluid inside the cell: high potassium, low sodium and calcium.',
  'cell membrane': 'A lipid bilayer that keeps ions apart; channels and pumps in it control what crosses.',
  /* ── blood ────────────────────────────────────────────────────────────────────────────────── */
  'neutrophil (white cell)': 'The commonest white cell; first to arrive at infection and injury.',
  'lymphocyte': 'White cell of the adaptive immune system (T and B cells).',
  'platelet': 'Cell fragment that sticks to exposed collagen and starts a clot.',
  'o₂ leaving for the tissue': 'Oxygen unloads from haemoglobin where tissue oxygen levels are low.',
  'tissue (muscle) — uses the o₂': 'Working tissue takes up oxygen; how much depends on its demand and the flow it receives.',
  'arterial end': 'Blood enters the capillary oxygen-rich at arterial pressure.',
  'venous end': 'Blood leaves the capillary with less oxygen and more CO₂.',
  'tear — collagen exposed': 'A break in the vessel wall exposes collagen, which triggers platelets and clotting.',
  'platelet plug': 'Platelets stacked at the injury — the first, temporary seal.',
  'fibrin mesh': 'Fibrin strands from the clotting cascade bind the plug into a firm clot.',
  'blood escaping': 'Bleeding continues until the plug and fibrin seal the vessel.',
  /* ── cell membrane patch ──────────────────────────────────────────────────────────────────── */
  'phospholipid heads': 'Water-loving heads facing the fluid on each side of the membrane.',
  'fatty-acid tails': 'The oily middle of the bilayer that ions cannot cross without a channel or pump.',
  'cholesterol': 'Sits among the lipids and stiffens the membrane.',
  'inner leaflet (pe, ps⁻)': 'The inner lipid layer, rich in negatively charged phosphatidylserine.',
  'glycocalyx': 'A sugar coat on the outer surface; in vessels it helps keep fluid inside the circulation.',
  /* ── whole-cell organelles (info key "cell <anchor key>") ─────────────────────────────────── */
  'cell nucleus': 'Holds the cell’s DNA and controls which proteins are made.',
  'cell envelope': 'Double membrane around the nucleus; its pores let RNA and proteins in and out.',
  'cell nucleolus': 'Inside the nucleus; builds ribosomes.',
  'cell cytosol': 'The fluid inside the cell: high potassium, low sodium and calcium.',
  'cell mito': 'Mitochondria make ATP using oxygen. Heart cells are packed with them because they never rest.',
  'cell rer': 'Rough endoplasmic reticulum — studded with ribosomes that make proteins for membranes and export.',
  'cell ser': 'Smooth endoplasmic reticulum — makes lipids and stores calcium.',
  'cell golgi': 'Sorts, finishes and ships proteins made in the ER.',
  'cell lyso': 'Lysosome — breaks down worn-out parts and engulfed material.',
  'cell perox': 'Peroxisome — breaks down fatty acids and toxic peroxides.',
  'cell centriole': 'Organises the spindle that separates chromosomes when the cell divides.',
  'cell mt': 'Microtubules — internal scaffolding and tracks for moving cargo.',
  'cell vesicle': 'Small membrane bubbles carrying proteins between compartments and to the surface.',
  'cell ribo': 'Free ribosomes make proteins that stay inside the cell.',
  'cell glycogen': 'Stored glucose, released when the cell needs fuel quickly.',
  'cell lipofuscin': 'Brownish wear-and-tear pigment that builds up in long-lived cells.',
  'cell myofibril': 'Bundles of sarcomeres — the contractile machinery of a muscle cell.',
  'cell sr': 'Sarcoplasmic reticulum — stores calcium and releases it to trigger each contraction.',
  'cell ttub': 'T-tubules carry the electrical signal deep into the cell so all sarcomeres contract together.',
  'cell disc': 'Intercalated disc — junctions that link heart cells mechanically and electrically.',
  'cell nissl': 'Nissl bodies — stacks of rough ER that make a neuron’s proteins.',
  'cell dendrite': 'Receives signals from other nerve cells.',
  'cell spines': 'Small knobs on dendrites where synapses land.',
  'cell hillock': 'Where the axon leaves the cell body; signals are summed here.',
  'cell ais': 'Axon initial segment — packed with sodium channels; the action potential starts here.',
  'cell axon': 'Carries the nerve impulse away from the cell body.',
  'cell myelin': 'Insulating wrap from glial cells that speeds conduction.',
  'cell node': 'Node of Ranvier — a gap in the myelin where the impulse is regenerated.',
  'cell nf': 'Neurofilaments and microtubules — the axon’s skeleton and transport tracks.',
  'cell branch': 'Junction to a neighbouring cell.',
};

const extra: Record<string, string> = {};
/** Add or override descriptions (keys are passed through labelKey). */
export function registerLabelInfo(map: Record<string, string>) { for (const [k, v] of Object.entries(map)) extra[labelKey(k)] = v; }

/** Description for a label key (falls back to the text without a trailing parenthesis). */
export function describeLabel(key: string, title?: string): string | null {
  const k = labelKey(key);
  const hit = extra[k] ?? G[k] ?? G[key] ?? (title ? G[labelKey(title)] ?? extra[labelKey(title)] : undefined);
  if (hit) return hit;
  const bare = k.replace(/\s*\(.*$/, '').trim();
  return G[bare] ?? extra[bare] ?? null;
}
export const GLOSSARY_SIZE = () => Object.keys(G).length + Object.keys(extra).length;
