/**
 * Teaching metadata for the Drugs module, kept as data beside the mechanisms: which graph nodes are
 * adverse effects, onset / peak / duration ranges (typical adult IV teaching values unless the route says
 * otherwise — own wording, check local references), and which Director lessons use each drug.
 */
export const ADVERSE: Record<string, { nodes: string[]; note: string }> = {
  norepinephrine: { nodes: [], note: 'Digital and splanchnic ischaemia, arrhythmia and extravasation injury are not drawn in this graph; watch the infusion site and perfusion.' },
  epinephrine: { nodes: ['glyco', 'hr'], note: 'Tachyarrhythmia and a metabolic (not only hypoperfusion) lactate rise.' },
  vasopressin: { nodes: ['water'], note: 'Free-water retention (sodium falls) and ischaemia at high doses.' },
  phenylephrine: { nodes: ['hr', 'co'], note: 'Reflex bradycardia and a fall in output in a weak heart.' },
  dobutamine: { nodes: ['svr', 'hr'], note: 'Vasodilation can drop pressure; tachycardia and arrhythmia.' },
  dopamine: { nodes: ['hr'], note: 'More tachyarrhythmia than norepinephrine.' },
  milrinone: { nodes: ['map'], note: 'Hypotension; arrhythmia; accumulates in renal failure.' },
  nicardipine: { nodes: ['hr'], note: 'Reflex tachycardia, headache, phlebitis.' },
  clevidipine: { nodes: ['hr'], note: 'Reflex tachycardia; lipid load; avoid with soy or egg allergy.' },
  esmolol: { nodes: ['co', 'hr'], note: 'Bradycardia, hypotension, worsening heart failure.' },
  labetalol: { nodes: ['bron', 'hr'], note: 'Bronchospasm (β2), bradycardia and heart block, orthostatic hypotension.' },
  nitroglycerin: { nodes: ['pde5', 'co'], note: 'Collapse with a PDE5 inhibitor or in a preload-dependent heart; headache; tolerance.' },
  etomidate: { nodes: ['cyp', 'cort', 'myo'], note: 'Adrenal suppression and myoclonus; no analgesia.' },
  propofol: { nodes: ['resp', 'map', 'myo'], note: 'Hypotension, apnoea; propofol-infusion syndrome with prolonged high doses.' },
  ketamine: { nodes: [], note: 'Emergence phenomena, hypersalivation, and myocardial depression in catecholamine-depleted patients (see the context selector).' },
  midazolam: { nodes: ['resp', 'map'], note: 'Respiratory depression (multiplied by opioids), delirium, accumulation in renal failure.' },
  fentanyl: { nodes: ['rc', 'rr', 'hr'], note: 'Respiratory depression and apnoea, bradycardia, chest-wall rigidity with rapid large doses.' },
  dexmedetomidine: { nodes: ['hr', 'map'], note: 'Bradycardia and hypotension; transient hypertension with a fast bolus.' },
  rocuronium: { nodes: [], note: 'Awareness if sedation is inadequate — paralysis is not sedation; anaphylaxis.' },
  succinylcholine: { nodes: ['kout', 'k'], note: 'Hyperkalaemia (dangerous with up-regulated receptors), malignant hyperthermia, bradycardia with repeat doses, prolonged block with cholinesterase deficiency.' },
  albuterol: { nodes: [], note: 'Tachycardia, tremor, hypokalaemia, lactate rise.' },
  ipratropium: { nodes: [], note: 'Dry mouth; can worsen angle-closure glaucoma if nebulised into the eyes.' },
  hypertonic: { nodes: [], note: 'Overcorrection of chronic hyponatraemia (osmotic demyelination), volume overload, hyperchloraemic acidosis.' },
  mannitol: { nodes: ['kid', 'vol'], note: 'Hypovolaemia and hypotension from diuresis, electrolyte loss, kidney injury, rebound.' },
  nimodipine: { nodes: ['map'], note: 'Hypotension that lowers cerebral perfusion.' },
  thrombolytic: { nodes: ['bleed'], note: 'Bleeding, including symptomatic intracranial haemorrhage; angio-oedema.' },
  calcium: { nodes: [], note: 'Tissue injury if it extravasates (chloride especially); caution with digoxin toxicity.' },
  insulin: { nodes: [], note: 'Hypoglycaemia hours later; check glucose repeatedly.' },
  txa: { nodes: [], note: 'Seizures at high doses; thrombosis is a theoretical concern; late use after trauma may harm.' },
  pcc: { nodes: ['thromb'], note: 'Thrombosis; contains heparin in some products (avoid with HIT).' },
  vitamink: { nodes: [], note: 'Rare anaphylactoid reactions with fast IV injection; delayed effect.' },
  protamine: { nodes: ['adv'], note: 'Hypotension, anaphylaxis, pulmonary hypertension; excess protamine is itself anticoagulant.' },
};

/** minutes; ranges are [low, high]. Curves are drawn on a log time axis from these. */
export interface TimeCourse { route: string; onset: [number, number]; peak: [number, number]; duration: [number, number]; note?: string }
export const TIMECOURSE: Record<string, TimeCourse> = {
  norepinephrine: { route: 'IV infusion', onset: [1, 2], peak: [3, 10], duration: [1, 2], note: 'Duration = offset after stopping; titrate every few minutes.' },
  epinephrine: { route: 'IV infusion', onset: [1, 2], peak: [3, 10], duration: [2, 5] },
  vasopressin: { route: 'IV infusion', onset: [2, 5], peak: [10, 20], duration: [10, 20] },
  phenylephrine: { route: 'IV push', onset: [0.5, 1], peak: [1, 2], duration: [15, 20] },
  dobutamine: { route: 'IV infusion', onset: [1, 2], peak: [5, 10], duration: [5, 10] },
  dopamine: { route: 'IV infusion', onset: [2, 5], peak: [5, 10], duration: [5, 10] },
  milrinone: { route: 'IV infusion', onset: [5, 15], peak: [30, 60], duration: [180, 360], note: 'Longer in renal failure.' },
  nicardipine: { route: 'IV infusion', onset: [5, 15], peak: [30, 45], duration: [30, 240], note: 'Offset lengthens after prolonged infusion.' },
  clevidipine: { route: 'IV infusion', onset: [2, 4], peak: [5, 10], duration: [5, 15] },
  esmolol: { route: 'IV bolus + infusion', onset: [1, 2], peak: [5, 10], duration: [10, 30] },
  labetalol: { route: 'IV bolus', onset: [2, 5], peak: [5, 15], duration: [120, 360] },
  nitroglycerin: { route: 'IV infusion', onset: [1, 2], peak: [3, 5], duration: [3, 5] },
  etomidate: { route: 'IV induction', onset: [0.5, 1], peak: [1, 1.5], duration: [3, 5] },
  propofol: { route: 'IV bolus', onset: [0.5, 0.7], peak: [1, 2], duration: [5, 10] },
  ketamine: { route: 'IV bolus', onset: [0.5, 1], peak: [1, 2], duration: [10, 20] },
  midazolam: { route: 'IV bolus', onset: [1, 5], peak: [5, 10], duration: [60, 120], note: 'Accumulates with infusions and renal failure.' },
  fentanyl: { route: 'IV bolus', onset: [1, 2], peak: [3, 5], duration: [30, 60] },
  dexmedetomidine: { route: 'IV infusion', onset: [5, 15], peak: [15, 30], duration: [60, 120] },
  rocuronium: { route: 'IV 1.2 mg/kg', onset: [0.75, 1.5], peak: [1.5, 3], duration: [45, 70] },
  succinylcholine: { route: 'IV 1.5 mg/kg', onset: [0.75, 1], peak: [1, 1.5], duration: [6, 10] },
  albuterol: { route: 'nebulised', onset: [5, 15], peak: [30, 90], duration: [180, 360] },
  ipratropium: { route: 'nebulised', onset: [15, 30], peak: [60, 120], duration: [240, 360] },
  hypertonic: { route: 'IV bolus', onset: [5, 10], peak: [15, 30], duration: [60, 180] },
  mannitol: { route: 'IV bolus', onset: [10, 20], peak: [30, 60], duration: [120, 360] },
  nimodipine: { route: 'enteral', onset: [20, 40], peak: [30, 60], duration: [240, 240], note: 'Given every 4 h (or smaller doses every 2 h).' },
  thrombolytic: { route: 'IV bolus (+ infusion for alteplase)', onset: [5, 15], peak: [30, 90], duration: [120, 360], note: 'The drug clears in minutes; the fibrinolytic state lasts hours.' },
  calcium: { route: 'IV', onset: [1, 3], peak: [3, 5], duration: [30, 60] },
  insulin: { route: 'IV bolus + dextrose', onset: [10, 20], peak: [30, 60], duration: [240, 360] },
  txa: { route: 'IV', onset: [1, 5], peak: [5, 15], duration: [180, 480] },
  pcc: { route: 'IV', onset: [10, 30], peak: [15, 30], duration: [360, 480], note: 'Factor VII wanes first — give vitamin K too.' },
  vitamink: { route: 'IV', onset: [60, 120], peak: [720, 1440], duration: [1440, 2880] },
  protamine: { route: 'IV slow', onset: [3, 5], peak: [5, 10], duration: [120, 120], note: 'Heparin rebound can follow.' },
};

/** Director lessons (by timeline id) that use each drug — the lesson shows the drug chips; the drug shows the lessons. */
export const LESSON_DRUGS: Record<string, string[]> = {
  'lines-shock-states': ['norepinephrine', 'dobutamine'],
  'lines-oxygen-delivery': ['norepinephrine'],
  'lines-haemorrhage-transfusion': ['txa'],
  'lines-iabp': ['dobutamine', 'milrinone'],
  'abd-dissection': ['esmolol', 'labetalol', 'clevidipine', 'nicardipine'],
  'abd-aaa': ['txa'],
  'hyperk-signature': ['calcium', 'insulin', 'albuterol'],
  'abg-dka': ['insulin'],
  'neuro-icp': ['mannitol', 'hypertonic'],
  'neuro-ich': ['nicardipine', 'labetalol', 'pcc', 'vitamink'],
  'neuro-sah': ['nimodipine'],
  'neuro-lvo': ['thrombolytic'],
  'neuro-time-is-brain': ['thrombolytic'],
  'neuro-time-machine': ['thrombolytic'],
  'vent-ards-vs-obstruction': ['albuterol', 'ipratropium'],
  'vent-tension-ptx': [],
  'vent-ards-signature': ['propofol', 'rocuronium'],
  'ob-circulation': ['txa'],
  'labs-coag': ['pcc', 'vitamink', 'protamine', 'txa'],
  'ob-gas': ['albuterol'],
  'pop-apnoea': ['rocuronium', 'succinylcholine'],
};
export const lessonsForDrug = (id: string) => Object.entries(LESSON_DRUGS).filter(([, ds]) => ds.includes(id)).map(([l]) => l);
