import type { AudioEpisode, MentalRep } from './types';

const rvTranscript = `You’re at the bedside. The blood pressure has fallen after intubation. Before you reach for fluid, build the physiology in your head. Picture the right ventricle pushing against the pulmonary circulation. Positive pressure has changed venous return, pulmonary vascular resistance, and the pressure surrounding the heart. Your job is not to chase a number. Your job is to decide what changed, predict what your intervention should do, and then watch whether the patient proves your model right.`;

const oxygenDeliveryTranscript = "Your pulse oximeter says ninety-eight percent. That feels reassuring. But saturation answers a very specific question: what fraction of the available hemoglobin binding sites are carrying oxygen? It does not tell you how much hemoglobin you have, and it does not tell you how much blood the heart is moving.\n\nThat distinction is the beginning of oxygen-delivery thinking.\n\nOxygen delivery, D O 2, is cardiac output multiplied by arterial oxygen content. Arterial oxygen content is dominated by oxygen bound to hemoglobin. A useful bedside approximation is one point three four times hemoglobin times arterial saturation, plus a very small contribution from oxygen dissolved in plasma.\n\nThat means three patients can all have an S P O 2 of ninety-eight percent and have very different oxygen delivery.\n\nPicture the first patient. Hemoglobin fourteen. Cardiac output five liters per minute. Saturation ninety-eight percent. Nothing surprising.\n\nNow keep saturation at ninety-eight percent but drop the hemoglobin to five. Every remaining red cell may be beautifully saturated, but there are far fewer red cells carrying oxygen. The pulse oximeter still looks excellent while arterial oxygen content has fallen dramatically.\n\nNow take a different patient. Hemoglobin is normal. Saturation is ninety-eight percent. But cardiac output has collapsed because of severe pump failure. The blood contains plenty of oxygen per deciliter, but not enough blood is reaching the tissues each minute. Again, the pulse oximeter can look perfect.\n\nThis is why expert critical-care reasoning does not ask only, “Is the blood oxygenated?” It asks, “Is enough oxygen actually being delivered?”\n\nNow add the tissues.\n\nOxygen consumption, V O 2, is what the body removes from the delivered oxygen. When delivery falls, tissues can initially compensate by extracting a larger fraction. Venous oxygen saturation falls because more oxygen is being taken out before the blood returns to the right heart. That compensation has limits. Below a critical level of delivery, oxygen consumption can become supply dependent.\n\nDo not turn that into another single-number rule. A low venous saturation can reflect low cardiac output, anemia, increased metabolic demand, arterial hypoxemia, or combinations of them. A surprisingly high venous saturation can occur when extraction is impaired or when flow distribution is abnormal. The number only becomes useful when it sits inside a physiologic model.\n\nHere is the mental shortcut I want you to keep.\n\nSaturation tells you how full the buses are.\n\nHemoglobin tells you how many buses you have.\n\nCardiac output tells you how fast the buses are moving.\n\nOxygen delivery asks how many passengers actually arrive each minute.\n\nSo the next time you see an S P O 2 of ninety-eight percent in a patient who looks poorly perfused, do not let the monitor end the conversation. Ask about hemoglobin. Ask about flow. Ask what the tissues are extracting. Ask whether the patient is warm or cold, alert or altered, making urine or shutting down, clearing lactate or accumulating it.\n\nA normal saturation can coexist with profoundly inadequate oxygen delivery.\n\nYour retrieval question is this: if saturation stays the same, name the two major variables that can still make oxygen delivery collapse.\n\nThe answer is hemoglobin and cardiac output.\n\nAnd the expert move is not merely remembering the formula. It is noticing when the patient and the pulse oximeter are telling different stories.";

export const EPISODES: AudioEpisode[] = [
  {
    id: 'rounds-rv-intubation', title: 'Why intubation can crash the failing RV',
    subtitle: 'Build the hemodynamic model before you chase the blood pressure.',
    format: 'rounds', level: 4, minutes: 12, domain: 'cardiac',
    concepts: ['rv-failure', 'pvr', 'ppv-hemodynamics', 'ventricular-interdependence', 'uncertainty'],
    status: 'voice-ready',
    chapters: [
      { id: 'scene', title: 'The pressure falls', seconds: 90, conceptIds: ['rv-failure'], prompt: 'Name three mechanisms that could reduce forward flow after intubation.' },
      { id: 'preload', title: 'Venous return changes', seconds: 150, conceptIds: ['venous-return', 'ppv-hemodynamics'] },
      { id: 'afterload', title: 'The RV sees a different afterload', seconds: 180, conceptIds: ['pvr', 'rv-failure'] },
      { id: 'septum', title: 'The LV becomes part of the problem', seconds: 150, conceptIds: ['ventricular-interdependence'] },
      { id: 'test', title: 'Make a prediction', seconds: 150, conceptIds: ['uncertainty'], prompt: 'What finding would make you abandon your current model?' },
    ],
    voice: {
      tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US',
      transcript: rvTranscript, reviewed: false,
      previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/000b3aaa-27e2-4489-94db-af1f3e5636e9.mp3',
    },
    outcomes: [
      'Explain the distinct effects of positive pressure on venous return, RV afterload and LV transmural pressure.',
      'Describe why RV distension can reduce LV filling through ventricular interdependence.',
      'State what response you expect from an intervention and what finding would falsify your model.',
    ],
  },
  {
    id: 'dose-normal-spo2', title: 'A normal SpO₂ can still hide terrible oxygen delivery',
    subtitle: 'Five-minute Daily Dose: saturation is only one term in the oxygen-delivery equation.',
    format: 'daily-dose', level: 3, minutes: 6, domain: 'hemodynamics',
    concepts: ['oxygen-delivery', 'oxygen-extraction'],
    chapters: [{ id: 'core', title: 'Saturation is not delivery', seconds: 360, conceptIds: ['oxygen-delivery', 'oxygen-extraction'], prompt: 'If saturation stays the same, name the two major variables that can still make oxygen delivery collapse.' }],
    status: 'voice-ready',
    voice: {
      tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US',
      transcript: oxygenDeliveryTranscript, reviewed: false,
      previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/0f74aa7b-257f-4d8b-a546-b073a98e4e8a.mp3',
    },
    outcomes: ['Explain how hemoglobin and cardiac output can make oxygen delivery inadequate despite a normal saturation.'],
  },
  {
    id: 'literacy-transmural', title: 'ICU Literacy: transmural pressure',
    subtitle: 'The pressure that actually distends a chamber is not always the number on the monitor.',
    format: 'icu-literacy', level: 4, minutes: 9, domain: 'foundations',
    concepts: ['preload', 'ppv-hemodynamics'],
    chapters: [{ id: 'core', title: 'Inside pressure minus outside pressure', seconds: 540, conceptIds: ['preload', 'ppv-hemodynamics'] }],
    status: 'scripted', outcomes: ['Use transmural pressure to explain why measured filling pressures change with intrathoracic pressure.'],
  },
  {
    id: 'deep-shock', title: 'Shock is a flow problem before it is a blood-pressure problem',
    subtitle: 'Phenotype the circulation: flow, tone, congestion, oxygen delivery and organ response.',
    format: 'deep-dive', level: 4, minutes: 38, domain: 'hemodynamics',
    concepts: ['shock', 'oxygen-delivery', 'oxygen-extraction', 'venous-return', 'lactate'],
    chapters: [
      { id: 'frame', title: 'Stop naming shock by one number', seconds: 420, conceptIds: ['shock'] },
      { id: 'flow', title: 'Flow and venous return', seconds: 600, conceptIds: ['venous-return'] },
      { id: 'do2', title: 'Delivery and extraction', seconds: 600, conceptIds: ['oxygen-delivery', 'oxygen-extraction'] },
      { id: 'lactate', title: 'Lactate without superstition', seconds: 420, conceptIds: ['lactate'] },
      { id: 'integration', title: 'Mixed shock', seconds: 240, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Phenotype mixed shock and choose a testable physiologic intervention rather than reflexively treating a pressure.'],
  },
  {
    id: 'case-ards-rv', title: 'Audio Case: ARDS + RV failure',
    subtitle: 'An unfolding multisystem case with no clean single-organ answer.',
    format: 'audio-case', level: 5, minutes: 22, domain: 'multisystem',
    concepts: ['ards', 'rv-failure', 'pvr', 'peep', 'multisystem-tradeoffs', 'uncertainty'],
    chapters: [
      { id: 'arrival', title: 'The handoff', seconds: 240, conceptIds: ['ards', 'rv-failure'], prompt: 'Before more data arrives, what are your competing priorities?' },
      { id: 'vent', title: 'The vent becomes part of the circulation', seconds: 360, conceptIds: ['peep', 'pvr'] },
      { id: 'echo', title: 'The RV is telling you something', seconds: 360, conceptIds: ['rv-failure', 'ventricular-interdependence'] },
      { id: 'choice', title: 'There is no free intervention', seconds: 360, conceptIds: ['multisystem-tradeoffs'], prompt: 'Choose your next move and name the organ you could worsen.' },
    ],
    status: 'planned', outcomes: ['Balance lung recruitment and RV load while explicitly stating uncertainty and tradeoffs.'],
  },
  {
    id: 'literacy-stressed-volume', title: 'ICU Literacy: stressed volume',
    subtitle: 'Why venoconstriction can change effective preload without adding a drop of fluid.',
    format: 'icu-literacy', level: 4, minutes: 11, domain: 'hemodynamics',
    concepts: ['stressed-volume', 'venous-return', 'preload'],
    chapters: [
      { id: 'container', title: 'The circulation as a pressure-generating container', seconds: 180, conceptIds: ['stressed-volume'] },
      { id: 'gradient', title: 'Mean systemic filling pressure and venous return', seconds: 240, conceptIds: ['venous-return'] },
      { id: 'pressor', title: 'Why venoconstriction is not the same as a fluid bolus', seconds: 240, conceptIds: ['stressed-volume', 'preload'] },
    ],
    status: 'planned', outcomes: ['Explain stressed versus unstressed volume and use it to reason about venous tone, fluids and pressors.'],
  },
  {
    id: 'rounds-lactate', title: 'Lactate is not a tissue-hypoxia meter',
    subtitle: 'Production, clearance, adrenergic drive and the mistakes that happen when one number becomes the diagnosis.',
    format: 'rounds', level: 4, minutes: 16, domain: 'renal-metabolic',
    concepts: ['lactate', 'oxygen-delivery', 'shock', 'uncertainty'],
    chapters: [
      { id: 'myth', title: 'The useful myth and where it breaks', seconds: 210, conceptIds: ['lactate'] },
      { id: 'prod', title: 'Production without global dysoxia', seconds: 260, conceptIds: ['lactate'] },
      { id: 'clear', title: 'Clearance matters', seconds: 220, conceptIds: ['lactate'] },
      { id: 'trend', title: 'Use the trajectory with the patient', seconds: 270, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Generate multiple mechanisms for hyperlactatemia and interpret the trend alongside perfusion rather than alone.'],
  },
  {
    id: 'deep-crrt', title: 'CRRT without memorizing the machine',
    subtitle: 'Build diffusion, convection, clearance and net fluid removal from first principles.',
    format: 'deep-dive', level: 4, minutes: 42, domain: 'renal-metabolic',
    concepts: ['crrt', 'acid-base', 'antimicrobial-pkpd', 'shock'],
    chapters: [
      { id: 'why', title: 'What problem are you asking CRRT to solve?', seconds: 360, conceptIds: ['crrt'] },
      { id: 'diffusion', title: 'Diffusion', seconds: 480, conceptIds: ['crrt'] },
      { id: 'convection', title: 'Convection', seconds: 480, conceptIds: ['crrt'] },
      { id: 'fluid', title: 'Net ultrafiltration is a hemodynamic intervention', seconds: 420, conceptIds: ['crrt', 'shock'] },
      { id: 'dose', title: 'Prescribed dose versus delivered dose', seconds: 420, conceptIds: ['crrt'] },
      { id: 'drugs', title: 'The circuit changes pharmacology too', seconds: 360, conceptIds: ['antimicrobial-pkpd'] },
    ],
    status: 'planned', outcomes: ['Explain common CRRT modes from transport mechanisms and reason about solute, acid-base, fluid and drug-clearance consequences.'],
  },
  {
    id: 'deep-pac', title: 'Pulmonary artery catheters: numbers only matter if the waveforms are real',
    subtitle: 'Chamber waveforms, cardiac output, oxygen extraction and model testing.',
    format: 'deep-dive', level: 5, minutes: 48, domain: 'imaging-monitoring',
    concepts: ['pa-catheter', 'rv-failure', 'oxygen-extraction', 'shock', 'uncertainty'],
    chapters: [
      { id: 'route', title: 'RA → RV → PA → wedge', seconds: 480, conceptIds: ['pa-catheter'] },
      { id: 'zero', title: 'Bad measurement creates bad physiology', seconds: 360, conceptIds: ['pa-catheter'] },
      { id: 'flow', title: 'Thermodilution and flow', seconds: 480, conceptIds: ['pa-catheter'] },
      { id: 'o2', title: 'SvO₂ belongs in the same model', seconds: 420, conceptIds: ['oxygen-extraction'] },
      { id: 'cases', title: 'Use serial data to falsify a model', seconds: 780, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Recognize the major pressure waveforms and integrate pressures, flow and oxygen extraction into one hemodynamic model.'],
  },
  {
    id: 'deep-ecmo', title: 'ECMO: follow the blood',
    subtitle: 'Understand extracorporeal support by tracing drainage, pump, membrane lung, return and native circulation.',
    format: 'deep-dive', level: 5, minutes: 50, domain: 'multisystem',
    concepts: ['ecmo', 'oxygen-delivery', 'rv-failure', 'ards'],
    chapters: [
      { id: 'circuit', title: 'The circuit is an extra circulation', seconds: 480, conceptIds: ['ecmo'] },
      { id: 'vv', title: 'VV: gas exchange, not a new heart', seconds: 540, conceptIds: ['ecmo', 'ards'] },
      { id: 'va', title: 'VA: flow changes loading conditions', seconds: 600, conceptIds: ['ecmo', 'rv-failure'] },
      { id: 'fail', title: 'Recirculation, access problems and differential hypoxemia', seconds: 600, conceptIds: ['ecmo'] },
      { id: 'do2', title: 'Come back to oxygen delivery', seconds: 480, conceptIds: ['oxygen-delivery'] },
    ],
    status: 'planned', outcomes: ['Distinguish VV and VA support physiology and reason through common circuit/patient mismatch patterns.'],
  },
  {
    id: 'rounds-sedation', title: 'The agitated ventilated patient: do not reflexively deepen sedation',
    subtitle: 'Pain, dyssynchrony, delirium, hypoxemia and physiology can all look like agitation.',
    format: 'rounds', level: 3, minutes: 18, domain: 'pharmacology',
    concepts: ['sedation-analgesia', 'delirium', 'vent-troubleshooting'],
    chapters: [
      { id: 'why', title: 'Agitation is a sign, not a diagnosis', seconds: 240, conceptIds: ['sedation-analgesia'] },
      { id: 'pain', title: 'Analgesia before amnesia', seconds: 240, conceptIds: ['sedation-analgesia'] },
      { id: 'vent', title: 'When the ventilator is causing the fight', seconds: 300, conceptIds: ['vent-troubleshooting'] },
      { id: 'brain', title: 'Delirium and the ICU environment', seconds: 300, conceptIds: ['delirium'] },
    ],
    status: 'planned', outcomes: ['Build a differential for agitation before escalating sedation and recognize when the underlying problem is pain, ventilator interaction or delirium.'],
  },
  {
    id: 'case-sepsis-crrt', title: 'Audio Case: septic shock + AKI + fluid accumulation',
    subtitle: 'Pressors are rising, oxygenation is worsening and the kidneys have stopped keeping up.',
    format: 'audio-case', level: 5, minutes: 26, domain: 'multisystem',
    concepts: ['shock', 'source-control', 'crrt', 'antimicrobial-pkpd', 'multisystem-tradeoffs', 'uncertainty'],
    chapters: [
      { id: 'handoff', title: 'The trajectory matters', seconds: 300, conceptIds: ['shock'] },
      { id: 'source', title: 'What has not been controlled?', seconds: 300, conceptIds: ['source-control'] },
      { id: 'kidney', title: 'AKI changes the treatment landscape', seconds: 360, conceptIds: ['crrt'] },
      { id: 'fluid', title: 'Removing fluid from a shocked patient', seconds: 360, conceptIds: ['multisystem-tradeoffs'], prompt: 'What response would tell you the net fluid-removal strategy is too aggressive?' },
      { id: 'drugs', title: 'Changing clearance changes drug exposure', seconds: 240, conceptIds: ['antimicrobial-pkpd'] },
    ],
    status: 'planned', outcomes: ['Integrate source control, hemodynamics, renal support and drug exposure in a changing multisystem patient.'],
  }
];

export const MENTAL_REPS: MentalRep[] = [
  {
    id: 'rep-push-dose-pressor', title: 'Push-dose pressor', subtitle: 'Medication safety first: prepare, verify, label, give, observe, reassess.',
    level: 3, domain: 'procedures', minutes: 8, concepts: ['push-dose-pressor', 'medication-safety', 'shock'],
    disclaimer: 'Mental rehearsal only. Use your service protocol, pharmacy-standard concentration, medical direction and local medication-safety process.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'See the patient', narration: 'You are at the bedside. The pressure is falling and you have decided a short bridge is needed while definitive support is prepared. Before touching a vial, state the physiologic problem you are treating.', pauseSeconds: 5, prompt: 'What response do you expect, and what adverse response would make you stop?' },
      { id: 'orient', phase: 'orientation', title: 'Slow the medication step down', narration: 'High-risk medication errors happen when urgency outruns verification. Separate the patient decision from the preparation task. Read the source concentration. Read your protocol. Do not build the final concentration from memory alone.', danger: true },
      { id: 'equip', phase: 'equipment', title: 'Build a clean workspace', narration: 'Picture the syringe, label, medication source and reference in one uncluttered field. Keep look-alike syringes out of that field. Prepare only one high-risk drug at a time.', visual: 'medication-prep' },
      { id: 'verify', phase: 'decision', title: 'Independent verification', narration: 'Before administration, verify drug, concentration, dose, route, patient and indication. Say them out loud. If the concentration does not match the standard you expected, stop and reconcile it.', pauseSeconds: 4, prompt: 'Can you state the six checks without looking?' },
      { id: 'give', phase: 'sequence', title: 'Administer and watch physiology', narration: 'Give according to local protocol through a verified line. Your attention immediately returns to the patient and monitor. Watch rhythm, pressure, perfusion and the clinical endpoint you named before the dose.', visual: 'monitor-response' },
      { id: 'comp', phase: 'complication', title: 'The response is information', narration: 'If the response is excessive, absent or physiologically inconsistent, do not automatically repeat the same action. Recheck the line, concentration, rhythm and your diagnosis.', danger: true, prompt: 'What finding would tell you your original hemodynamic model may be wrong?' },
      { id: 'debrief', phase: 'debrief', title: 'Close the loop', narration: 'The mental anchor is simple: indication, standardized concentration, verify, label, administer, reassess, and transition to definitive support. The procedure is not drawing up a syringe. The procedure is safe physiology-guided medication use.' },
    ],
  },
  {
    id: 'rep-blood', title: 'Start blood safely', subtitle: 'From order and product verification to the first minutes of transfusion and reaction recognition.',
    level: 3, domain: 'procedures', minutes: 10, concepts: ['transfusion', 'oxygen-delivery'],
    disclaimer: 'Mental rehearsal only. Product verification, tubing, warming, rates and reaction protocols vary; follow local blood-bank policy and medical direction.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Why blood?', narration: 'Before you spike anything, name what you are treating: oxygen-carrying capacity, hemorrhagic shock, a component deficiency, or a specific protocol target.', prompt: 'What endpoint will tell you the transfusion is helping?' },
      { id: 'verify', phase: 'orientation', title: 'Identity is the critical step', narration: 'Pause over the product and the patient. Perform the required patient, product, compatibility and expiration checks exactly as your system requires. This is a deliberate interruption, not paperwork.' , danger: true},
      { id: 'setup', phase: 'equipment', title: 'Build the circuit', narration: 'Picture the approved blood tubing and filter, compatible carrier fluid if required by policy, warming equipment when indicated, patent vascular access, and monitoring already running before the product starts.', visual: 'blood-circuit' },
      { id: 'start', phase: 'sequence', title: 'The first minutes matter', narration: 'Begin according to policy and stay clinically present. Reassess the patient, not only the pump. A reaction can begin with subtle symptoms before the monitor changes.', visual: 'monitor-response' },
      { id: 'reaction', phase: 'complication', title: 'If the patient changes', narration: 'New fever, chills, dyspnea, pain, hypotension, rash or a sense that something is wrong demands immediate reassessment and the local transfusion-reaction process. Do not explain away a new change simply because the patient was already sick.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication. Identity. Product. Circuit. Patient. Early reassessment. Reaction recognition. Documentation and response. Every time.' },
    ],
  },
  {
    id: 'rep-art-line', title: 'Arterial line', subtitle: 'Rehearse the whole system: patient, artery, catheter, transducer, waveform and troubleshooting.',
    level: 3, domain: 'procedures', minutes: 14, concepts: ['arterial-line', 'waveform-damping'],
    disclaimer: 'Mental rehearsal only. Insertion requires supervised procedural training, sterile technique and local policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Start with the purpose', narration: 'You need beat-to-beat pressure and arterial sampling. Picture the patient positioned, monitoring visible, rescue equipment available and the entire pressure system prepared before puncture.' },
      { id: 'anatomy', phase: 'orientation', title: 'See the vessel before the needle', narration: 'Visualize the artery in cross-section and long axis. If ultrasound is used, keep the actual needle tip in view rather than following a bright shaft and assuming the tip is there.', visual: 'artery-ultrasound' },
      { id: 'system', phase: 'equipment', title: 'The catheter is only half the procedure', narration: 'Mentally trace catheter to tubing, flush system, pressure source, transducer, cable and monitor. An excellent puncture connected to a poor monitoring system gives poor data.', visual: 'transducer-system' },
      { id: 'level', phase: 'confirmation', title: 'Level and zero', narration: 'Level the transducer to the reference point used by your unit, zero to atmosphere, then restore the system to the patient. Understand what happens to displayed pressure when the transducer is too high or too low.', prompt: 'Transducer too low: what happens to the displayed pressure?' },
      { id: 'wave', phase: 'confirmation', title: 'Interrogate the waveform', narration: 'Do not accept a number without its waveform. Look at upstroke, systolic peak, dicrotic notch, diastolic runoff and respiratory variation in context.', visual: 'arterial-waveform' },
      { id: 'square', phase: 'decision', title: 'Test the system', narration: 'When the trace looks suspicious, use the dynamic response test and inspect the circuit. Think clot, air, compliant tubing, loose connections, catheter position and excessive resonance before blaming the patient.', visual: 'square-wave-test' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Patient, artery, catheter, level, zero, waveform, dynamic response. The arterial line is a measurement system, not simply a line in an artery.' },
    ],
  },
  {
    id: 'rep-efast', title: 'eFAST mental sweep', subtitle: 'Probe position, image orientation, target spaces and the discipline of a repeatable exam.',
    level: 3, domain: 'procedures', minutes: 12, concepts: ['efast'],
    disclaimer: 'Mental rehearsal only. Diagnostic ultrasound requires supervised image-acquisition training and must be integrated with the clinical picture.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Set the question', narration: 'You are not doing ultrasound because a probe is available. State the question: is there blood where it should not be, pericardial fluid, or pleural evidence of pneumothorax or hemothorax?', visual: 'efast-map', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'You are not doing ultrasound because a probe is available. State the question: is there blood where it should not be, pericardial fluid, or pleural evidence of pneumothorax or hemothorax?', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/f7233a4f-49e5-4bda-902e-5bf5957a9021.mp3' } },
      { id: 'orientation', phase: 'orientation', title: 'Anchor orientation every time', narration: 'Before interpreting pathology, prove to yourself which side of the screen is cephalad, which anatomy you are seeing, and whether your probe marker matches the convention you are using.', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Before interpreting pathology, prove to yourself which side of the screen is cephalad, which anatomy you are seeing, and whether your probe marker matches the convention you are using.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/2ac01d70-907d-4deb-862f-0199e9048964.mp3' } },
      { id: 'ruq', phase: 'sequence', title: 'RUQ', narration: 'Sweep through the hepatorenal interface, diaphragm and inferior liver tip. Do not take one frozen view and call the window negative. Search the dependent spaces.', visual: 'efast-ruq', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Sweep through the hepatorenal interface, diaphragm and inferior liver tip. Do not take one frozen view and call the window negative. Search the dependent spaces.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/6f2d9ce4-ca13-4de8-b31a-4ca27002e1d7.mp3' } },
      { id: 'luq', phase: 'sequence', title: 'LUQ', narration: 'Find spleen, kidney and diaphragm. The geometry is less forgiving. Sweep deliberately rather than chasing the textbook picture.', visual: 'efast-luq', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Find spleen, kidney and diaphragm. The geometry is less forgiving. Sweep deliberately rather than chasing the textbook picture.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/9882ce63-7637-4b89-b5ab-3c7700d9b690.mp3' } },
      { id: 'pelvis', phase: 'sequence', title: 'Pelvis', narration: 'Use the bladder as your acoustic window and examine the dependent space around it in the appropriate planes.', visual: 'efast-pelvis', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Use the bladder as your acoustic window and examine the dependent space around it in the appropriate planes.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/2e6bc861-8638-494d-aee6-376657c5cdb7.mp3' } },
      { id: 'cardiac', phase: 'sequence', title: 'Pericardium', narration: 'Acquire the best cardiac window the patient gives you and identify the pericardial space before deciding fluid is present. Fat, pleural fluid and artifact can mislead.', visual: 'efast-cardiac', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Acquire the best cardiac window the patient gives you and identify the pericardial space before deciding fluid is present. Fat, pleural fluid and artifact can mislead.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/842ec09c-d369-417d-86d8-2098c24f4f01.mp3' } },
      { id: 'lung', phase: 'sequence', title: 'Pleura', narration: 'Interrogate the pleural line bilaterally. Lung sliding is a dynamic sign. When absent, use the rest of the ultrasound and clinical picture rather than treating one sign as the diagnosis.', visual: 'efast-lung', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Interrogate the pleural line bilaterally. Lung sliding is a dynamic sign. When absent, use the rest of the ultrasound and clinical picture rather than treating one sign as the diagnosis.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/9ac0ac09-9191-4d60-a043-90caeae7ddb3.mp3' } },
      { id: 'repeat', phase: 'debrief', title: 'A negative exam is time-stamped', narration: 'Trauma evolves. The mental anchor is orientation, systematic windows, sweeping rather than snapshotting, and repeat examination when physiology changes.', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Trauma evolves. The mental anchor is orientation, systematic windows, sweeping rather than snapshotting, and repeat examination when physiology changes.', reviewed: false, previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/3ba2180d-bd3a-4795-b579-681d341b2ea0.mp3' } },
    ],
  },
  {
    id: 'rep-chest-tube', title: 'Chest tube / pleural drain', subtitle: 'Anatomy, setup, safe sequence, system behavior and early failure recognition.',
    level: 3, domain: 'procedures', minutes: 15, concepts: ['chest-tube'],
    disclaimer: 'Mental rehearsal only. Tube thoracostomy requires supervised hands-on training, credentialing, sterile technique and local procedural policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Indication before incision', narration: 'Picture the patient and state what you are treating. Tension physiology, hemothorax and ongoing pleural air are related problems but they shape urgency, equipment and aftercare differently.' },
      { id: 'anatomy', phase: 'orientation', title: 'Build the chest wall in your head', narration: 'See skin, subcutaneous tissue, intercostal muscles, rib, neurovascular bundle and parietal pleura. Orient to the safe procedural zone taught by your credentialing program and local policy.', visual: 'chest-wall-anatomy' },
      { id: 'setup', phase: 'equipment', title: 'Prepare the whole system', narration: 'The procedure includes the drain system, connections, dressing, suction or water seal plan, monitoring and analgesia strategy. Do not discover missing pieces after entering the pleural space.', visual: 'drain-system' },
      { id: 'sequence', phase: 'sequence', title: 'Controlled entry', narration: 'Mentally rehearse deliberate tissue handling and confirmation that the pleural space has actually been entered before advancing the drain. Maintain awareness of depth and direction rather than using force.', danger: true },
      { id: 'connect', phase: 'confirmation', title: 'Connect and ask what changed', narration: 'Once connected, reassess patient physiology and the drain system together. Improvement should make physiologic sense. If nothing changes, question position, patency, diagnosis and the system.', visual: 'drain-water-seal' },
      { id: 'failure', phase: 'complication', title: 'A drain can fail after it worked', narration: 'Kinked tubing, disconnection, migration, clot, dependent loops or a new air leak can turn a functioning drain into a problem. Trace from patient outward whenever physiology worsens.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication, anatomy, complete setup, controlled pleural entry, connection, patient response, system response, and continuous troubleshooting.' },
    ],
  },
  {
    id: 'rep-central-line', title: 'Ultrasound-guided IJ central line', subtitle: 'Scan, identify, track the tip, confirm the vessel, control the wire, then dilate.',
    level: 3, domain: 'procedures', minutes: 16, concepts: ['central-line', 'medication-safety'],
    disclaimer: 'Mental rehearsal only. Central venous access requires supervised procedural training, maximal sterile precautions, credentialing and local policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Know why you need the line', narration: 'State the indication and whether a safer or faster alternative can meet the immediate need. Prepare monitoring, sterile equipment and a plan for complications before beginning.' },
      { id: 'scan', phase: 'orientation', title: 'Map anatomy before sterile entry', narration: 'Identify vein and artery in more than one plane. Use compressibility, pulsatility and anatomy rather than trusting color alone. Look for overlap and thrombus.', visual: 'ijv-real' },
      { id: 'tip', phase: 'sequence', title: 'The bright dot must be the tip', narration: 'With real-time ultrasound, keep the needle tip accounted for. A shaft crossing the ultrasound plane can look convincing while the actual tip has traveled deeper.', prompt: 'What could you injure if you advance while the true tip is lost from view?' },
      { id: 'confirm', phase: 'confirmation', title: 'Confirm venous access before dilation', narration: 'Do not let dark blood color alone make the decision in shock or hypoxemia. Use the confirmation method required by your environment before a dilator enters the patient.', danger: true },
      { id: 'wire', phase: 'sequence', title: 'The wire is never an afterthought', narration: 'Pass smoothly without force, maintain control of the wire, and verify that it is where you think it is. Seeing the wire in the intended vessel before dilation is a powerful safety checkpoint.' },
      { id: 'comp', phase: 'complication', title: 'If something does not fit, stop', narration: 'Resistance, unexpected pressure, ectopy, abnormal ultrasound position or patient deterioration are information. Stop and reconcile the anatomy before progressing.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication, anatomy, sterile setup, tip visibility, vessel confirmation, wire control, confirmation before dilation, then post-procedure reassessment.' },
    ],
  },
  {
    id: 'rep-io', title: 'Intraosseous access', subtitle: 'Rapid access still requires landmark discipline, confirmation and repeated site reassessment.',
    level: 2, domain: 'procedures', minutes: 8, concepts: ['io-access', 'medication-safety', 'shock'],
    disclaimer: 'Mental rehearsal only. Use only approved sites/devices and the manufacturer instructions, service protocol and supervised skills training for your equipment.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Access is the goal, not the device', narration: 'The patient needs reliable vascular access now. Decide whether IO is appropriate rather than repeatedly delaying resuscitation for difficult peripheral attempts.' },
      { id: 'landmark', phase: 'orientation', title: 'Find the approved landmark deliberately', narration: 'Picture the anatomy for the site and device you actually use. Palpate and identify the target before touching the driver.', visual: 'io-landmark' },
      { id: 'place', phase: 'sequence', title: 'Controlled placement', narration: 'Stabilize the limb and device, follow the device-specific technique, and stop when the expected endpoint is reached rather than adding unnecessary depth.' },
      { id: 'confirm', phase: 'confirmation', title: 'Prove it works', narration: 'Assess stability, aspiration if applicable, flush behavior and the surrounding tissue. A line that does not behave as expected is not automatically usable.' },
      { id: 'comp', phase: 'complication', title: 'Keep looking at the limb', narration: 'Swelling, leaking, worsening pain, resistance or neurovascular change can signal extravasation or another complication. Reassess after use, not only at insertion.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Decision, landmark, device-specific placement, confirmation, securement and repeated site checks.' },
    ],
  },
  {
    id: 'rep-vent-emergency', title: 'Sudden ventilator deterioration', subtitle: 'Patient first, then tube, circuit, pressure pattern and physiology.',
    level: 3, domain: 'procedures', minutes: 12, concepts: ['vent-troubleshooting', 'ppv-hemodynamics', 'dead-space'],
    disclaimer: 'Mental rehearsal only. Acute airway/ventilator emergencies require local protocols, immediate bedside assessment and escalation when needed.',
    beats: [
      { id: 'alarm', phase: 'arrival', title: 'The alarm is a symptom', narration: 'The patient suddenly desaturates and the ventilator is alarming. Look at the patient before the screen: chest movement, color, waveform capnography, hemodynamics and level of distress.', visual: 'vent-check' },
      { id: 'oxygen', phase: 'decision', title: 'Can you trust the ventilator and circuit?', narration: 'If oxygenation or ventilation is immediately threatened and the device cannot be trusted, transition to a reliable rescue method while troubleshooting according to your environment.' },
      { id: 'trace', phase: 'sequence', title: 'Trace the system', narration: 'Mentally move from patient to tube to connectors to circuit to machine. Disconnection, obstruction, displacement, pneumothorax and breath stacking leave different clues.', visual: 'vent-check' },
      { id: 'pressure', phase: 'decision', title: 'Use peak and plateau as physiology', narration: 'High peak with a relatively preserved plateau points you toward resistance. High peak and high plateau point you toward compliance or pressure surrounding the lung.', prompt: 'What bedside problems belong in each category?' },
      { id: 'hemo', phase: 'complication', title: 'The circulation may be the first organ failing', narration: 'Auto-PEEP, tension physiology and excessive intrathoracic pressure can present as hypotension before oxygen saturation collapses. The ventilator and circulation are one system.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Patient first. Rescue ventilation if needed. Trace the airway and circuit. Separate resistance from compliance. Look for pressure-related circulatory failure. Reassess after every intervention.' },
    ],
  },
  {
    id: 'rep-evd', title: 'Move a patient with an EVD', subtitle: 'Clamp, move, re-level, verify, reopen according to the ordered drainage strategy.',
    level: 3, domain: 'procedures', minutes: 8, concepts: ['evd', 'icp-cpp'],
    disclaimer: 'Mental rehearsal only. EVD management must follow the neurosurgical order, device instructions and local neurocritical-care policy.',
    beats: [
      { id: 'before', phase: 'arrival', title: 'Read the order before the room moves', narration: 'Know the ordered reference level, drainage strategy and whether the system is currently open or clamped. A drainage device without its order is an unsafe abstraction.' },
      { id: 'level', phase: 'orientation', title: 'See the reference point', narration: 'Visualize the reference point on the patient and the leveling device. The chamber height determines the hydrostatic threshold for drainage.', visual: 'evd-level' },
      { id: 'clamp', phase: 'sequence', title: 'Secure the system for movement', narration: 'Before changing bed height or patient position, manage the drain exactly as ordered so a sudden vertical shift cannot unintentionally over-drain or stop drainage.', danger: true },
      { id: 'move', phase: 'sequence', title: 'Move the patient, not the reference logic', narration: 'After the move, the old chamber position is no longer meaningful. Re-establish the patient reference and level the system again before returning it to the ordered state.', visual: 'evd-level' },
      { id: 'verify', phase: 'confirmation', title: 'Confirm patient + system', narration: 'Reassess ICP waveform if monitored, drainage, neurologic state, tubing and clamps. A number that changed after repositioning may reflect the measurement system before it reflects the brain.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Order, clamp for movement as required, move, re-level to the patient, verify, then return to the prescribed drainage state.' },
    ],
  },
  {
    id: 'rep-mtp', title: 'Massive transfusion mental run', subtitle: 'Run hemorrhagic resuscitation as a coordinated system, not a stack of blood bags.',
    level: 4, domain: 'procedures', minutes: 14, concepts: ['massive-transfusion', 'transfusion', 'shock', 'oxygen-delivery'],
    disclaimer: 'Mental rehearsal only. Product ratios, activation criteria, medication adjuncts and laboratory targets vary by institution; follow the active MTP, blood-bank process and medical direction.',
    beats: [
      { id: 'activate', phase: 'arrival', title: 'Recognize the system problem', narration: 'This is not ordinary transfusion. The patient is bleeding faster than routine workflow can keep up. Activate the local hemorrhage system early enough that blood bank, access, warming and source control can move together.' },
      { id: 'roles', phase: 'equipment', title: 'Build the room', narration: 'Picture designated access, rapid infuser or approved delivery setup, warmer, monitoring, blood verification workflow, calcium and laboratory plan according to protocol, and someone explicitly tracking products and time.' },
      { id: 'source', phase: 'decision', title: 'Blood does not stop bleeding', narration: 'Resuscitation buys time for source control. Continually ask where the blood is going and what definitive action ends that loss.' },
      { id: 'phys', phase: 'complication', title: 'Watch what resuscitation itself changes', narration: 'Temperature, ionized calcium, fibrinogen, platelet function, acid-base state and dilution can deteriorate as the resuscitation grows. Anticipate them instead of discovering them late.', danger: true },
      { id: 'response', phase: 'confirmation', title: 'Follow physiology, not only pressure', narration: 'Reassess mental status, pulse quality, perfusion, shock index or hemodynamics, lactate trajectory when appropriate, bleeding rate and the response to source control.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Activate early, verify products, warm everything, maintain access and monitoring, anticipate calcium/coagulation/temperature problems, and never lose sight of source control.' },
    ],
  }
];

export const EPISODE_BY_ID = Object.fromEntries(EPISODES.map((e) => [e.id, e]));
export const REP_BY_ID = Object.fromEntries(MENTAL_REPS.map((r) => [r.id, r]));
