import type { AudioEpisode, MentalRep } from './types';
import { EXPERT_EPISODES } from './expertEpisodes';

const rvTranscript = `You’re at the bedside. The blood pressure has fallen after intubation. Before you reach for fluid, build the physiology in your head. Picture the right ventricle pushing against the pulmonary circulation. Positive pressure has changed venous return, pulmonary vascular resistance, and the pressure surrounding the heart. Your job is not to chase a number. Your job is to decide what changed, predict what your intervention should do, and then watch whether the patient proves your model right.`;

const oxygenDeliveryTranscript = "Your pulse oximeter says ninety-eight percent. That feels reassuring. But saturation answers a very specific question: what fraction of the available hemoglobin binding sites are carrying oxygen? It does not tell you how much hemoglobin you have, and it does not tell you how much blood the heart is moving.\n\nThat distinction is the beginning of oxygen-delivery thinking.\n\nOxygen delivery, D O 2, is cardiac output multiplied by arterial oxygen content. Arterial oxygen content is dominated by oxygen bound to hemoglobin. A useful bedside approximation is one point three four times hemoglobin times arterial saturation, plus a very small contribution from oxygen dissolved in plasma.\n\nThat means three patients can all have an S P O 2 of ninety-eight percent and have very different oxygen delivery.\n\nPicture the first patient. Hemoglobin fourteen. Cardiac output five liters per minute. Saturation ninety-eight percent. Nothing surprising.\n\nNow keep saturation at ninety-eight percent but drop the hemoglobin to five. Every remaining red cell may be beautifully saturated, but there are far fewer red cells carrying oxygen. The pulse oximeter still looks excellent while arterial oxygen content has fallen dramatically.\n\nNow take a different patient. Hemoglobin is normal. Saturation is ninety-eight percent. But cardiac output has collapsed because of severe pump failure. The blood contains plenty of oxygen per deciliter, but not enough blood is reaching the tissues each minute. Again, the pulse oximeter can look perfect.\n\nThis is why expert critical-care reasoning does not ask only, “Is the blood oxygenated?” It asks, “Is enough oxygen actually being delivered?”\n\nNow add the tissues.\n\nOxygen consumption, V O 2, is what the body removes from the delivered oxygen. When delivery falls, tissues can initially compensate by extracting a larger fraction. Venous oxygen saturation falls because more oxygen is being taken out before the blood returns to the right heart. That compensation has limits. Below a critical level of delivery, oxygen consumption can become supply dependent.\n\nDo not turn that into another single-number rule. A low venous saturation can reflect low cardiac output, anemia, increased metabolic demand, arterial hypoxemia, or combinations of them. A surprisingly high venous saturation can occur when extraction is impaired or when flow distribution is abnormal. The number only becomes useful when it sits inside a physiologic model.\n\nHere is the mental shortcut I want you to keep.\n\nSaturation tells you how full the buses are.\n\nHemoglobin tells you how many buses you have.\n\nCardiac output tells you how fast the buses are moving.\n\nOxygen delivery asks how many passengers actually arrive each minute.\n\nSo the next time you see an S P O 2 of ninety-eight percent in a patient who looks poorly perfused, do not let the monitor end the conversation. Ask about hemoglobin. Ask about flow. Ask what the tissues are extracting. Ask whether the patient is warm or cold, alert or altered, making urine or shutting down, clearing lactate or accumulating it.\n\nA normal saturation can coexist with profoundly inadequate oxygen delivery.\n\nYour retrieval question is this: if saturation stays the same, name the two major variables that can still make oxygen delivery collapse.\n\nThe answer is hemoglobin and cardiac output.\n\nAnd the expert move is not merely remembering the formula. It is noticing when the patient and the pulse oximeter are telling different stories.";

const CORE_EPISODES: AudioEpisode[] = [
  {
    id: 'rounds-rv-intubation', title: 'Why intubation can crash the failing RV',
    subtitle: 'Build the hemodynamic model before you chase the blood pressure.',
    format: 'rounds', level: 4, minutes: 12, domain: 'cardiac',
    concepts: ['rv-failure', 'pvr', 'ppv-hemodynamics', 'ventricular-interdependence', 'uncertainty'],
    status: 'voice-ready',
    chapters: [
      { id: 'scene', title: 'The pressure falls', seconds: 90, conceptIds: ['rv-failure'], prompt: 'Name three mechanisms that could reduce forward flow after intubation.' },
      { id: 'preload', title: 'Venous return changes', seconds: 150, conceptIds: ['venous-return', 'ppv-hemodynamics'] },
      { id: 'afterload', title: 'The RV sees a different afterload', seconds: 180, conceptIds: ['pvr', 'rv-failure'] },
      { id: 'septum', title: 'The LV becomes part of the problem', seconds: 150, conceptIds: ['ventricular-interdependence'] },
      { id: 'test', title: 'Make a prediction', seconds: 150, conceptIds: ['uncertainty'], prompt: 'What finding would make you abandon your current model?' },
    ],
    voice: {
      tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US',
      transcript: rvTranscript, reviewed: false,
      previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/000b3aaa-27e2-4489-94db-af1f3e5636e9.mp3',
    },
    outcomes: [
      'Explain the distinct effects of positive pressure on venous return, RV afterload and LV transmural pressure.',
      'Describe why RV distension can reduce LV filling through ventricular interdependence.',
      'State what response you expect from an intervention and what finding would falsify your model.',
    ],
  },
  {
    id: 'dose-normal-spo2', title: 'A normal SpO₂ can still hide terrible oxygen delivery',
    subtitle: 'Five-minute Daily Dose: saturation is only one term in the oxygen-delivery equation.',
    format: 'daily-dose', level: 3, minutes: 6, domain: 'hemodynamics',
    concepts: ['oxygen-delivery', 'oxygen-extraction'],
    chapters: [{ id: 'core', title: 'Saturation is not delivery', seconds: 360, conceptIds: ['oxygen-delivery', 'oxygen-extraction'], prompt: 'If saturation stays the same, name the two major variables that can still make oxygen delivery collapse.' }],
    status: 'voice-ready',
    voice: {
      tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US',
      transcript: oxygenDeliveryTranscript, reviewed: false,
      previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/0f74aa7b-257f-4d8b-a546-b073a98e4e8a.mp3',
    },
    outcomes: ['Explain how hemoglobin and cardiac output can make oxygen delivery inadequate despite a normal saturation.'],
  },
  {
    id: 'literacy-transmural', title: 'ICU Literacy: transmural pressure',
    subtitle: 'The pressure that actually distends a chamber is not always the number on the monitor.',
    format: 'icu-literacy', level: 4, minutes: 9, domain: 'foundations',
    concepts: ['preload', 'ppv-hemodynamics'],
    chapters: [{ id: 'core', title: 'Inside pressure minus outside pressure', seconds: 540, conceptIds: ['preload', 'ppv-hemodynamics'] }],
    status: 'scripted', outcomes: ['Use transmural pressure to explain why measured filling pressures change with intrathoracic pressure.'],
  },
  {
    id: 'deep-shock', title: 'Shock is a flow problem before it is a blood-pressure problem',
    subtitle: 'Phenotype the circulation: flow, tone, congestion, oxygen delivery and organ response.',
    format: 'deep-dive', level: 4, minutes: 38, domain: 'hemodynamics',
    concepts: ['shock', 'oxygen-delivery', 'oxygen-extraction', 'venous-return', 'lactate'],
    chapters: [
      { id: 'frame', title: 'Stop naming shock by one number', seconds: 420, conceptIds: ['shock'] },
      { id: 'flow', title: 'Flow and venous return', seconds: 600, conceptIds: ['venous-return'] },
      { id: 'do2', title: 'Delivery and extraction', seconds: 600, conceptIds: ['oxygen-delivery', 'oxygen-extraction'] },
      { id: 'lactate', title: 'Lactate without superstition', seconds: 420, conceptIds: ['lactate'] },
      { id: 'integration', title: 'Mixed shock', seconds: 240, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Phenotype mixed shock and choose a testable physiologic intervention rather than reflexively treating a pressure.'],
  },
  {
    id: 'case-ards-rv', title: 'Audio Case: ARDS + RV failure',
    subtitle: 'An unfolding multisystem case with no clean single-organ answer.',
    format: 'audio-case', level: 5, minutes: 22, domain: 'multisystem',
    concepts: ['ards', 'rv-failure', 'pvr', 'peep', 'multisystem-tradeoffs', 'uncertainty'],
    chapters: [
      { id: 'arrival', title: 'The handoff', seconds: 240, conceptIds: ['ards', 'rv-failure'], prompt: 'Before more data arrives, what are your competing priorities?' },
      { id: 'vent', title: 'The vent becomes part of the circulation', seconds: 360, conceptIds: ['peep', 'pvr'] },
      { id: 'echo', title: 'The RV is telling you something', seconds: 360, conceptIds: ['rv-failure', 'ventricular-interdependence'] },
      { id: 'choice', title: 'There is no free intervention', seconds: 360, conceptIds: ['multisystem-tradeoffs'], prompt: 'Choose your next move and name the organ you could worsen.' },
    ],
    status: 'planned', outcomes: ['Balance lung recruitment and RV load while explicitly stating uncertainty and tradeoffs.'],
  },
  {
    id: 'literacy-stressed-volume', title: 'ICU Literacy: stressed volume',
    subtitle: 'Why venoconstriction can change effective preload without adding a drop of fluid.',
    format: 'icu-literacy', level: 4, minutes: 11, domain: 'hemodynamics',
    concepts: ['stressed-volume', 'venous-return', 'preload'],
    chapters: [
      { id: 'container', title: 'The circulation as a pressure-generating container', seconds: 180, conceptIds: ['stressed-volume'] },
      { id: 'gradient', title: 'Mean systemic filling pressure and venous return', seconds: 240, conceptIds: ['venous-return'] },
      { id: 'pressor', title: 'Why venoconstriction is not the same as a fluid bolus', seconds: 240, conceptIds: ['stressed-volume', 'preload'] },
    ],
    status: 'planned', outcomes: ['Explain stressed versus unstressed volume and use it to reason about venous tone, fluids and pressors.'],
  },
  {
    id: 'rounds-lactate', title: 'Lactate is not a tissue-hypoxia meter',
    subtitle: 'Production, clearance, adrenergic drive and the mistakes that happen when one number becomes the diagnosis.',
    format: 'rounds', level: 4, minutes: 16, domain: 'renal-metabolic',
    concepts: ['lactate', 'oxygen-delivery', 'shock', 'uncertainty'],
    chapters: [
      { id: 'myth', title: 'The useful myth and where it breaks', seconds: 210, conceptIds: ['lactate'] },
      { id: 'prod', title: 'Production without global dysoxia', seconds: 260, conceptIds: ['lactate'] },
      { id: 'clear', title: 'Clearance matters', seconds: 220, conceptIds: ['lactate'] },
      { id: 'trend', title: 'Use the trajectory with the patient', seconds: 270, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Generate multiple mechanisms for hyperlactatemia and interpret the trend alongside perfusion rather than alone.'],
  },
  {
    id: 'deep-crrt', title: 'CRRT without memorizing the machine',
    subtitle: 'Build diffusion, convection, clearance and net fluid removal from first principles.',
    format: 'deep-dive', level: 4, minutes: 42, domain: 'renal-metabolic',
    concepts: ['crrt', 'acid-base', 'antimicrobial-pkpd', 'shock'],
    chapters: [
      { id: 'why', title: 'What problem are you asking CRRT to solve?', seconds: 360, conceptIds: ['crrt'] },
      { id: 'diffusion', title: 'Diffusion', seconds: 480, conceptIds: ['crrt'] },
      { id: 'convection', title: 'Convection', seconds: 480, conceptIds: ['crrt'] },
      { id: 'fluid', title: 'Net ultrafiltration is a hemodynamic intervention', seconds: 420, conceptIds: ['crrt', 'shock'] },
      { id: 'dose', title: 'Prescribed dose versus delivered dose', seconds: 420, conceptIds: ['crrt'] },
      { id: 'drugs', title: 'The circuit changes pharmacology too', seconds: 360, conceptIds: ['antimicrobial-pkpd'] },
    ],
    status: 'planned', outcomes: ['Explain common CRRT modes from transport mechanisms and reason about solute, acid-base, fluid and drug-clearance consequences.'],
  },
  {
    id: 'deep-pac', title: 'Pulmonary artery catheters: numbers only matter if the waveforms are real',
    subtitle: 'Chamber waveforms, cardiac output, oxygen extraction and model testing.',
    format: 'deep-dive', level: 5, minutes: 48, domain: 'imaging-monitoring',
    concepts: ['pa-catheter', 'rv-failure', 'oxygen-extraction', 'shock', 'uncertainty'],
    chapters: [
      { id: 'route', title: 'RA → RV → PA → wedge', seconds: 480, conceptIds: ['pa-catheter'] },
      { id: 'zero', title: 'Bad measurement creates bad physiology', seconds: 360, conceptIds: ['pa-catheter'] },
      { id: 'flow', title: 'Thermodilution and flow', seconds: 480, conceptIds: ['pa-catheter'] },
      { id: 'o2', title: 'SvO₂ belongs in the same model', seconds: 420, conceptIds: ['oxygen-extraction'] },
      { id: 'cases', title: 'Use serial data to falsify a model', seconds: 780, conceptIds: ['shock', 'uncertainty'] },
    ],
    status: 'planned', outcomes: ['Recognize the major pressure waveforms and integrate pressures, flow and oxygen extraction into one hemodynamic model.'],
  },
  {
    id: 'deep-ecmo', title: 'ECMO: follow the blood',
    subtitle: 'Understand extracorporeal support by tracing drainage, pump, membrane lung, return and native circulation.',
    format: 'deep-dive', level: 5, minutes: 50, domain: 'multisystem',
    concepts: ['ecmo', 'oxygen-delivery', 'rv-failure', 'ards'],
    chapters: [
      { id: 'circuit', title: 'The circuit is an extra circulation', seconds: 480, conceptIds: ['ecmo'] },
      { id: 'vv', title: 'VV: gas exchange, not a new heart', seconds: 540, conceptIds: ['ecmo', 'ards'] },
      { id: 'va', title: 'VA: flow changes loading conditions', seconds: 600, conceptIds: ['ecmo', 'rv-failure'] },
      { id: 'fail', title: 'Recirculation, access problems and differential hypoxemia', seconds: 600, conceptIds: ['ecmo'] },
      { id: 'do2', title: 'Come back to oxygen delivery', seconds: 480, conceptIds: ['oxygen-delivery'] },
    ],
    status: 'planned', outcomes: ['Distinguish VV and VA support physiology and reason through common circuit/patient mismatch patterns.'],
  },
  {
    id: 'rounds-sedation', title: 'The agitated ventilated patient: do not reflexively deepen sedation',
    subtitle: 'Pain, dyssynchrony, delirium, hypoxemia and physiology can all look like agitation.',
    format: 'rounds', level: 3, minutes: 18, domain: 'pharmacology',
    concepts: ['sedation-analgesia', 'delirium', 'vent-troubleshooting'],
    chapters: [
      { id: 'why', title: 'Agitation is a sign, not a diagnosis', seconds: 240, conceptIds: ['sedation-analgesia'] },
      { id: 'pain', title: 'Analgesia before amnesia', seconds: 240, conceptIds: ['sedation-analgesia'] },
      { id: 'vent', title: 'When the ventilator is causing the fight', seconds: 300, conceptIds: ['vent-troubleshooting'] },
      { id: 'brain', title: 'Delirium and the ICU environment', seconds: 300, conceptIds: ['delirium'] },
    ],
    status: 'planned', outcomes: ['Build a differential for agitation before escalating sedation and recognize when the underlying problem is pain, ventilator interaction or delirium.'],
  },
  {
    id: 'case-sepsis-crrt', title: 'Audio Case: septic shock + AKI + fluid accumulation',
    subtitle: 'Pressors are rising, oxygenation is worsening and the kidneys have stopped keeping up.',
    format: 'audio-case', level: 5, minutes: 26, domain: 'multisystem',
    concepts: ['shock', 'source-control', 'crrt', 'antimicrobial-pkpd', 'multisystem-tradeoffs', 'uncertainty'],
    chapters: [
      { id: 'handoff', title: 'The trajectory matters', seconds: 300, conceptIds: ['shock'] },
      { id: 'source', title: 'What has not been controlled?', seconds: 300, conceptIds: ['source-control'] },
      { id: 'kidney', title: 'AKI changes the treatment landscape', seconds: 360, conceptIds: ['crrt'] },
      { id: 'fluid', title: 'Removing fluid from a shocked patient', seconds: 360, conceptIds: ['multisystem-tradeoffs'], prompt: 'What response would tell you the net fluid-removal strategy is too aggressive?' },
      { id: 'drugs', title: 'Changing clearance changes drug exposure', seconds: 240, conceptIds: ['antimicrobial-pkpd'] },
    ],
    status: 'planned', outcomes: ['Integrate source control, hemodynamics, renal support and drug exposure in a changing multisystem patient.'],
  }
];

export const EPISODES: AudioEpisode[] = [...CORE_EPISODES, ...EXPERT_EPISODES];

export const MENTAL_REPS: MentalRep[] = [
  {
    id: 'rep-push-dose-pressor', title: 'Push-dose epinephrine', subtitle: 'Hands-on medication rehearsal: source concentration, dilution math, labeling, dose conversion and reassessment.',
    level: 3, domain: 'procedures', minutes: 9, concepts: ['push-dose-pressor', 'medication-safety', 'shock'],
    disclaimer: 'Mental rehearsal only. This example assumes epinephrine 1 mg in 10 mL (0.1 mg/mL = 100 mcg/mL) and a service-approved final preparation of 10 mcg/mL. If your stock concentration, pharmacy preparation or protocol differs, stop and use the local reference, medical direction and medication-safety process.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'See the patient and name the bridge', narration: 'You are at the bedside. The blood pressure is falling. You have decided push-dose epinephrine is an appropriate short bridge while definitive hemodynamic support is being prepared. Your monitor is on. Your vascular access is confirmed. Before you touch the medication, name the endpoint you are trying to improve and the response that would make you stop.', pauseSeconds: 5, prompt: 'What physiologic endpoint are you treating, and what adverse response would make you stop?' },
      { id: 'orient', phase: 'orientation', title: 'Pick up the source and read it out loud', narration: 'You grab your cardiac epinephrine syringe. Stop and read the label. One milligram in ten milliliters. That is zero point one milligram per milliliter. Convert milligrams to micrograms: zero point one milligram is one hundred micrograms. Your source concentration is one hundred micrograms per milliliter. Do not continue until the label in your hand matches that source concentration.', pauseSeconds: 4, prompt: 'Your source is 1 mg in 10 mL. How many micrograms are in each milliliter?', visual: 'epi-source', danger: true },
      { id: 'equip', phase: 'equipment', title: 'Prepare the saline syringe', narration: 'You grab a ten milliliter normal saline flush. You expel one milliliter. Look at the barrel. Nine milliliters of saline remain. Keep the syringe in your hand. Keep the source epinephrine and the label in the same clean medication workspace.', visual: 'epi-flush' },
      { id: 'verify', phase: 'sequence', title: 'Add one milliliter and do the math', narration: 'Using your approved aseptic transfer technique, draw one milliliter from the cardiac epinephrine source into the syringe containing nine milliliters of saline. You now have ten milliliters total. That one milliliter of source contributed one hundred micrograms of epinephrine. One hundred micrograms in ten milliliters equals ten micrograms per milliliter. Say the final concentration out loud: epinephrine, ten micrograms per milliliter.', pauseSeconds: 5, prompt: 'What is the final concentration, and how did you get there?', visual: 'epi-dilution', danger: true },
      { id: 'give', phase: 'confirmation', title: 'Label first. Then convert dose to volume', narration: 'Before that syringe leaves your hand, label it: epinephrine, ten micrograms per milliliter, with the additional identifiers required by your policy. Now do the dose-to-volume conversion from your protocol or order. At ten micrograms per milliliter, a ten microgram dose is one milliliter, and a twenty microgram dose is two milliliters. Verify the intended dose, route, patient, indication and line before administration. Then give only the protocol-directed amount and return your eyes to the patient and monitor.', visual: 'epi-label', pauseSeconds: 5, prompt: 'At 10 mcg/mL, how many milliliters contain 10 mcg? How many contain 20 mcg?' },
      { id: 'comp', phase: 'complication', title: 'Do not let the syringe drive the plan', narration: 'Watch the rhythm, pressure, perfusion and clinical endpoint immediately. If the response is excessive, you see a concerning tachyarrhythmia, or the physiology moves in the wrong direction, stop and reassess. If there is little or no response, do not reflexively keep pushing. Recheck the line, the prepared concentration, the delivered volume and the diagnosis while definitive support continues to come online.', danger: true, prompt: 'What finding would make you stop repeating the same action and reconsider your hemodynamic model?' },
      { id: 'debrief', phase: 'debrief', title: 'Run the preparation backward', narration: 'Replay the preparation. Cardiac epinephrine: one milligram in ten milliliters, which is one hundred micrograms per milliliter. Ten milliliter saline flush: expel one milliliter, leaving nine. Add one milliliter of the source. Now you have one hundred micrograms in ten milliliters, or ten micrograms per milliliter. Label it before it leaves your hand. Convert the ordered dose to volume. Verify. Give. Reassess. Then transition to definitive support.' },
    ],
  },
  {
    id: 'rep-blood', title: 'Start blood safely', subtitle: 'From order and product verification to the first minutes of transfusion and reaction recognition.',
    level: 3, domain: 'procedures', minutes: 10, concepts: ['transfusion', 'oxygen-delivery'],
    disclaimer: 'Mental rehearsal only. Product verification, tubing, warming, rates and reaction protocols vary; follow local blood-bank policy and medical direction.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Why blood?', narration: 'Before you spike anything, name what you are treating: oxygen-carrying capacity, hemorrhagic shock, a component deficiency, or a specific protocol target.', prompt: 'What endpoint will tell you the transfusion is helping?' },
      { id: 'verify', phase: 'orientation', title: 'Identity is the critical step', narration: 'Pick up the blood product and the order. At the bedside, match the patient identifiers and every product field your blood-bank policy requires: product type, unit identifier, compatibility label, ABO/Rh when applicable, expiration, and bag integrity. Perform the required independent check. If a single field does not match, the unit does not go up.' , danger: true},
      { id: 'setup', phase: 'equipment', title: 'Build the circuit', narration: 'Grab the approved blood tubing and filter. Prime it with the compatible solution your policy requires, clear visible air, connect the warmer if indicated, and trace the tubing from the bag all the way to the patient. Confirm the access is patent and appropriate for the intended flow. Put the pump or rapid-infuser setup in the correct configuration before you spike the unit.', visual: 'blood-circuit' },
      { id: 'start', phase: 'sequence', title: 'The first minutes matter', narration: 'Spike the verified unit using aseptic technique, hang or load it into the approved device, and record the start time and baseline assessment. Start at the policy- or order-directed rate. For the first minutes, keep your eyes on the patient: breathing, skin, pressure, temperature, pain, and anything new.', visual: 'monitor-response' },
      { id: 'reaction', phase: 'complication', title: 'If the patient changes', narration: 'If a transfusion reaction is suspected, stop the blood immediately. Keep the patient’s vascular access available using the method your local protocol specifies; do not simply restart the same unit. Reassess airway, breathing and circulation, verify the patient and product again, notify the appropriate team and blood bank, and follow the local reaction workup.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication. Identity. Product. Circuit. Patient. Early reassessment. Reaction recognition. Documentation and response. Every time.' },
    ],
  },
  {
    id: 'rep-art-line', title: 'Arterial line', subtitle: 'Rehearse the whole system: patient, artery, catheter, transducer, waveform and troubleshooting.',
    level: 3, domain: 'procedures', minutes: 14, concepts: ['arterial-line', 'waveform-damping'],
    disclaimer: 'Mental rehearsal only. Insertion requires supervised procedural training, sterile technique and local policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Start with the purpose', narration: 'You need beat-to-beat pressure and arterial sampling. Picture the patient positioned, monitoring visible, rescue equipment available and the entire pressure system prepared before puncture.' },
      { id: 'anatomy', phase: 'orientation', title: 'Find and prove the radial artery', narration: 'For a distal radial approach, orient to the volar radial wrist. Palpate the radial pulse and identify the nearby tendons and bony radial border so you know where you are before looking at the screen. With ultrasound, find the small round pulsatile artery and distinguish it from compressible veins and nearby soft-tissue or nerve structures. Sweep proximally and distally, then rotate into long axis so you understand the vessel course rather than aiming at a single dot. If the anatomy is ambiguous or the vessel course is poor, choose a better site before the needle enters.', visual: 'artery-ultrasound', pauseSeconds: 4, prompt: 'What tells you the structure is an artery, and what lies immediately around your intended path?' },
      { id: 'system', phase: 'equipment', title: 'The catheter is only half the procedure', narration: 'Pick up the flush bag, pressure tubing, transducer and monitor cable. Spike and prime the tubing, then flush every stopcock and connector until no visible air remains. Put the bag in the pressure sleeve and pressurize it to the manufacturer or unit target. Connect the transducer to the monitor, then trace the system end to end before it reaches the patient.', visual: 'transducer-system' },
      { id: 'level', phase: 'confirmation', title: 'Level and zero', narration: 'Place the transducer at the reference level used by your unit, commonly the phlebostatic axis for arterial pressure. Open the stopcock to air, select zero, wait for confirmation, then close air and reopen to the patient. If the bed or patient moves, re-level before trusting the number. Too low reads falsely high; too high reads falsely low.', prompt: 'Transducer too low: what happens to the displayed pressure?' },
      { id: 'wave', phase: 'confirmation', title: 'Interrogate the waveform', narration: 'Do not accept a number without its waveform. Look at upstroke, systolic peak, dicrotic notch, diastolic runoff and respiratory variation in context.', visual: 'arterial-waveform' },
      { id: 'square', phase: 'decision', title: 'Test the system', narration: 'Pull and release the fast-flush device while watching the waveform. A crisp square followed by a brief oscillation supports an appropriate dynamic response. Too much ringing suggests underdamping; a sluggish return suggests overdamping. Then physically inspect the line for air, clot, kinks, compliant tubing, loose connections, or catheter-wall contact before blaming the patient.', visual: 'square-wave-test' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Patient, artery, catheter, level, zero, waveform, dynamic response. The arterial line is a measurement system, not simply a line in an artery.' },
    ],
  },
  {
    id: 'rep-efast', title: 'eFAST mental sweep', subtitle: 'Probe position, image orientation, target spaces and the discipline of a repeatable exam.',
    level: 3, domain: 'procedures', minutes: 12, concepts: ['efast'],
    disclaimer: 'Mental rehearsal only. Diagnostic ultrasound requires supervised image-acquisition training and must be integrated with the clinical picture.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Set the question', narration: 'You are not doing ultrasound because a probe is available. State the question: is there blood where it should not be, pericardial fluid, or pleural evidence of pneumothorax or hemothorax?', visual: 'efast-map', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'You are not doing ultrasound because a probe is available. State the question: is there blood where it should not be, pericardial fluid, or pleural evidence of pneumothorax or hemothorax?', reviewed: false, src: 'voice/rep.rep-efast.arrival.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/f7233a4f-49e5-4bda-902e-5bf5957a9021.mp3' } },
      { id: 'orientation', phase: 'orientation', title: 'Anchor the probe and the screen', narration: 'Before you interpret anything, decide your probe-marker convention and prove it on the screen. Know which side is cephalad and which side is caudad or right versus left for that window. Put the probe on the patient, identify one unmistakable structure, then use it to orient everything else. If the image orientation in your head does not match the anatomy on the screen, stop and correct the probe before looking for pathology.', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Before you interpret anything, decide your probe-marker convention and prove it on the screen. Know which side is cephalad and which side is caudad or right versus left for that window. Put the probe on the patient, identify one unmistakable structure, then use it to orient everything else. If the image orientation in your head does not match the anatomy on the screen, stop and correct the probe before looking for pathology.', reviewed: false, src: 'voice/rep.rep-efast.orientation.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/777e23d1-53ae-4313-ac99-a27d8bab05c7.mp3' } },
      { id: 'ruq', phase: 'sequence', title: 'RUQ: build the window from landmarks', narration: 'Move to the right lateral lower chest and upper abdomen. A common starting point is the mid-axillary line around the eighth to eleventh intercostal spaces, with the probe oriented longitudinally according to your convention. First identify the liver, then the right kidney, then the bright diaphragm. Once those anchors are real, search the hepatorenal interface and inferior liver tip while sliding, fanning and sweeping through the window. Do not accept one frozen image as a negative examination.', visual: 'efast-ruq', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Move to the right lateral lower chest and upper abdomen. A common starting point is the mid-axillary line around the eighth to eleventh intercostal spaces, with the probe oriented longitudinally according to your convention. First identify the liver, then the right kidney, then the bright diaphragm. Once those anchors are real, search the hepatorenal interface and inferior liver tip while sliding, fanning and sweeping through the window. Do not accept one frozen image as a negative examination.', reviewed: false, src: 'voice/rep.rep-efast.ruq.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/6c33c741-910c-4417-8745-ea3c581bcc61.mp3' } },
      { id: 'luq', phase: 'sequence', title: 'LUQ: move posterior and prove the spleen', narration: 'For the left upper quadrant, move more posteriorly and usually more cephalad than on the right; a common starting point is the posterior axillary line around the sixth to ninth intercostal spaces. Identify spleen, left kidney and diaphragm before hunting for fluid. Keep the probe between the ribs, sweep through the splenorenal interface and the subdiaphragmatic region, and adjust your hand rather than twisting the image in your head to resemble a textbook picture.', visual: 'efast-luq', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'For the left upper quadrant, move more posteriorly and usually more cephalad than on the right; a common starting point is the posterior axillary line around the sixth to ninth intercostal spaces. Identify spleen, left kidney and diaphragm before hunting for fluid. Keep the probe between the ribs, sweep through the splenorenal interface and the subdiaphragmatic region, and adjust your hand rather than twisting the image in your head to resemble a textbook picture.', reviewed: false, src: 'voice/rep.rep-efast.luq.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/22bf7366-753b-4496-9381-cd36b3e4882d.mp3' } },
      { id: 'pelvis', phase: 'sequence', title: 'Pelvis: use the bladder as the anchor', narration: 'Move to the midline just cephalad to the pubic bone. Touch the probe to the pubic bone first if needed to see its shadow, then slide slightly cephalad and find the bladder. It should give you a dark fluid-filled acoustic window and a clear pelvic reference. Scan in both transverse and longitudinal planes according to your convention, then examine the dependent spaces around the bladder rather than staring only at its center. If you cannot confidently identify the bladder, re-orient before calling the pelvic window complete.', visual: 'efast-pelvis', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Move to the midline just cephalad to the pubic bone. Touch the probe to the pubic bone first if needed to see its shadow, then slide slightly cephalad and find the bladder. It should give you a dark fluid-filled acoustic window and a clear pelvic reference. Scan in both transverse and longitudinal planes according to your convention, then examine the dependent spaces around the bladder rather than staring only at its center. If you cannot confidently identify the bladder, re-orient before calling the pelvic window complete.', reviewed: false, src: 'voice/rep.rep-efast.pelvis.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/05ba04ca-bf2e-4e84-8b4a-16a26f0a3a70.mp3' } },
      { id: 'cardiac', phase: 'sequence', title: 'Pericardium: build the cardiac window before calling fluid', narration: 'Choose the cardiac window the patient gives you. In a subxiphoid approach, use the liver as an acoustic window and direct the image toward the heart; in another standard view, orient by recognizable chambers first. Identify myocardium and the pericardial boundary before deciding that an anechoic space is pericardial fluid. Epicardial fat, pleural fluid and artifact can mimic the target, so prove the anatomy before you call the finding.', visual: 'efast-cardiac', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Choose the cardiac window the patient gives you. In a subxiphoid approach, use the liver as an acoustic window and direct the image toward the heart; in another standard view, orient by recognizable chambers first. Identify myocardium and the pericardial boundary before deciding that an anechoic space is pericardial fluid. Epicardial fat, pleural fluid and artifact can mimic the target, so prove the anatomy before you call the finding.', reviewed: false, src: 'voice/rep.rep-efast.cardiac.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/f844002a-eceb-4aaa-8a5a-9b92872fa7e6.mp3' } },
      { id: 'lung', phase: 'sequence', title: 'Pleura: find the rib space, then the pleural line', narration: 'Move to the anterior chest and identify two rib shadows with the bright pleural line running between them. That rib-pleura relationship proves you are at the lung surface instead of interpreting superficial tissue artifact. Compare sides and zones. Watch the pleural line dynamically for sliding and use M-mode or additional signs when appropriate. If sliding is absent, do not turn one sign into a diagnosis; integrate the rest of the scan and the patient.', visual: 'efast-lung', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Move to the anterior chest and identify two rib shadows with the bright pleural line running between them. That rib-pleura relationship proves you are at the lung surface instead of interpreting superficial tissue artifact. Compare sides and zones. Watch the pleural line dynamically for sliding and use M-mode or additional signs when appropriate. If sliding is absent, do not turn one sign into a diagnosis; integrate the rest of the scan and the patient.', reviewed: false, src: 'voice/rep.rep-efast.lung.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/fc4ad59b-157f-4908-85c9-174fefa09630.mp3' } },
      { id: 'repeat', phase: 'debrief', title: 'A negative exam is time-stamped', narration: 'Trauma evolves. The mental anchor is orientation, systematic windows, sweeping rather than snapshotting, and repeat examination when physiology changes.', voice: { tier: 'premium-human', voice: 'Natural clinical narrator prototype', locale: 'en-US', transcript: 'Trauma evolves. The mental anchor is orientation, systematic windows, sweeping rather than snapshotting, and repeat examination when physiology changes.', reviewed: false, src: 'voice/rep.rep-efast.repeat.mp3', previewSrc: 'https://storage.googleapis.com/adm--audio-playback--7d--public/mcp-preview/3ba2180d-bd3a-4795-b579-681d341b2ea0.mp3' } },
    ],
  },
  {
    id: 'rep-chest-tube', title: 'Chest tube / pleural drain', subtitle: 'Anatomy, setup, safe sequence, system behavior and early failure recognition.',
    level: 3, domain: 'procedures', minutes: 15, concepts: ['chest-tube'],
    disclaimer: 'Mental rehearsal only. Tube thoracostomy requires supervised hands-on training, credentialing, sterile technique and local procedural policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Indication before incision', narration: 'Picture the patient and state what you are treating. Tension physiology, hemothorax and ongoing pleural air are related problems but they shape urgency, equipment and aftercare differently.' },
      { id: 'anatomy', phase: 'orientation', title: 'Find the safe triangle before you prep', narration: 'Expose the lateral chest and orient yourself before anything sterile begins. Trace the lateral border of pectoralis major anteriorly and the anterior border of latissimus dorsi posteriorly. The inferior boundary of the usual safe triangle is around the fifth intercostal-space level, with the apex below the axilla. Now palpate the ribs bracketing the interspace you intend to use. Remember that the main intercostal neurovascular bundle runs along the inferior border of the rib above, so your mental entry path stays just over the superior border of the rib below. If you cannot confidently identify the boundaries and rib relationship, stop and re-orient before proceeding.', visual: 'chest-wall-anatomy', pauseSeconds: 5, prompt: 'Can you name the safe-triangle boundaries and which rib border you are protecting?' },
      { id: 'setup', phase: 'equipment', title: 'Prepare the whole system', narration: 'Before you prep, lay out the tube, sterile instruments, suture, dressing, connector, drainage unit, and suction tubing if ordered. Prepare the water-seal or suction chamber exactly according to that device. Trace the entire connection path now, so once the tube is in the pleural space you have a ready system to connect to instead of searching for pieces.', visual: 'drain-system' },
      { id: 'sequence', phase: 'sequence', title: 'Controlled entry', narration: 'After sterile prep, drape, analgesia and local anesthesia, make the skin incision over the chosen site. Bluntly dissect to the chest wall, stay over the superior border of the rib below, and enter the pleural space under control. Open the tract and use a gloved finger to confirm the pleural space and feel for adhesions before the tube follows that path. If the anatomy or resistance does not fit, stop rather than force it.', danger: true },
      { id: 'connect', phase: 'confirmation', title: 'Connect and ask what changed', narration: 'Once the tube is positioned, connect it immediately to the prepared drainage system and secure the connection. Look for the expected return and chamber behavior for the problem you are treating, then secure the tube and dressing. Reassess breathing, oxygenation, blood pressure and work of breathing, and obtain the prescribed confirmation. If nothing improves, troubleshoot tube position, patency, the system and the diagnosis.', visual: 'drain-water-seal' },
      { id: 'failure', phase: 'complication', title: 'A drain can fail after it worked', narration: 'Kinked tubing, disconnection, migration, clot, dependent loops or a new air leak can turn a functioning drain into a problem. Trace from patient outward whenever physiology worsens.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication, anatomy, complete setup, controlled pleural entry, connection, patient response, system response, and continuous troubleshooting.' },
    ],
  },
  {
    id: 'rep-central-line', title: 'Ultrasound-guided IJ central line', subtitle: 'Scan, identify, track the tip, confirm the vessel, control the wire, then dilate.',
    level: 3, domain: 'procedures', minutes: 16, concepts: ['central-line', 'medication-safety'],
    disclaimer: 'Mental rehearsal only. Central venous access requires supervised procedural training, maximal sterile precautions, credentialing and local policy.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Know why you need the line', narration: 'State the indication and whether a safer or faster alternative can meet the immediate need. Prepare monitoring, sterile equipment and a plan for complications before beginning.' },
      { id: 'scan', phase: 'orientation', title: 'Map the neck before sterile entry', narration: 'Start with surface orientation: clavicle below, sternocleidomastoid over the lower neck, carotid pulse medial. Then put the linear probe on the neck and prove the anatomy rather than assuming it. Find the carotid artery: round, pulsatile and relatively noncompressible. Find the internal jugular vein: usually thinner-walled and compressible, but its position relative to the artery can vary. Sweep up and down the neck and rotate into another plane. Look for vessel overlap, thrombus, depth and the path your needle would have to travel. If you cannot clearly distinguish vein, artery and the structures deep to them, stop and remap before puncture.', visual: 'ijv-real', pauseSeconds: 5, prompt: 'What features tell you this is the IJ rather than the carotid, and is there overlap in your intended path?' },
      { id: 'tip', phase: 'sequence', title: 'The bright dot must be the tip', narration: 'Hold the probe in one hand and advance the needle only a few millimeters at a time. After every movement, move the probe or needle until the true tip—not the shaft—is seen again. Keep the target vein centered and watch the anterior wall tent, then the tip enter the lumen. If the tip disappears, your needle hand stops until you reacquire it.', prompt: 'What could you injure if you advance while the true tip is lost from view?' },
      { id: 'confirm', phase: 'confirmation', title: 'Confirm venous access before dilation', narration: 'Once you think you are venous, keep the needle still and prove it before dilation. Confirm the tip in the vein with ultrasound and use the pressure, transduction, blood-gas, or other confirmation method required by your environment. Dark blood alone is unreliable in shock or hypoxemia. If any cue disagrees, stop and reconcile it before the dilator enters the patient.', danger: true },
      { id: 'wire', phase: 'sequence', title: 'The wire is never an afterthought', narration: 'Feed the guidewire gently and never release the proximal end. If you meet resistance or trigger ectopy, stop rather than push. When feasible, use ultrasound to see the wire inside the intended vein in short and long axis before dilation. Keep one hand controlling the wire during every exchange, and physically account for the wire when the catheter is in.' },
      { id: 'comp', phase: 'complication', title: 'If something does not fit, stop', narration: 'Resistance, unexpected pressure, ectopy, abnormal ultrasound position or patient deterioration are information. Stop and reconcile the anatomy before progressing.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication, anatomy, sterile setup, tip visibility, vessel confirmation, wire control, confirmation before dilation, then post-procedure reassessment.' },
    ],
  },
  {
    id: 'rep-io', title: 'Intraosseous access', subtitle: 'Rapid access still requires landmark discipline, confirmation and repeated site reassessment.',
    level: 2, domain: 'procedures', minutes: 8, concepts: ['io-access', 'medication-safety', 'shock'],
    disclaimer: 'Mental rehearsal only. Use only approved sites/devices and the manufacturer instructions, service protocol and supervised skills training for your equipment.',
    beats: [
      { id: 'arrival', phase: 'arrival', title: 'Access is the goal, not the device', narration: 'The patient needs reliable vascular access now. Decide whether IO is appropriate rather than repeatedly delaying resuscitation for difficult peripheral attempts.' },
      { id: 'landmark', phase: 'orientation', title: 'Find the bony target before you touch the driver', narration: 'Choose an approved site for the device and patient in front of you, then identify it by touch before opening the driver. For a proximal tibial example, first find the tibial tuberosity, then identify the broad flat anteromedial surface about one to two centimeters inferior and medial to it rather than drifting toward the joint or posterior structures. In pediatric patients, deliberately account for the growth plate according to your training and device instructions. If you are using another approved site such as the proximal humerus, switch to that device-specific landmark sequence instead of carrying the tibial landmarks over. If the bony target is not unmistakable, stop and select or re-identify the site.', visual: 'io-landmark', pauseSeconds: 5, prompt: 'What landmark anchors the site you use, and what nearby structure or zone are you deliberately avoiding?' },
      { id: 'place', phase: 'sequence', title: 'Controlled placement', narration: 'Stabilize the limb. Choose the device-approved needle length so you have enough needle to reach bone at that site. Place the needle on the landmark at the angle required by the device and site, engage the cortex, and advance until the expected loss of resistance or endpoint occurs. Stop there—do not keep driving once you have entered the medullary space.' },
      { id: 'confirm', phase: 'confirmation', title: 'Prove it works', narration: 'Remove the driver or stylet as the device requires and attach the extension set. Check that the needle is stable, aspirate if appropriate, then flush according to protocol while watching the surrounding tissue. Easy flow without swelling supports correct placement; absence of aspirate alone does not prove failure. Secure the site before high-pressure use and keep reassessing it during infusion.' },
      { id: 'comp', phase: 'complication', title: 'Keep looking at the limb', narration: 'Swelling, leaking, worsening pain, resistance or neurovascular change can signal extravasation or another complication. Reassess after use, not only at insertion.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Decision, landmark, device-specific placement, confirmation, securement and repeated site checks.' },
    ],
  },
  {
    id: 'rep-vent-emergency', title: 'Sudden ventilator deterioration', subtitle: 'Patient first, then tube, circuit, pressure pattern and physiology.',
    level: 3, domain: 'procedures', minutes: 12, concepts: ['vent-troubleshooting', 'ppv-hemodynamics', 'dead-space'],
    disclaimer: 'Mental rehearsal only. Acute airway/ventilator emergencies require local protocols, immediate bedside assessment and escalation when needed.',
    beats: [
      { id: 'alarm', phase: 'arrival', title: 'The alarm is a symptom', narration: 'The patient suddenly desaturates and the ventilator is alarming. Look at the patient before the screen: chest movement, color, waveform capnography, hemodynamics and level of distress.', visual: 'vent-check' },
      { id: 'oxygen', phase: 'decision', title: 'Can you trust the ventilator and circuit?', narration: 'If oxygenation or ventilation is immediately threatened and the device cannot be trusted, transition to a reliable rescue method while troubleshooting according to your environment.' },
      { id: 'trace', phase: 'sequence', title: 'Trace the system', narration: 'Mentally move from patient to tube to connectors to circuit to machine. Disconnection, obstruction, displacement, pneumothorax and breath stacking leave different clues.', visual: 'vent-check' },
      { id: 'pressure', phase: 'decision', title: 'Use peak and plateau as physiology', narration: 'High peak with a relatively preserved plateau points you toward resistance. High peak and high plateau point you toward compliance or pressure surrounding the lung.', prompt: 'What bedside problems belong in each category?' },
      { id: 'hemo', phase: 'complication', title: 'The circulation may be the first organ failing', narration: 'Auto-PEEP, tension physiology and excessive intrathoracic pressure can present as hypotension before oxygen saturation collapses. The ventilator and circulation are one system.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Patient first. Rescue ventilation if needed. Trace the airway and circuit. Separate resistance from compliance. Look for pressure-related circulatory failure. Reassess after every intervention.' },
    ],
  },
  {
    id: 'rep-evd', title: 'Move a patient with an EVD', subtitle: 'Clamp, move, re-level, verify, reopen according to the ordered drainage strategy.',
    level: 3, domain: 'procedures', minutes: 8, concepts: ['evd', 'icp-cpp'],
    disclaimer: 'Mental rehearsal only. EVD management must follow the neurosurgical order, device instructions and local neurocritical-care policy.',
    beats: [
      { id: 'before', phase: 'arrival', title: 'Read the order before the room moves', narration: 'Know the ordered reference level, drainage strategy and whether the system is currently open or clamped. A drainage device without its order is an unsafe abstraction.' },
      { id: 'level', phase: 'orientation', title: 'Find the patient reference before you touch the chamber', narration: 'Identify the tragus or external auditory meatus on the patient—the bedside external reference commonly used to approximate the level of the foramen of Monro when the head is positioned appropriately. Bring the leveling device or laser to that patient reference, then look from the patient to the drain scale. The chamber height is meaningful only relative to that reference. If the head or bed position changes, assume the old level is no longer valid until you re-level it.', visual: 'evd-level', pauseSeconds: 4, prompt: 'What patient landmark are you leveling to, and what intracranial reference is it approximating?' },
      { id: 'clamp', phase: 'sequence', title: 'Secure the system for movement', narration: 'Before changing bed height or patient position, manage the drain exactly as ordered so a sudden vertical shift cannot unintentionally over-drain or stop drainage.', danger: true },
      { id: 'move', phase: 'sequence', title: 'After the move, rebuild the reference from the patient outward', narration: 'Once the patient and bed have moved, ignore the old chamber position. Go back to the patient. Find the tragus or external auditory meatus again at the new head position. Re-level the device to that reference, then verify the ordered drain height before returning the EVD to its prescribed open or clamped state. Patient first, reference second, chamber third.', visual: 'evd-level' },
      { id: 'verify', phase: 'confirmation', title: 'Confirm patient + system', narration: 'Reassess ICP waveform if monitored, drainage, neurologic state, tubing and clamps. A number that changed after repositioning may reflect the measurement system before it reflects the brain.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Order, clamp for movement as required, move, re-level to the patient, verify, then return to the prescribed drainage state.' },
    ],
  },
  {
    id: 'rep-mtp', title: 'Massive transfusion mental run', subtitle: 'Run hemorrhagic resuscitation as a coordinated system, not a stack of blood bags.',
    level: 4, domain: 'procedures', minutes: 14, concepts: ['massive-transfusion', 'transfusion', 'shock', 'oxygen-delivery'],
    disclaimer: 'Mental rehearsal only. Product ratios, activation criteria, medication adjuncts and laboratory targets vary by institution; follow the active MTP, blood-bank process and medical direction.',
    beats: [
      { id: 'activate', phase: 'arrival', title: 'Recognize the system problem', narration: 'This is not ordinary transfusion. The patient is bleeding faster than routine workflow can keep up. Activate the local hemorrhage system early enough that blood bank, access, warming and source control can move together.' },
      { id: 'roles', phase: 'equipment', title: 'Build the room', narration: 'Picture designated access, rapid infuser or approved delivery setup, warmer, monitoring, blood verification workflow, calcium and laboratory plan according to protocol, and someone explicitly tracking products and time.' },
      { id: 'source', phase: 'decision', title: 'Blood does not stop bleeding', narration: 'Resuscitation buys time for source control. Continually ask where the blood is going and what definitive action ends that loss.' },
      { id: 'phys', phase: 'complication', title: 'Watch what resuscitation itself changes', narration: 'Temperature, ionized calcium, fibrinogen, platelet function, acid-base state and dilution can deteriorate as the resuscitation grows. Anticipate them instead of discovering them late.', danger: true },
      { id: 'response', phase: 'confirmation', title: 'Follow physiology, not only pressure', narration: 'Reassess mental status, pulse quality, perfusion, shock index or hemodynamics, lactate trajectory when appropriate, bleeding rate and the response to source control.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Activate early, verify products, warm everything, maintain access and monitoring, anticipate calcium/coagulation/temperature problems, and never lose sight of source control.' },
    ],
  }
,
  {
    id: 'rep-us-piv', title: 'Ultrasound-guided peripheral IV', subtitle: 'Choose the vessel, track the tip, thread enough catheter and prove the line works.',
    level: 2, domain: 'procedures', minutes: 10, concepts: ['ultrasound-piv'],
    disclaimer: 'Mental rehearsal only. Ultrasound-guided vascular access requires supervised hands-on training, aseptic technique and local device/policy guidance.',
    beats: [
      { id: 'scan', phase: 'orientation', title: 'Map the vessel and everything around it', narration: 'Before touching a needle, scan the target region in short and long axis. Find a vein by its thin wall and compressibility, then deliberately look for nearby arteries, nerves, bone and other structures in the planned path. Follow the vein proximally and distally so you know its depth, diameter, direction and whether it branches or dives. A good target is not just a dark circle—it is a vessel with a usable course and enough safe catheter length. If you cannot account for the neighboring anatomy, keep scanning or choose another target.', visual: 'piv-map', pauseSeconds: 4, prompt: 'Can you identify the target vein, the nearest artery or nerve, and the vessel course before the needle enters?' },
      { id: 'setup', phase: 'equipment', title: 'Match catheter to depth', narration: 'After you map the vein, choose a catheter long enough for that depth and course. Prep the skin and probe, put the ultrasound screen in line with your needle path, and have the extension and flush ready before puncture. Recompress the target once more after positioning, because probe pressure and limb position can change the anatomy you mapped.' },
      { id: 'tip', phase: 'sequence', title: 'The tip is the procedure', narration: 'Enter the skin under the probe. Advance the needle a few millimeters, then slide or rock the probe until the true tip reappears. Repeat the sequence: find the tip first, then advance. Do not chase a bright shaft. Watch the tip indent the anterior vein wall and enter the lumen; if you cannot see the tip, your needle hand stops.', visual: 'piv-tip', prompt: 'What visual mistake makes a needle look safer than it really is?' },
      { id: 'thread', phase: 'sequence', title: 'Advance into the vessel before threading', narration: 'Once the needle tip is convincingly intraluminal, advance the needle-catheter unit a little farther under visualization so the catheter tip also crosses the vessel wall. Hold the needle steady and thread the catheter without force. If it will not thread, stop pushing and re-image where the tip and catheter actually are.' },
      { id: 'confirm', phase: 'confirmation', title: 'Prove the line works', narration: 'Connect the extension, aspirate if expected, and flush while watching both the skin and the ultrasound image. You should see flow stay intravascular without soft-tissue expansion. Secure the catheter, then check it again after the dressing is on, because taping can pull a short deep catheter partly back out.', visual: 'piv-confirm' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Map, choose, track the true tip, advance enough catheter, then confirm function and tissue integrity.' },
    ],
  },
  {
    id: 'rep-rsi', title: 'RSI setup and physiologic preparation', subtitle: 'Rehearse the room, the patient, the hemodynamics and the backup plan before induction.',
    level: 4, domain: 'procedures', minutes: 15, concepts: ['airway-rsi','ppv-hemodynamics','sedation-analgesia','rv-failure'],
    disclaimer: 'Mental rehearsal only. Airway management, RSI medications and rescue plans must follow credentialing, local protocols, medical direction and patient-specific clinical judgment.',
    beats: [
      { id: 'why', phase: 'arrival', title: 'State why the airway is needed', narration: 'Before preparing drugs, define the problem you are solving: oxygenation, ventilation, airway protection, work of breathing or clinical trajectory.', visual: 'airway-overview' },
      { id: 'phys', phase: 'decision', title: 'Identify the physiologically difficult airway', narration: 'Ask what induction and positive pressure will do to preload, afterload, vascular tone and the right ventricle. Severe shock, RV failure, metabolic acidosis and hypoxemia change the risk before laryngoscopy begins.', danger: true },
      { id: 'oxygen', phase: 'equipment', title: 'Build the oxygenation plan', narration: 'Position the patient for the airway and physiology in front of you. Put suction within reach and turn it on. Apply the primary preoxygenation device with a deliberate seal, and add apneic oxygenation when appropriate to your protocol. Watch the oxygenation response and end-tidal oxygen if available. If you cannot achieve an acceptable reserve, optimize or move to the rescue oxygenation plan before paralysis.', visual: 'airway-preoxygenation' },
      { id: 'room', phase: 'equipment', title: 'Lay out Plan A through rescue', narration: 'Lay out Plan A in reach: the chosen laryngoscope powered on, blade, tube with cuff checked, stylet or bougie, syringe, suction, and waveform capnography. Beside it, place bag-mask ventilation with the needed adjuncts, the backup supraglottic airway, and the emergency front-of-neck kit. Test the equipment now and make sure the person assigned to each rescue step can physically reach it.' },
      { id: 'meds', phase: 'decision', title: 'Choose drugs for the physiology', narration: 'Pick up each medication syringe and read the drug and concentration before it joins the airway setup. Label every syringe. Arrange induction, paralytic, flush, post-intubation analgesia and sedation, and any protocol-directed hemodynamic support in the order you expect to use them. Confirm the vascular access works and perform the required medication check before the first drug leaves your hand.' },
      { id: 'commit', phase: 'sequence', title: 'Induction is a point of no return', narration: 'Do one final sweep before the first drug: monitor on, access working, preoxygenation still running, suction on, bag-mask and rescue devices ready, capnography open, medications labeled, and the post-intubation support plan ready. The operator states Plan A, the assistant states the next rescue step, and only then does the protocol-directed induction sequence begin while someone watches the physiology.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Indication, physiology, oxygenation, equipment, rescue, medication strategy, role clarity, then induction. The airway starts before the laryngoscope.' },
    ],
  },
  {
    id: 'rep-post-intubation', title: 'The first five minutes after intubation', subtitle: 'Confirm the tube, stabilize physiology, set the ventilator, provide sedation and reassess the diagnosis.',
    level: 3, domain: 'procedures', minutes: 12, concepts: ['post-intubation','vent-troubleshooting','sedation-analgesia','ppv-hemodynamics'],
    disclaimer: 'Mental rehearsal only. Post-intubation management must follow local protocols, ventilator capabilities, patient physiology and medical direction.',
    beats: [
      { id: 'confirm', phase: 'confirmation', title: 'Confirm the airway', narration: 'Inflate the cuff according to your practice, connect the tube to the bag or ventilator, and attach waveform capnography immediately. Look for a sustained exhaled carbon-dioxide waveform over repeated breaths, note the tube depth at the teeth or lip, check bilateral chest movement and breath sounds, and use ultrasound or imaging when indicated. Then secure the tube. If capnography is absent or inconsistent, stop and investigate before assuming the airway is correct.', visual: 'post-tube' },
      { id: 'pressure', phase: 'decision', title: 'The blood pressure falls', narration: 'If the pressure falls, put your eyes on the patient and monitor before changing a drip. Check rhythm and capnography, trace the tube and circuit, compare chest movement, and inspect airway pressures and expiratory flow. Think induction-related vasodilation, lost venous return, increased right-ventricular afterload, auto-PEEP, tension physiology, displacement, and the underlying shock. Treat the mechanism you can support, not just the number.', danger: true, prompt: 'Which mechanisms became possible only after induction and positive pressure?' },
      { id: 'vent', phase: 'equipment', title: 'Set the ventilator from the disease', narration: 'At the ventilator, enter a starting tidal volume from predicted body weight rather than actual body weight. Choose respiratory rate and expiratory time for the acid-base and obstructive physiology, then set PEEP and oxygen for the oxygenation goal and set alarms. Now read back the delivered breath: exhaled tidal volume, peak and plateau pressure when available, expiratory flow returning toward baseline, saturation and capnography. Adjust from what the patient shows you.', visual: 'vent-check' },
      { id: 'sed', phase: 'sequence', title: 'Analgesia and sedation are now mandatory work', narration: 'Confirm the line you will use actually flushes and flows. Pick up the analgesia and sedation you intend to use, verify the labels and concentrations, connect them to the correct line, and start the protocol-directed plan with an explicit sedation target. If the patient is paralyzed, movement cannot tell you whether they are comfortable or aware; analgesia and sedation must be treated as active work.', visual: 'sedation-lines' },
      { id: 'recheck', phase: 'confirmation', title: 'Reassess everything you just changed', narration: 'Run the bedside loop again from the patient outward: tube depth and securement, capnography waveform, oxygenation, blood pressure and rhythm, bilateral chest movement, ventilator pressures and volumes, expiratory flow, synchrony, and the response to your interventions. If a trend is wrong, trace patient to tube to circuit to ventilator before making random setting changes. Intubation created a new physiologic state; reassess the diagnosis inside that new state.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Confirm tube, stabilize pressure, set the ventilator, sedate and analgesize, then reassess the patient as a new physiologic state.' },
    ],
  },
  {
    id: 'rep-pac', title: 'PA catheter waveform run', subtitle: 'Mentally travel RA → RV → PA → wedge and know what each waveform means before you use the numbers.',
    level: 5, domain: 'procedures', minutes: 16, concepts: ['pa-catheter','rv-failure','oxygen-extraction'],
    disclaimer: 'Mental rehearsal only. Pulmonary artery catheter insertion and interpretation require supervised procedural competency and local critical-care practice standards.',
    beats: [
      { id: 'zero', phase: 'equipment', title: 'The measurement system first', narration: 'At the bedside, trace the pressure system before the catheter moves: flush solution and pressure source, tubing, transducer, cable and monitor. Clear visible air, pressurize the flush system as required, level the transducer to the reference used by your unit, open it to atmosphere and zero, then restore it to the patient. Verify the balloon syringe and inflation volume against the catheter and local procedure, and keep the balloon deflated except during the intended maneuver. A bad measurement system can create a very convincing false waveform.', visual: 'transducer-system' },
      { id: 'ra', phase: 'sequence', title: 'Right atrium', narration: 'Start with the distal port displaying a plausible right-atrial waveform before advancing. Keep the pressure trace visible continuously. Recognize the low-pressure atrial pattern and its a and v components in context rather than using insertion depth alone. If the waveform does not fit the chamber you think you are in, stop and reconcile the system and catheter position before moving farther.', visual: 'pac-ra' },
      { id: 'rv', phase: 'sequence', title: 'Right ventricle', narration: 'As the tip enters the right ventricle, watch the waveform change in real time: systolic pressure rises while diastolic pressure falls toward zero. Keep the monitor and rhythm in view because ventricular ectopy can occur during passage. If ectopy becomes persistent or the pressure pattern is unexpected, stop advancement and follow the local response rather than blindly pushing forward.', visual: 'pac-rv' },
      { id: 'pa', phase: 'sequence', title: 'Pulmonary artery', narration: 'When the catheter enters the pulmonary artery, look for the diastolic pressure to step up and for a dicrotic notch to appear while systolic pressure remains in the pulmonary-artery range. Pause there and make sure the tracing is stable and physiologically plausible before attempting any occlusion measurement. The waveform—not the centimeters inserted—tells you which chamber or vessel is being sampled.', visual: 'pac-pa' },
      { id: 'wedge', phase: 'confirmation', title: 'Wedge is a measurement maneuver, not a destination', narration: 'For a wedge measurement, use only the manufacturer- and protocol-directed balloon volume while watching the waveform continuously. Stop inflation as soon as the pulmonary-artery trace transitions to a plausible wedge pattern; never force the balloon or leave it inflated after the measurement. Deflate promptly and confirm the pulmonary-artery waveform returns. If obtaining the tracing requires unexpected volume or the waveform does not make physiologic sense, abandon the number and troubleshoot rather than calling it a wedge.', visual: 'pac-wedge' },
      { id: 'integrate', phase: 'decision', title: 'Pressures do not interpret themselves', narration: 'Combine RA, PA, wedge, cardiac output and venous saturation with the patient and trend. Use the catheter to test a model, not to collect targets.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Level and zero, recognize each chamber, validate wedge, then integrate pressures, flow and oxygen extraction as one physiologic story.' },
    ],
  },
  {
    id: 'rep-crrt', title: 'CRRT circuit walk-through', subtitle: 'Follow blood, dialysate, replacement fluid and effluent until every pressure and alarm has a physical meaning.',
    level: 4, domain: 'procedures', minutes: 15, concepts: ['crrt','antimicrobial-pkpd'],
    disclaimer: 'Mental rehearsal only. CRRT setup and troubleshooting are device- and institution-specific and require trained bedside competency.',
    beats: [
      { id: 'purpose', phase: 'arrival', title: 'State the prescription goal', narration: 'Before looking at the machine, decide what you are trying to control: solute, acid-base, potassium, volume, or several at once.', visual: 'crrt-circuit' },
      { id: 'blood', phase: 'sequence', title: 'Follow the blood path', narration: 'Stand at the CRRT machine and trace the blood path with your eyes from the patient outward: vascular access to the access limb, through the blood pump, into the filter, then through the return limb back to the patient. Identify which pressure sensor belongs to each part of that path. Before interpreting an alarm, make sure you can point to the segment of tubing or catheter that the pressure represents.', visual: 'crrt-circuit' },
      { id: 'transport', phase: 'orientation', title: 'Diffusion versus convection', narration: 'Now trace the non-blood fluids. Find where dialysate enters the filter side, where replacement solution enters if the prescription uses it—pre-filter, post-filter, or both—and where effluent leaves to its bag or scale. Say the mechanism as you point: dialysate supports diffusion; ultrafiltration and replacement configuration shape convection and hemoconcentration. The mode name should be explainable by the physical fluid paths in front of you.' },
      { id: 'effluent', phase: 'decision', title: 'Effluent is not the same as patient fluid removal', narration: 'On the prescription and machine, find the therapy or effluent dose and the separate net patient-fluid-removal target. Then compare those settings with the actual effluent collection and the bedside intake-and-output record. Total effluent describes therapy leaving the circuit; net ultrafiltration is the fluid-balance intervention on the patient. Do not use one number as though it were the other.', prompt: 'Which number changes the patient’s intravascular volume directly?' },
      { id: 'alarm', phase: 'complication', title: 'An alarm is a circuit clue', narration: 'When an alarm sounds, read the named pressure and its trend before touching the silence button again. An increasingly negative access pressure sends you back toward drainage, catheter position, kinks and patient factors. An increasingly positive return pressure sends you down the return limb for obstruction or catheter problems. Rising filter or transmembrane pressure makes you inspect the filter and circuit for increasing resistance, clotting or hemoconcentration. Trace the physical path first; change therapy settings only when the cause and device-specific response are clear.', danger: true },
      { id: 'drugs', phase: 'confirmation', title: 'The circuit changes drug clearance', narration: 'As renal function and extracorporeal clearance change, antimicrobial and other drug exposure can change too. Delivered therapy matters more than the label on the prescription.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Goal, blood path, transport mechanism, effluent, net fluid removal, pressure pattern, and delivered dose.' },
    ],
  },
  {
    id: 'rep-ecmo', title: 'ECMO circuit walk-through', subtitle: 'Follow the blood through drainage, pump, membrane lung and return—then connect the circuit to native heart and lung function.',
    level: 5, domain: 'procedures', minutes: 16, concepts: ['ecmo','oxygen-delivery','rv-failure'],
    disclaimer: 'Mental rehearsal only. ECMO management requires specialized team training, program protocols and real-time specialist oversight.',
    beats: [
      { id: 'type', phase: 'arrival', title: 'Name what the circuit is supporting', narration: 'Before touching a control, identify the circuit configuration on the patient. Trace where blood is drained and where it is returned. In VV support, both ends are in the venous circulation and the primary job is gas exchange. In VA support, blood returns to the arterial system and the circuit also supports circulation. The cannulation map tells you what the circuit can and cannot fix.', visual: 'ecmo-circuit' },
      { id: 'drain', phase: 'sequence', title: 'Drainage starts the story', narration: 'Put your eyes on the drainage limb from the patient to the pump. Watch the tubing, displayed flow and the drainage-side pressure or access information available on that system. If the line chatters or collapses, flow falls, or drainage becomes increasingly difficult, think about cannula position, venous return, intravascular volume and surrounding thoracic or abdominal pressure before simply turning the pump faster.' },
      { id: 'pump', phase: 'sequence', title: 'The pump creates flow', narration: 'Now point to the pump. Read pump speed and measured blood flow as two different variables. Increase in speed does not guarantee useful flow if drainage is inadequate, and circuit afterload or cannula resistance can also limit flow. Trend the values together and look back at the patient and both limbs of the circuit before deciding that a pump number equals effective support.', visual: 'ecmo-circuit' },
      { id: 'lung', phase: 'sequence', title: 'The membrane lung handles gas exchange', narration: 'Follow blood from the pump into the membrane lung, then find the sweep-gas source, blender or flow control, and gas connection entering the oxygenator. Blood flow is a major determinant of how much oxygenated blood the circuit can deliver; sweep gas is a major lever for carbon-dioxide removal. If gas flow is disconnected or the membrane is failing, an impressive pump speed cannot substitute for a functioning gas-exchange path.' },
      { id: 'return', phase: 'decision', title: 'Where the blood returns changes the patient', narration: 'Follow the oxygenated blood out of the membrane lung and along the return limb all the way back to the patient. In VA support, arterial return changes systemic pressure and left-ventricular loading, so compare circuit flow with native pulsatility and the patient’s perfusion. In VV support, make sure returned oxygenated blood is reaching the patient rather than being immediately redrained as recirculation. The return site changes what the same displayed flow means.', visual: 'ecmo-return' },
      { id: 'mismatch', phase: 'complication', title: 'Circuit numbers can look fine while the patient is not', narration: 'If the circuit numbers look acceptable but the patient does not, stop reading the console in isolation. Compare patient saturation and arterial blood gas with the circuit’s pre- and post-membrane information available to your program, examine cannula position and drainage/return behavior, and reassess native heart and lung function. In VA support, actively consider differential oxygenation based on the cannulation configuration. In VV support, consider recirculation. A normal-looking RPM or flow display never overrules the patient.', danger: true },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Support goal, drainage, pump, membrane lung, return, then native circulation. Follow the blood every time.' },
    ],
  },
  {
    id: 'rep-iabp', title: 'IABP timing rehearsal', subtitle: 'Use the arterial waveform to time inflation and deflation and recognize when the balloon is fighting the ventricle.',
    level: 4, domain: 'procedures', minutes: 12, concepts: ['iabp','arterial-line','cardiogenic-shock'],
    disclaimer: 'Mental rehearsal only. IABP operation and timing changes require trained device competency and local critical-care/cardiology practice.',
    beats: [
      { id: 'why', phase: 'arrival', title: 'Know what the balloon is trying to do', narration: 'Start at the IABP console and identify the trigger source being used, the assist ratio, and the arterial-pressure waveform you are timing against. Find an unassisted beat and the dicrotic notch so you know where aortic-valve closure is represented. The goal is mechanical: inflate in diastole to augment diastolic pressure, then have the balloon deflated before the next ventricular ejection.', visual: 'iabp-wave' },
      { id: 'inflate', phase: 'sequence', title: 'Inflate at the start of diastole', narration: 'Put your eye on the dicrotic notch of a clean arterial trace. The inflation marker should begin at or just after aortic-valve closure rather than during active systolic ejection. After the assisted beat, compare the augmented diastolic peak with the surrounding unassisted diastolic pressure. If timing changes, reassess several beats rather than judging a single noisy waveform.', visual: 'iabp-wave' },
      { id: 'deflate', phase: 'sequence', title: 'Deflate before systole', narration: 'Now look at the end of diastole. The balloon should be deflated before the next systolic upstroke so the ventricle ejects against less resistance. Compare assisted end-diastolic pressure and the assisted systolic upstroke with an unassisted beat. If the balloon is still inflated as systole begins, timing is working against the left ventricle instead of helping it.' },
      { id: 'early', phase: 'complication', title: 'Early inflation', narration: 'For early inflation, look for the inflation marker and pressure rise occurring before the dicrotic notch while the ventricle is still ejecting. That means the balloon is opposing late systolic flow and can increase left-ventricular work. Move your attention back to the notch and correct timing according to the device and local competency process rather than chasing the augmented peak alone.', danger: true, visual: 'iabp-errors' },
      { id: 'late', phase: 'complication', title: 'Late deflation', narration: 'For late deflation, watch the balloon remain inflated into the next systolic upstroke. Assisted end-diastolic pressure fails to fall appropriately and the ventricle meets extra resistance at ejection. The fix is not more augmentation; it is restoring deflation before systole using the device-specific timing control and then comparing assisted with unassisted beats again.', danger: true, visual: 'iabp-errors' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Dicrotic notch, diastolic augmentation, deflate before systole, then compare assisted and unassisted beats for the intended effect.' },
    ],
  },
  {
    id: 'rep-sedation', title: 'Post-intubation analgesia and sedation setup', subtitle: 'Treat pain, choose a sedation target, anticipate hemodynamics and keep the neurologic plan visible.',
    level: 3, domain: 'procedures', minutes: 10, concepts: ['sedation-analgesia','post-intubation'],
    disclaimer: 'Mental rehearsal only. Medication selection and dosing must follow local protocols, patient-specific factors and medical direction.',
    beats: [
      { id: 'pain', phase: 'arrival', title: 'Pain and sedation are not the same problem', narration: 'Start by asking whether the patient is in pain, anxious, delirious, dyssynchronous or inadequately ventilated. A deeper sedative is not the universal answer.', visual: 'sedation-lines' },
      { id: 'goal', phase: 'decision', title: 'Choose the target', narration: 'Set an explicit sedation target based on the clinical need—comfort and synchrony, neurologic assessment, paralysis, refractory hypoxemia or another indication.' },
      { id: 'hemo', phase: 'decision', title: 'Predict the circulatory cost', narration: 'Many analgesic and sedative strategies alter vascular tone, respiratory drive or myocardial performance. Decide what deterioration you are prepared to recognize and treat.' },
      { id: 'paralysis', phase: 'complication', title: 'Paralysis hides distress', narration: 'Neuromuscular blockade removes movement, not awareness or pain. Analgesia and sedation must already be established and maintained when paralysis is used.', danger: true },
      { id: 'reassess', phase: 'confirmation', title: 'Reassess the target, not just the drip', narration: 'Trend comfort, synchrony, hemodynamics, delirium risk and neurologic needs. Sedation should be titrated toward an explicit clinical goal.' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Pain, sedation target, physiologic cost, paralysis awareness, then repeated reassessment.' },
    ],
  },
  {
    id: 'rep-status', title: 'Status epilepticus sequence', subtitle: 'Rehearse time, airway support, medication phases and the moment convulsions stop but seizure may continue.',
    level: 4, domain: 'procedures', minutes: 12, concepts: ['status-epilepticus','airway-rsi','sedation-analgesia'],
    disclaimer: 'Mental rehearsal only. Status epilepticus treatment must follow current local protocol, patient factors, medical direction and access to EEG/critical-care resources.',
    beats: [
      { id: 'clock', phase: 'arrival', title: 'Start the clock mentally', narration: 'Persistent seizure activity is time-dependent. Stabilization and treatment move together; do not wait for every diagnostic answer before treating ongoing convulsive status.', visual: 'seizure-timeline' },
      { id: 'support', phase: 'equipment', title: 'Protect oxygenation and perfusion', narration: 'Position, suction, oxygenation, glucose assessment, monitoring and vascular access happen while the seizure treatment sequence begins.' },
      { id: 'first', phase: 'sequence', title: 'First-line therapy is time-sensitive', narration: 'Deliver the protocol-defined first-line therapy promptly and adequately rather than giving repeated ineffective fragments.' },
      { id: 'second', phase: 'sequence', title: 'Move to the next phase if seizure continues', narration: 'Persistent seizure after adequate first-line treatment means the treatment phase has changed. Prepare second-line therapy and escalation rather than restarting the same loop.' },
      { id: 'airway', phase: 'decision', title: 'Airway decisions are physiology decisions', narration: 'Refractory seizure, medication effect, hypoventilation or loss of airway protection may require airway control—but the post-intubation sedation plan must also treat ongoing seizure risk.', danger: true },
      { id: 'silent', phase: 'confirmation', title: 'No convulsions does not guarantee no seizure', narration: 'Persistent coma or unexplained mental status after convulsions stop should raise concern for nonconvulsive status and the need for EEG when available.', visual: 'seizure-eeg' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Time, stabilize, adequate first-line therapy, change phases when it fails, secure physiology when needed, and remember that seizure activity can become invisible.' },
    ],
  }
,
  {
    id: 'rep-pocus-shock', title: 'Critical-care POCUS shock survey', subtitle: 'Heart, lung, venous and abdominal windows organized around one hemodynamic question.',
    level: 4, domain: 'procedures', minutes: 14, concepts: ['critical-care-echo','lung-ultrasound','efast','shock'],
    disclaimer: 'Mental rehearsal only. Point-of-care ultrasound requires supervised image-acquisition and interpretation training; focused findings must be integrated with the patient and escalated to comprehensive imaging when needed.',
    beats: [
      { id: 'question', phase: 'arrival', title: 'Ask the question before touching the probe', narration: 'The patient is in shock. Do not begin by collecting pretty views. State what you need to know: pump failure, right-heart pressure load, pericardial constraint, lung congestion, pneumothorax, free fluid, or another cause of instability.', visual: 'pocus-map' },
      { id: 'heart', phase: 'orientation', title: 'Interrogate the heart from more than one view', narration: 'Choose a cardiac window and prove the orientation using your local probe-marker convention. For subxiphoid imaging, start just below the xiphoid and use the liver as the acoustic window toward the heart. For parasternal views, move to the left sternal border; for apical views, move toward the point of maximal impulse and avoid foreshortening. Identify chambers before judging size or function, and do not call tamponade or right-heart strain from one uncertain view.', visual: 'pocus-heart', prompt: 'Which finding would make you change your fluid or positive-pressure strategy immediately?' },
      { id: 'lung', phase: 'sequence', title: 'Map the lungs bilaterally', narration: 'Place the probe between two ribs and first identify the two rib shadows with the bright pleural line between them. Once the pleural surface is proven, scan matched anterior, lateral and posterior zones on both sides. At each zone watch for sliding, A-lines, B-lines, consolidation and pleural fluid, then compare the distribution. If you cannot confidently identify the pleural line, stop and re-orient before interpreting pneumothorax.', visual: 'pocus-lung' },
      { id: 'venous', phase: 'decision', title: 'Venous findings are context, not a volume-status oracle', narration: 'For the IVC, start subxiphoid with the liver as your window and identify the vessel entering the right atrium. Distinguish it from the aorta by its course, wall and pulsatility, then sweep along the IVC and watch what happens with respiration. Add other venous Doppler views only when they answer your question and are within your training. Do not turn one IVC diameter or collapse pattern into an automatic command to give or withhold fluid.', visual: 'pocus-venous' },
      { id: 'abdomen', phase: 'sequence', title: 'Look for the abdominal problem that changes the resuscitation', narration: 'When bleeding or aortic catastrophe is plausible, move through a repeatable abdominal sequence. In the right upper quadrant, identify liver, kidney and diaphragm before searching their dependent spaces; on the left, prove spleen, kidney and diaphragm. In the pelvis, use the bladder as the anchor. For the aorta, identify it in the epigastrium and follow it distally rather than measuring a single dark circle. A negative FAST does not exclude retroperitoneal bleeding and can become positive later.', visual: 'pocus-abdomen' },
      { id: 'integrate', phase: 'decision', title: 'Build one shock model', narration: 'Now stop scanning. Integrate the heart, lungs, venous system, abdomen, blood pressure, capnography and clinical examination into one working physiologic model. Make a prediction about what your next intervention should change.', visual: 'pocus-integrate', prompt: 'What finding would falsify your current shock model?' },
      { id: 'debrief', phase: 'debrief', title: 'Mental anchor', narration: 'Question, cardiac views, lung map, venous context, abdominal question, then integration. POCUS is not a collection of images. It is bedside evidence used to test a physiologic hypothesis.' },
    ],
  }
];

export const EPISODE_BY_ID = Object.fromEntries(EPISODES.map((e) => [e.id, e]));
export const REP_BY_ID = Object.fromEntries(MENTAL_REPS.map((r) => [r.id, r]));
