import type { AudioEpisode, CriticalCareDomain, MasteryLevel } from './types';

type ChapterSeed = [string, string, number, string[], string?];
type EpisodeSeed = {
  id: string; title: string; subtitle: string; format: AudioEpisode['format'];
  level: MasteryLevel; minutes: number; domain: CriticalCareDomain; concepts: string[];
  chapters: ChapterSeed[]; outcomes: string[];
};

const episode = (x: EpisodeSeed): AudioEpisode => ({
  ...x,
  status: 'scripted',
  chapters: x.chapters.map(([id,title,seconds,conceptIds,prompt]) => ({ id,title,seconds,conceptIds,prompt })),
});

/**
 * Expertise-audio expansion.
 *
 * These are canonical curriculum structures, not AI-on-demand lectures.
 * Each episode is deterministic and mapped to the mastery graph. The production
 * voice pipeline renders clinically reviewed scripts from these structures.
 */
export const EXPERT_EPISODES: AudioEpisode[] = [
  episode({
    id:'rounds-fluid-responsiveness', title:'Fluid responsive does not mean give fluid',
    subtitle:'Separate preload responsiveness, fluid need and fluid tolerance.',
    format:'rounds', level:4, minutes:16, domain:'hemodynamics',
    concepts:['fluid-responsiveness','preload','venous-return','rv-failure'],
    chapters:[
      ['terms','Three different questions',180,['fluid-responsiveness'], 'Can a patient be fluid responsive and still be harmed by fluid?'],
      ['tests','What dynamic tests actually test',260,['fluid-responsiveness','preload']],
      ['tolerance','Congestion and the right heart',260,['rv-failure','venous-return']],
      ['decision','Turn a test into a decision',260,['fluid-responsiveness']],
    ],
    outcomes:['Separate responsiveness from indication and tolerance.','Use a dynamic test as evidence inside a physiologic model rather than as a command to give volume.'],
  }),
  episode({
    id:'rounds-driving-pressure', title:'Driving pressure: why the same tidal volume is not the same breath',
    subtitle:'Link plateau pressure, PEEP, compliance and the functional size of the ventilated lung.',
    format:'rounds', level:3, minutes:15, domain:'respiratory',
    concepts:['driving-pressure','compliance','ards','mechanical-power'],
    chapters:[
      ['calc','The bedside calculation',180,['driving-pressure']],
      ['meaning','What the number is expressing',260,['driving-pressure','compliance']],
      ['ards','The baby-lung problem',240,['ards']],
      ['power','Driving pressure is not the whole injury model',220,['mechanical-power']],
    ],
    outcomes:['Calculate and interpret driving pressure.','Explain why identical tidal volumes can impose very different mechanical stress.'],
  }),
  episode({
    id:'deep-mechanical-power', title:'Mechanical power: the ventilator delivers energy, not just breaths',
    subtitle:'Pressure, volume, flow and respiratory rate combine into an energy load.',
    format:'deep-dive', level:4, minutes:32, domain:'respiratory',
    concepts:['mechanical-power','driving-pressure','ards','compliance'],
    chapters:[
      ['energy','From a breath to energy',360,['mechanical-power']],
      ['components','Pressure, volume, flow and rate',480,['mechanical-power']],
      ['lung','Same ventilator, different lung',420,['ards','compliance']],
      ['bedside','Usefulness without fetishizing one equation',420,['mechanical-power','uncertainty']],
    ],
    outcomes:['Explain the components of mechanical power from first principles.','Use the concept to recognize injurious combinations even when any single setting looks acceptable.'],
  }),
  episode({
    id:'literacy-strong-ion', title:'ICU Literacy: strong-ion difference without the religion',
    subtitle:'Use physicochemical acid-base reasoning as another lens, not a replacement identity.',
    format:'icu-literacy', level:5, minutes:20, domain:'renal-metabolic',
    concepts:['strong-ion','acid-base'],
    chapters:[
      ['charge','Electroneutrality and strong ions',300,['strong-ion']],
      ['chloride','Why chloride can acidify plasma',360,['strong-ion']],
      ['albumin','Weak acids and albumin',300,['strong-ion']],
      ['integrate','Translate between frameworks',240,['strong-ion','acid-base']],
    ],
    outcomes:['Explain SID, weak acids and PCO2 conceptually.','Translate common hyperchloremic and hypoalbuminemic states between physicochemical and traditional acid-base frameworks.'],
  }),
  episode({
    id:'rounds-septic-shock', title:'Septic shock is more than low SVR',
    subtitle:'Vasoplegia, venous capacitance, myocardial dysfunction and microcirculation can coexist.',
    format:'rounds', level:4, minutes:22, domain:'infectious',
    concepts:['septic-shock','shock','vasopressors','oxygen-extraction','lactate'],
    chapters:[
      ['tone','Vasoplegia and venous capacitance',300,['septic-shock','vasopressors']],
      ['flow','Flow can be low, normal or high',300,['shock']],
      ['heart','Sepsis can depress the pump too',300,['septic-shock']],
      ['micro','Macrocirculation and microcirculation can disagree',300,['oxygen-extraction','lactate']],
    ],
    outcomes:['Describe multiple simultaneous hemodynamic phenotypes in septic shock.','Reassess pressor, flow and perfusion response instead of treating MAP as the whole syndrome.'],
  }),
  episode({
    id:'deep-cardiogenic-shock', title:'Cardiogenic shock: pressure, flow and congestion',
    subtitle:'Stop using one blood pressure to represent the entire circulation.',
    format:'deep-dive', level:5, minutes:42, domain:'cardiac',
    concepts:['cardiogenic-shock','shock','vasopressors','pa-catheter','mechanical-circulatory-support'],
    chapters:[
      ['phenotype','LV, RV and biventricular failure',420,['cardiogenic-shock','rv-failure']],
      ['coronary','Coronary perfusion and myocardial demand',420,['cardiogenic-shock']],
      ['drugs','Pressor versus inotrope tradeoffs',480,['vasopressors']],
      ['monitor','When invasive hemodynamics clarify the model',420,['pa-catheter']],
      ['support','When drugs are no longer enough',420,['mechanical-circulatory-support']],
    ],
    outcomes:['Phenotype pump failure by flow, congestion and ventricle.','Choose monitoring and support based on the failing physiology rather than a generic shock label.'],
  }),
  episode({
    id:'rounds-massive-pe', title:'Massive PE: the lung can be clear while the circulation collapses',
    subtitle:'Acute RV afterload, dead space and ventricular interaction.',
    format:'rounds', level:4, minutes:20, domain:'cardiac',
    concepts:['pe','rv-failure','pvr','dead-space','ppv-hemodynamics'],
    chapters:[
      ['obstruction','Pulmonary vascular obstruction',260,['pe','pvr']],
      ['rv','Why the RV fails abruptly',300,['rv-failure']],
      ['gas','Dead space and the gas-exchange clues',260,['dead-space']],
      ['airway','Why intubation can be dangerous',300,['ppv-hemodynamics','rv-failure']],
    ],
    outcomes:['Connect PE to RV pressure load, dead space and LV underfilling.','Anticipate why induction and positive pressure can destabilize severe obstructive shock.'],
  }),
  episode({
    id:'rounds-tamponade', title:'Tamponade is a pressure problem, not a Beck-triad trivia question',
    subtitle:'Pericardial constraint, ventricular interaction and precarious venous return.',
    format:'rounds', level:4, minutes:17, domain:'cardiac',
    concepts:['tamponade','preload','ventricular-interdependence','ppv-hemodynamics'],
    chapters:[
      ['constraint','The pericardium becomes the problem',260,['tamponade']],
      ['coupling','The ventricles compete for space',240,['ventricular-interdependence']],
      ['return','Venous return becomes fragile',240,['preload']],
      ['pressure','Positive pressure changes the gradient',240,['ppv-hemodynamics']],
    ],
    outcomes:['Explain tamponade from chamber and pericardial pressures.','Predict why positive pressure and loss of sympathetic tone can precipitate collapse.'],
  }),
  episode({
    id:'deep-vasoactives', title:'Vasopressors and inotropes by physiology',
    subtitle:'Arterial tone, venous tone, contractility, heart rate and regional flow.',
    format:'deep-dive', level:4, minutes:45, domain:'pharmacology',
    concepts:['vasopressors','shock','septic-shock','cardiogenic-shock','rv-failure'],
    chapters:[
      ['receptors','Receptors are only the beginning',420,['vasopressors']],
      ['venous','The venous circulation matters',420,['venous-return','vasopressors']],
      ['sepsis','Vasoplegic shock',420,['septic-shock']],
      ['pump','Pump failure and inotropy',420,['cardiogenic-shock']],
      ['rv','The failing right ventricle',420,['rv-failure']],
      ['tradeoff','Every catecholamine has a cost',360,['vasopressors','uncertainty']],
    ],
    outcomes:['Choose vasoactive strategy from the physiologic deficit.','Predict intended and adverse responses before titrating.'],
  }),
  episode({
    id:'rounds-coagulopathy', title:'Coagulopathy: stop treating INR as the clot',
    subtitle:'Platelets, fibrinogen, factors, fibrinolysis, calcium and temperature work as a system.',
    format:'rounds', level:4, minutes:22, domain:'hematology',
    concepts:['coagulopathy','massive-transfusion','transfusion'],
    chapters:[
      ['clot','Build a clot in your head',260,['coagulopathy']],
      ['fibrinogen','Fibrinogen and platelets',260,['coagulopathy']],
      ['environment','Temperature, calcium and pH',260,['massive-transfusion']],
      ['testing','What conventional and viscoelastic tests can and cannot tell you',300,['coagulopathy']],
    ],
    outcomes:['Reason from the failing component of hemostasis.','Anticipate resuscitation-induced coagulopathy before a single conventional lab value declares it.'],
  }),
  episode({
    id:'rounds-dka-potassium', title:'DKA potassium: the serum number lies about the body store',
    subtitle:'Insulin deficiency, acidosis, osmotic diuresis and treatment shift potassium in different directions.',
    format:'rounds', level:3, minutes:18, domain:'endocrine',
    concepts:['dka','acid-base'],
    chapters:[
      ['before','Total-body depletion with a normal or high serum K',280,['dka']],
      ['insulin','What insulin does next',260,['dka']],
      ['acid','Acid-base and potassium are related but not one-to-one',260,['acid-base']],
      ['monitor','Trend the physiology through treatment',260,['dka']],
    ],
    outcomes:['Explain why serum potassium can be high despite total-body depletion.','Predict how insulin and correction of acidosis can unmask dangerous hypokalemia.'],
  }),
  episode({
    id:'deep-acute-liver-failure', title:'Acute liver failure: the liver, brain and circulation fail together',
    subtitle:'Synthetic failure, ammonia, cerebral edema, vasodilation and transplant urgency.',
    format:'deep-dive', level:5, minutes:40, domain:'gi-hepatic',
    concepts:['acute-liver-failure','hepatic-encephalopathy','coagulopathy','icp-cpp','crrt'],
    chapters:[
      ['different','Acute failure is not chronic cirrhosis',360,['acute-liver-failure']],
      ['brain','Ammonia and cerebral edema',480,['hepatic-encephalopathy','icp-cpp']],
      ['clot','Coagulopathy is not synonymous with spontaneous bleeding risk',360,['coagulopathy']],
      ['circulation','Vasodilation and multiorgan failure',360,['shock']],
      ['bridge','Support while moving toward transplant',360,['crrt','acute-liver-failure']],
    ],
    outcomes:['Integrate neurologic, metabolic, coagulation and circulatory consequences of acute liver failure.','Recognize why early transplant-center involvement is part of critical care, not an afterthought.'],
  }),
  episode({
    id:'rounds-gi-bleed', title:'The crashing GI bleed',
    subtitle:'Resuscitation, airway judgment, portal hypertension and definitive source control.',
    format:'rounds', level:4, minutes:20, domain:'gi-hepatic',
    concepts:['gi-hemorrhage','massive-transfusion','coagulopathy','source-control'],
    chapters:[
      ['first','Resuscitate while locating the source',260,['gi-hemorrhage']],
      ['airway','When airway protection helps—and when intubation adds risk',260,['gi-hemorrhage']],
      ['blood','Blood, calcium, temperature and clot',300,['massive-transfusion','coagulopathy']],
      ['source','Endoscopic/interventional control is the endpoint',260,['source-control']],
    ],
    outcomes:['Run hemorrhage resuscitation and definitive-control planning in parallel.','Recognize physiology and airway features that make severe GI bleeding uniquely dangerous.'],
  }),
  episode({
    id:'rounds-pancreatitis', title:'Severe pancreatitis is a multisystem ICU disease',
    subtitle:'Capillary leak, respiratory failure, renal injury, nutrition and infection over time.',
    format:'rounds', level:4, minutes:20, domain:'gi-hepatic',
    concepts:['acute-pancreatitis','shock','ards','crrt','nutrition'],
    chapters:[
      ['early','The early inflammatory phase',260,['acute-pancreatitis','shock']],
      ['lung','Why the lungs often join the problem',260,['ards']],
      ['kidney','AKI and fluid accumulation',260,['crrt']],
      ['later','Necrosis, infection and nutrition',260,['nutrition','source-control']],
    ],
    outcomes:['Anticipate the changing organ-support needs of severe pancreatitis.','Separate early inflammatory deterioration from later infectious complications.'],
  }),
  episode({
    id:'rounds-icu-nutrition', title:'ICU nutrition is not just calories',
    subtitle:'Route, protein, aspiration, hemodynamics and the metabolic cost of critical illness.',
    format:'rounds', level:3, minutes:18, domain:'gi-hepatic',
    concepts:['nutrition','refeeding','recovery-weakness'],
    chapters:[
      ['why','What feeding is trying to accomplish',240,['nutrition']],
      ['route','Enteral versus parenteral reasoning',240,['nutrition']],
      ['refeed','When feeding itself becomes dangerous',260,['refeeding']],
      ['recovery','Protein, mobility and recovery',260,['recovery-weakness']],
    ],
    outcomes:['Frame nutrition as organ-support and recovery therapy.','Recognize refeeding risk before escalating calories.'],
  }),
  episode({
    id:'rounds-hhs', title:'HHS: hyperosmolality is the neurologic problem',
    subtitle:'Profound water deficit, sodium behavior and why correction pace matters.',
    format:'rounds', level:3, minutes:18, domain:'endocrine',
    concepts:['hhs','dka'],
    chapters:[
      ['different','Why HHS is not DKA without ketones',260,['hhs']],
      ['water','The scale of the free-water deficit',260,['hhs']],
      ['sodium','Corrected sodium and effective osmolality',280,['hhs']],
      ['pace','Why trajectories matter during treatment',240,['hhs','uncertainty']],
    ],
    outcomes:['Explain the dominant osmotic physiology of HHS.','Track sodium and osmolality rather than glucose alone during therapy.'],
  }),
  episode({
    id:'rounds-adrenal-crisis', title:'Adrenal crisis hiding inside refractory shock',
    subtitle:'Cortisol, vascular responsiveness and electrolyte clues.',
    format:'rounds', level:3, minutes:14, domain:'endocrine',
    concepts:['adrenal-crisis','shock','vasopressors'],
    chapters:[
      ['clues','The physiology behind the clues',220,['adrenal-crisis']],
      ['shock','Why the circulation stops responding normally',240,['shock','vasopressors']],
      ['context','Steroid exposure, pituitary disease and stress',220,['adrenal-crisis']],
    ],
    outcomes:['Recognize adrenal crisis as a cause of otherwise unexplained shock.','Connect cortisol deficiency to vascular tone, glucose and electrolyte findings.'],
  }),
  episode({
    id:'deep-thyroid-emergencies', title:'Thyroid emergencies at both extremes',
    subtitle:'Thyroid storm and myxedema coma are multisystem failures, not abnormal lab values.',
    format:'deep-dive', level:4, minutes:32, domain:'endocrine',
    concepts:['thyroid-storm','myxedema-coma','cardiogenic-shock','vent-troubleshooting'],
    chapters:[
      ['storm','Thyroid storm physiology',420,['thyroid-storm']],
      ['heart','High-output physiology can become pump failure',300,['cardiogenic-shock']],
      ['myxedema','Myxedema coma physiology',420,['myxedema-coma']],
      ['support','Airway, temperature, sodium and adrenal considerations',420,['vent-troubleshooting']],
    ],
    outcomes:['Recognize severe thyrotoxicosis and severe hypothyroidism as organ-failure syndromes.','Anticipate the cardiovascular and respiratory traps of treatment.'],
  }),
  episode({
    id:'deep-toxic-alcohols', title:'Toxic alcohols: follow the metabolites',
    subtitle:'Osmolar gap, anion gap, end-organ clues and extracorporeal removal.',
    format:'deep-dive', level:4, minutes:34, domain:'toxicology',
    concepts:['toxic-alcohols','acid-base','crrt'],
    chapters:[
      ['parent','Parent compound versus toxic metabolite',360,['toxic-alcohols']],
      ['gaps','The gaps change with time',420,['acid-base','toxic-alcohols']],
      ['organs','Visual and renal clues',360,['toxic-alcohols']],
      ['block','Block metabolism',360,['toxic-alcohols']],
      ['dialysis','When extracorporeal removal matters',420,['crrt']],
    ],
    outcomes:['Reason from time course, osmolar/anion gaps and organ findings.','Explain why antidotal blockade and dialysis address different parts of the toxicokinetic problem.'],
  }),
  episode({
    id:'rounds-salicylates', title:'Salicylates: do not steal the patient’s compensatory ventilation',
    subtitle:'A mixed acid-base disorder where falling pH changes toxin distribution.',
    format:'rounds', level:4, minutes:20, domain:'toxicology',
    concepts:['salicylate-toxicity','acid-base','crrt'],
    chapters:[
      ['mixed','Respiratory alkalosis plus metabolic acidosis',260,['salicylate-toxicity','acid-base']],
      ['brain','Why pH changes toxicity',260,['salicylate-toxicity']],
      ['airway','The intubation trap',300,['salicylate-toxicity','vent-troubleshooting']],
      ['remove','Alkalinization and extracorporeal removal',260,['crrt']],
    ],
    outcomes:['Recognize severe salicylate poisoning from physiology, not just concentration.','Explain why loss of compensatory ventilation can abruptly worsen toxicity.'],
  }),
  episode({
    id:'deep-cardiotoxic-overdose', title:'Cardiotoxic overdose: when the shock mechanism is the antidote map',
    subtitle:'Beta blockers, calcium-channel blockers and sodium-channel blockade.',
    format:'deep-dive', level:5, minutes:40, domain:'toxicology',
    concepts:['bb-ccb-toxicity','sodium-channel-toxicity','shock','vasopressors'],
    chapters:[
      ['bb','Beta-blocker physiology',360,['bb-ccb-toxicity']],
      ['ccb','Calcium-channel blocker physiology',360,['bb-ccb-toxicity']],
      ['metabolic','Why high-dose insulin can support the poisoned heart',420,['bb-ccb-toxicity']],
      ['sodium','Sodium-channel blockade and the ECG',420,['sodium-channel-toxicity']],
      ['shock','Build the support from the dominant physiology',420,['shock','vasopressors']],
    ],
    outcomes:['Differentiate major cardiotoxic overdose phenotypes.','Map supportive and antidotal strategies to the underlying electrophysiology and metabolism.'],
  }),
  episode({
    id:'deep-transplant-icu', title:'The transplant patient in the ICU',
    subtitle:'Rejection, infection, altered anatomy, drug toxicity and diagnostic humility.',
    format:'deep-dive', level:5, minutes:42, domain:'transplant',
    concepts:['transplant-physiology','immunosuppression','antimicrobial-pkpd','source-control'],
    chapters:[
      ['host','The host is different',360,['immunosuppression']],
      ['timeline','Time from transplant changes the differential',420,['transplant-physiology']],
      ['graft','Graft dysfunction is not automatically rejection',420,['transplant-physiology']],
      ['drugs','Immunosuppressants interact with critical illness',420,['immunosuppression','antimicrobial-pkpd']],
      ['infection','Infection can be quiet and atypical',420,['source-control']],
    ],
    outcomes:['Build a transplant-specific differential without premature closure.','Integrate immune defect, drug exposure, graft physiology and infection timing.'],
  }),
  episode({
    id:'deep-burns', title:'Major burns: resuscitation without fluid creep',
    subtitle:'Capillary leak, airway injury, perfusion endpoints and evolving organ support.',
    format:'deep-dive', level:4, minutes:38, domain:'trauma-burns',
    concepts:['burn-shock','inhalation-injury','shock','oxygen-delivery'],
    chapters:[
      ['size','Estimate injury, then stop worshiping the formula',360,['burn-shock']],
      ['leak','Capillary leak and burn shock',420,['burn-shock','shock']],
      ['airway','Upper airway, lower airway and systemic toxins',420,['inhalation-injury']],
      ['fluid','Titrate resuscitation to physiology',420,['burn-shock']],
      ['later','The physiology keeps changing after day one',300,['burn-shock']],
    ],
    outcomes:['Use burn formulas as starting estimates rather than endpoints.','Separate airway edema, inhalation injury and systemic toxic exposure.'],
  }),
  episode({
    id:'case-polytrauma-tbi', title:'Audio Case: hemorrhagic shock + severe TBI',
    subtitle:'The blood pressure target that helps the brain can worsen uncontrolled hemorrhage.',
    format:'audio-case', level:6, minutes:28, domain:'trauma-burns',
    concepts:['traumatic-brain-injury','massive-transfusion','icp-cpp','multisystem-tradeoffs','uncertainty'],
    chapters:[
      ['arrival','Two life threats, competing priorities',300,['traumatic-brain-injury','massive-transfusion'], 'What harm could come from treating either problem in isolation?'],
      ['pressure','CPP meets hemorrhage',360,['icp-cpp','multisystem-tradeoffs']],
      ['coag','Coagulopathy and brain injury',300,['coagulopathy']],
      ['decision','Choose the least harmful bridge',360,['uncertainty','multisystem-tradeoffs']],
    ],
    outcomes:['Balance cerebral perfusion with hemorrhage control under uncertainty.','State what data would cause you to change the resuscitation strategy.'],
  }),
  episode({
    id:'rounds-ob-hemorrhage', title:'Obstetric hemorrhage: pregnancy can hide the shock',
    subtitle:'Source control, fibrinogen and massive transfusion in a different circulation.',
    format:'rounds', level:4, minutes:20, domain:'obstetric',
    concepts:['ob-hemorrhage','massive-transfusion','coagulopathy'],
    chapters:[
      ['reserve','Why vital signs can lag behind blood loss',260,['ob-hemorrhage']],
      ['source','Uterine source control',260,['ob-hemorrhage']],
      ['clot','Fibrinogen and coagulopathy',260,['coagulopathy']],
      ['system','Run the hemorrhage system early',260,['massive-transfusion']],
    ],
    outcomes:['Recognize major obstetric bleeding before hypotension declares it.','Integrate source control and balanced hemorrhagic resuscitation.'],
  }),
  episode({
    id:'deep-preeclampsia', title:'Preeclampsia and eclampsia: a multisystem endothelial disease',
    subtitle:'Brain, liver, kidney, platelets, lung and placenta can all become part of the syndrome.',
    format:'deep-dive', level:4, minutes:34, domain:'obstetric',
    concepts:['preeclampsia-eclampsia','icp-cpp','coagulopathy'],
    chapters:[
      ['syndrome','Severe features across organ systems',360,['preeclampsia-eclampsia']],
      ['brain','Seizure and cerebral complications',360,['icp-cpp']],
      ['blood','Platelets, liver and HELLP',360,['coagulopathy']],
      ['lung','Pulmonary edema and fluid sensitivity',360,['preeclampsia-eclampsia']],
      ['definitive','Stabilization and definitive obstetric management',300,['preeclampsia-eclampsia']],
    ],
    outcomes:['Recognize severe disease as a multisystem syndrome.','Balance seizure prevention, pressure control and definitive obstetric management.'],
  }),
  episode({
    id:'rounds-peripartum-cm', title:'Peripartum cardiomyopathy: when “normal postpartum” is heart failure',
    subtitle:'Recognize pump failure in a period full of misleading symptoms.',
    format:'rounds', level:4, minutes:17, domain:'obstetric',
    concepts:['peripartum-cardiomyopathy','cardiogenic-shock'],
    chapters:[
      ['clues','Normal symptoms can camouflage failure',240,['peripartum-cardiomyopathy']],
      ['hemo','The pump-failure model',260,['cardiogenic-shock']],
      ['therapy','Pregnancy/postpartum context changes therapy',260,['peripartum-cardiomyopathy']],
    ],
    outcomes:['Recognize peripartum heart failure early.','Apply cardiogenic-shock physiology while respecting pregnancy/postpartum constraints.'],
  }),
  episode({
    id:'deep-pediatric-shock', title:'Pediatric shock: hypotension is late',
    subtitle:'Compensation, age-adjusted physiology and why children are not small adults.',
    format:'deep-dive', level:4, minutes:34, domain:'peds-neonatal',
    concepts:['pediatric-shock','shock','oxygen-delivery'],
    chapters:[
      ['comp','How children compensate',360,['pediatric-shock']],
      ['age','Age changes what “normal” means',360,['pediatric-shock']],
      ['do2','Oxygen delivery and metabolic demand',360,['oxygen-delivery']],
      ['phenotype','Distributive, hypovolemic and pump failure',420,['shock']],
    ],
    outcomes:['Recognize pediatric shock before hypotension.','Reason from age, size and physiology rather than scaled adult thresholds.'],
  }),
  episode({
    id:'deep-neonatal-transition', title:'From placenta to lungs: neonatal transition',
    subtitle:'PVR falls, shunts change direction and the circulation rewires itself in minutes.',
    format:'deep-dive', level:4, minutes:32, domain:'peds-neonatal',
    concepts:['neonatal-transition','pvr','congenital-heart'],
    chapters:[
      ['fetal','The fetal circulation before birth',360,['neonatal-transition']],
      ['firstbreath','What the first breaths do to PVR',360,['pvr']],
      ['shunts','Ductus and foramen ovale change roles',360,['neonatal-transition']],
      ['failure','When transition fails',360,['congenital-heart']],
    ],
    outcomes:['Explain fetal-to-neonatal circulation as a pressure/flow transition.','Predict how persistent high PVR changes shunt direction and oxygenation.'],
  }),
  episode({
    id:'deep-congenital-heart', title:'Critical congenital heart disease without memorizing twenty lesions',
    subtitle:'Think pulmonary flow, systemic flow, mixing and ductal dependence.',
    format:'deep-dive', level:5, minutes:45, domain:'peds-neonatal',
    concepts:['congenital-heart','neonatal-transition','oxygen-delivery','pvr'],
    chapters:[
      ['topology','Four questions for any lesion',360,['congenital-heart']],
      ['pulm','Pulmonary blood-flow limitation',420,['congenital-heart']],
      ['systemic','Systemic blood-flow limitation',420,['congenital-heart']],
      ['mixing','Mixing lesions',420,['congenital-heart']],
      ['resistance','Oxygen and ventilation can change shunt balance',420,['pvr']],
    ],
    outcomes:['Classify critical congenital lesions by circulation topology.','Predict how PVR/SVR changes alter shunt balance and oxygen delivery.'],
  }),
  episode({
    id:'rounds-pediatric-airway', title:'The pediatric airway has less reserve than you think',
    subtitle:'Resistance, dead space, oxygen consumption and why small errors become big quickly.',
    format:'rounds', level:3, minutes:18, domain:'peds-neonatal',
    concepts:['pediatric-airway','vent-troubleshooting','dead-space'],
    chapters:[
      ['size','Small radius, large resistance consequences',260,['pediatric-airway']],
      ['reserve','Higher demand, smaller reserve',240,['pediatric-airway']],
      ['equipment','Dead space and equipment scale',260,['dead-space']],
      ['trouble','Troubleshooting after intubation',260,['vent-troubleshooting']],
    ],
    outcomes:['Explain why pediatric respiratory deterioration can accelerate quickly.','Anticipate resistance and apparatus-dead-space problems unique to smaller patients.'],
  }),
  episode({
    id:'deep-vent-liberation', title:'Liberating the patient from the ventilator',
    subtitle:'Readiness, spontaneous breathing, airway protection and post-extubation support.',
    format:'deep-dive', level:4, minutes:38, domain:'recovery',
    concepts:['vent-weaning','sedation-analgesia','recovery-weakness','cardiogenic-shock'],
    chapters:[
      ['ready','Ready to test is not ready to extubate',360,['vent-weaning']],
      ['sbt','What an SBT stresses',420,['vent-weaning']],
      ['fail','Respiratory, cardiac and neuromuscular failure',420,['cardiogenic-shock','recovery-weakness']],
      ['airway','Airway protection is separate',360,['vent-weaning']],
      ['after','Plan the post-extubation period',360,['vent-weaning']],
    ],
    outcomes:['Separate SBT performance from airway protection and extubation risk.','Diagnose failed liberation by physiology rather than repeatedly restarting the same trial.'],
  }),
  episode({
    id:'rounds-icu-weakness', title:'The patient survived the ICU—now they cannot stand',
    subtitle:'Critical-illness myopathy, neuropathy, sedation, immobility and recovery.',
    format:'rounds', level:3, minutes:18, domain:'recovery',
    concepts:['recovery-weakness','delirium','nutrition','vent-weaning'],
    chapters:[
      ['why','Why weakness develops',240,['recovery-weakness']],
      ['vent','Weakness can become a ventilation problem',240,['vent-weaning']],
      ['bundle','Sedation, mobility and delirium',260,['delirium']],
      ['rebuild','Nutrition and rehabilitation',260,['nutrition']],
    ],
    outcomes:['Recognize ICU-acquired weakness as a predictable organ-system consequence.','Connect daily ICU choices to ventilator liberation and long-term recovery.'],
  }),
  episode({
    id:'rounds-iabp', title:'IABP timing: make the waveform tell you what the balloon is doing',
    subtitle:'Diastolic augmentation and presystolic deflation without memorizing arrows.',
    format:'rounds', level:4, minutes:20, domain:'cardiac',
    concepts:['iabp','arterial-line','cardiogenic-shock'],
    chapters:[
      ['why','What the balloon can and cannot do',260,['iabp']],
      ['inflate','Inflation in diastole',260,['iabp']],
      ['deflate','Deflation before systole',260,['iabp']],
      ['errors','Timing errors on the waveform',300,['arterial-line','iabp']],
    ],
    outcomes:['Explain the intended physiologic effect of inflation and deflation.','Recognize major timing errors from the arterial waveform.'],
  }),
  episode({
    id:'deep-mcs', title:'Mechanical circulatory support: match the device to the failing circulation',
    subtitle:'IABP, axial flow and VA ECMO change loading conditions in different ways.',
    format:'deep-dive', level:5, minutes:45, domain:'cardiac',
    concepts:['mechanical-circulatory-support','iabp','ecmo','cardiogenic-shock','rv-failure'],
    chapters:[
      ['goal','What are you trying to support?',360,['mechanical-circulatory-support']],
      ['iabp','Counterpulsation',360,['iabp']],
      ['axial','Axial-flow unloading',420,['mechanical-circulatory-support']],
      ['va','VA ECMO flow and LV loading',480,['ecmo']],
      ['rv','Right-sided failure changes the answer',360,['rv-failure']],
      ['comp','Device complications are physiology too',360,['mechanical-circulatory-support']],
    ],
    outcomes:['Match temporary support to LV, RV, biventricular or cardiopulmonary failure.','Anticipate how each device changes loading conditions and downstream complications.'],
  }),
  episode({
    id:'deep-status', title:'Status epilepticus: time changes the biology',
    subtitle:'Recognition, medication sequencing, airway consequences and nonconvulsive status.',
    format:'deep-dive', level:4, minutes:34, domain:'neuro',
    concepts:['status-epilepticus','icp-cpp','sedation-analgesia'],
    chapters:[
      ['time','Why ongoing seizure becomes harder to stop',320,['status-epilepticus']],
      ['sequence','Medication sequence as a time problem',360,['status-epilepticus']],
      ['system','Hypoxemia, acidosis, temperature and hemodynamics',360,['icp-cpp']],
      ['after','The convulsions stop—did the seizure?',360,['status-epilepticus']],
    ],
    outcomes:['Treat status as a time-dependent neurologic and systemic emergency.','Recognize when persistent coma requires evaluation for nonconvulsive status.'],
  }),
  episode({
    id:'deep-neuroprognosis', title:'Neuroprognostication: certainty is the dangerous drug',
    subtitle:'Timing, confounders, multimodal evidence and death by neurologic criteria.',
    format:'deep-dive', level:6, minutes:38, domain:'communication-systems',
    concepts:['brain-death-neuroprognosis','uncertainty','goals-care','cognitive-bias'],
    chapters:[
      ['separate','Prognosis is not death determination',300,['brain-death-neuroprognosis']],
      ['confound','Sedation, temperature and metabolism',360,['uncertainty']],
      ['multi','Why multimodal evidence matters',420,['brain-death-neuroprognosis']],
      ['bias','Self-fulfilling prophecy and premature closure',360,['cognitive-bias']],
      ['talk','Communicating uncertainty with families',360,['goals-care']],
    ],
    outcomes:['Separate prognostication from formal death determination.','Use timing and multimodal evidence while explicitly controlling for confounders and cognitive bias.'],
  }),
  episode({
    id:'rounds-goals-care', title:'Goals of care is a clinical skill',
    subtitle:'Values, prognosis, uncertainty and time-limited trials without abandoning critical care.',
    format:'rounds', level:5, minutes:22, domain:'communication-systems',
    concepts:['goals-care','uncertainty'],
    chapters:[
      ['values','Find out what outcomes matter',260,['goals-care']],
      ['forecast','Best case, worst case and most likely',280,['uncertainty','goals-care']],
      ['trial','Design a time-limited trial',300,['goals-care']],
      ['language','Recommend, do not merely list procedures',260,['goals-care']],
    ],
    outcomes:['Frame prognosis without false precision.','Build a time-limited trial with explicit goals and reassessment criteria.'],
  }),
  episode({
    id:'rounds-cognitive-bias', title:'The patient is not obligated to obey your diagnosis',
    subtitle:'Anchoring, premature closure, overconfidence and deliberate model revision.',
    format:'rounds', level:6, minutes:20, domain:'multisystem',
    concepts:['cognitive-bias','uncertainty'],
    chapters:[
      ['anchor','How a useful first impression becomes a trap',260,['cognitive-bias']],
      ['contradict','Look for the fact that should not be there',260,['uncertainty']],
      ['predict','Make the model predict something',260,['uncertainty']],
      ['revise','Failure to respond is diagnostic information',260,['cognitive-bias']],
    ],
    outcomes:['Use explicit debiasing without paralyzing decision-making.','Treat unexpected treatment response as evidence that can falsify the working model.'],
  }),
  episode({
    id:'case-expert-mixed-shock', title:'Expert Case: mixed shock after surgery',
    subtitle:'Vasoplegia, bleeding, RV strain and sedation all remain plausible at the same time.',
    format:'audio-case', level:6, minutes:30, domain:'multisystem',
    concepts:['shock','septic-shock','rv-failure','coagulopathy','uncertainty','cognitive-bias'],
    chapters:[
      ['handoff','The first story is probably incomplete',300,['shock'], 'State your top three physiologic models, not diagnoses.'],
      ['new','New data contradicts the favorite answer',360,['cognitive-bias']],
      ['echo','The RV changes the resuscitation',360,['rv-failure']],
      ['bleed','The drain output changes again',360,['coagulopathy']],
      ['decision','Choose a move that is both treatment and test',360,['uncertainty']],
    ],
    outcomes:['Maintain multiple plausible physiologic models in an evolving patient.','Use treatment response to update probability rather than defend the initial diagnosis.'],
  }),
];
