import type { CriticalCareDomain, MasteryConcept, MasteryLevel } from './types';

export const LEVELS: { level: MasteryLevel; name: string; description: string }[] = [
  { level: 1, name: 'Language & normal physiology', description: 'Anatomy, terminology, normal values and causal relationships.' },
  { level: 2, name: 'Single-system critical illness', description: 'Recognize, explain and initially manage major critical-care syndromes.' },
  { level: 3, name: 'Organ support', description: 'Ventilation, vasoactives, transfusion, sedation, invasive monitoring and procedures.' },
  { level: 4, name: 'Advanced physiology', description: 'Predict responses using pressure, flow, gas exchange, oxygen transport, acid-base and PK/PD.' },
  { level: 5, name: 'Multisystem critical care', description: 'Balance competing organ priorities and understand treatment tradeoffs.' },
  { level: 6, name: 'Expert integration', description: 'Reason through ambiguity, uncertainty, cognitive traps, evolving physiology and imperfect evidence.' },
];

export const DOMAIN_LABELS: Record<CriticalCareDomain, string> = {
  foundations: 'Foundations',
  respiratory: 'Respiratory',
  hemodynamics: 'Hemodynamics & shock',
  cardiac: 'Cardiovascular',
  neuro: 'Neurocritical care',
  'renal-metabolic': 'Renal, endocrine & metabolic',
  infectious: 'Sepsis & infection',
  hematology: 'Hematology & coagulation',
  pharmacology: 'Pharmacology',
  'imaging-monitoring': 'Imaging & monitoring',
  procedures: 'Procedures & devices',
  multisystem: 'Multisystem integration',
  'communication-systems': 'Communication, ethics & ICU systems',
};

export const MASTERY: MasteryConcept[] = [
  {
    id: 'preload', name: 'Preload', domain: 'foundations', level: 1,
    summary: 'The loading conditions of a ventricle before contraction; not synonymous with a single pressure or volume.',
    prereq: [], related: ['venous-return', 'fluid-responsiveness', 'rv-failure'],
    vocabulary: ['end-diastolic volume', 'transmural pressure'],
    performance: ['Distinguish preload from CVP or fluid responsiveness.', 'Predict how changes in intrathoracic pressure alter measured filling pressures.'],
  },
  {
    id: 'venous-return', name: 'Venous return', domain: 'hemodynamics', level: 4,
    summary: 'Flow back to the right heart determined by the pressure gradient from the systemic circulation and resistance to venous return.',
    prereq: ['preload'], related: ['stressed-volume', 'rv-failure', 'ppv-hemodynamics'],
    vocabulary: ['mean systemic filling pressure', 'stressed volume', 'venous return gradient'],
    performance: ['Explain why CVP can rise while venous return falls.', 'Predict effects of vasodilation, venoconstriction and positive pressure on venous return.'],
  },
  {
    id: 'stressed-volume', name: 'Stressed vs unstressed volume', domain: 'hemodynamics', level: 4,
    summary: 'The fraction of blood volume generating elastic recoil pressure versus volume that fills the vasculature without generating pressure.',
    prereq: ['preload'], related: ['venous-return'],
    vocabulary: ['mean systemic filling pressure', 'venous capacitance'],
    performance: ['Explain how venoconstriction can recruit unstressed volume without giving fluid.'],
  },
  {
    id: 'fluid-responsiveness', name: 'Fluid responsiveness', domain: 'hemodynamics', level: 3,
    summary: 'Whether stroke volume will meaningfully increase after an increase in preload; distinct from whether fluid is indicated or safe.',
    prereq: ['preload'], related: ['venous-return', 'rv-failure'],
    vocabulary: ['dynamic assessment', 'passive leg raise'],
    performance: ['Separate responsiveness from tolerance and need.', 'Interpret dynamic tests in their physiologic context and recognize limitations.'],
  },
  {
    id: 'rv-failure', name: 'Right ventricular failure', domain: 'cardiac', level: 4,
    summary: 'Failure of a thin-walled ventricle that is highly sensitive to acute afterload, volume, perfusion pressure and ventricular interaction.',
    prereq: ['preload', 'venous-return'], related: ['pvr', 'ventricular-interdependence', 'ppv-hemodynamics', 'pe'],
    vocabulary: ['RV-PA coupling', 'septal shift', 'transmural pressure'],
    performance: ['Recognize RV shock physiology before systemic hypotension becomes profound.', 'Predict how PEEP, hypercapnia, hypoxemia, fluids and vasoactives may change RV performance.'],
  },
  {
    id: 'pvr', name: 'Pulmonary vascular resistance', domain: 'cardiac', level: 4,
    summary: 'Resistance faced by the RV, influenced by lung volume, oxygenation, CO2, pH, pulmonary vascular disease and mechanical ventilation.',
    prereq: ['preload'], related: ['rv-failure', 'ppv-hemodynamics', 'ards'],
    vocabulary: ['RV afterload', 'West zones'],
    performance: ['Explain the U-shaped relationship between lung volume and pulmonary vascular resistance.', 'Identify reversible contributors to acute RV afterload.'],
  },
  {
    id: 'ventricular-interdependence', name: 'Ventricular interdependence', domain: 'cardiac', level: 4,
    summary: 'The ventricles share a septum and constrained pericardial space, so pressure or volume loading of one changes filling and geometry of the other.',
    prereq: ['rv-failure'], related: ['tamponade', 'ppv-hemodynamics'],
    vocabulary: ['septal shift', 'pericardial constraint'],
    performance: ['Use septal position and loading conditions to explain falling LV output during RV distension.'],
  },
  {
    id: 'ppv-hemodynamics', name: 'Positive-pressure ventilation & circulation', domain: 'respiratory', level: 4,
    summary: 'Positive intrathoracic pressure changes venous return, ventricular transmural pressures and pulmonary vascular resistance.',
    prereq: ['preload'], related: ['rv-failure', 'pvr', 'peep'],
    vocabulary: ['transmural pressure', 'mean airway pressure'],
    performance: ['Predict why induction and positive pressure can precipitate hypotension.', 'Distinguish effects on RV preload, RV afterload and LV transmural afterload.'],
  },
  {
    id: 'peep', name: 'PEEP', domain: 'respiratory', level: 2,
    summary: 'Positive end-expiratory pressure used to preserve recruitment and oxygenation, with important mechanical and hemodynamic effects.',
    prereq: [], related: ['ards', 'ppv-hemodynamics', 'driving-pressure'],
    vocabulary: ['recruitability', 'intrinsic PEEP'],
    performance: ['Explain when increasing PEEP may recruit lung versus overdistend it.', 'Anticipate circulatory effects in preload-dependent or RV-failing patients.'],
  },
  {
    id: 'driving-pressure', name: 'Driving pressure', domain: 'respiratory', level: 3,
    summary: 'Plateau pressure minus total PEEP; a bedside expression of tidal strain relative to respiratory-system compliance.',
    prereq: ['peep'], related: ['ards', 'compliance', 'mechanical-power'],
    vocabulary: ['plateau pressure', 'tidal strain'],
    performance: ['Calculate and interpret driving pressure.', 'Explain why the same tidal volume can have different mechanical consequences in different lungs.'],
  },
  {
    id: 'compliance', name: 'Compliance & elastance', domain: 'foundations', level: 1,
    summary: 'Compliance describes change in volume for change in pressure; elastance is its inverse.',
    prereq: [], related: ['driving-pressure', 'ards'],
    vocabulary: ['static compliance', 'elastance'],
    performance: ['Separate resistance problems from compliance problems using peak and plateau pressures.'],
  },
  {
    id: 'ards', name: 'ARDS physiology', domain: 'respiratory', level: 3,
    summary: 'Diffuse inflammatory lung injury producing heterogeneity, shunt, low aerated lung volume and risk from ventilator-induced injury.',
    prereq: ['compliance', 'peep'], related: ['driving-pressure', 'pvr', 'oxygen-delivery'],
    vocabulary: ['baby lung', 'shunt', 'recruitability'],
    performance: ['Integrate oxygenation, mechanics, recruitability and hemodynamics rather than treating a P/F ratio in isolation.'],
  },
  {
    id: 'mechanical-power', name: 'Mechanical power', domain: 'respiratory', level: 4,
    summary: 'Energy delivered to the respiratory system over time from pressure, volume, flow and respiratory rate.',
    prereq: ['driving-pressure'], related: ['ards'],
    vocabulary: ['energy load', 'ventilator-induced lung injury'],
    performance: ['Explain how respiratory rate and flow can increase ventilator energy even when tidal volume appears acceptable.'],
  },
  {
    id: 'dead-space', name: 'Dead space', domain: 'respiratory', level: 3,
    summary: 'Ventilation that does not effectively participate in CO2 exchange, from conducting airways or ventilated but poorly perfused alveoli.',
    prereq: [], related: ['pe', 'ards', 'etco2-gap'],
    vocabulary: ['VD/VT', 'alveolar dead space'],
    performance: ['Use PaCO2–EtCO2 behavior and minute ventilation requirements to reason about changing dead space.'],
  },
  {
    id: 'oxygen-delivery', name: 'Oxygen delivery', domain: 'hemodynamics', level: 3,
    summary: 'DO2 is cardiac output multiplied by arterial oxygen content; saturation alone does not describe tissue oxygen delivery.',
    prereq: [], related: ['oxygen-extraction', 'shock', 'transfusion'],
    vocabulary: ['CaO2', 'DO2', 'VO2'],
    performance: ['Predict effects of hemoglobin, saturation and flow on oxygen delivery.', 'Explain why a normal SpO2 can coexist with inadequate DO2.'],
  },
  {
    id: 'oxygen-extraction', name: 'Oxygen extraction', domain: 'hemodynamics', level: 4,
    summary: 'The relationship between delivered and consumed oxygen reflected by venous saturation and tissue extraction.',
    prereq: ['oxygen-delivery'], related: ['shock', 'lactate'],
    vocabulary: ['O2ER', 'SvO2', 'critical DO2'],
    performance: ['Interpret low or high venous saturation in context rather than labeling it simply good or bad.'],
  },
  {
    id: 'shock', name: 'Shock phenotyping', domain: 'hemodynamics', level: 3,
    summary: 'Identify inadequate effective circulation by integrating flow, vascular tone, congestion, oxygen delivery and organ response.',
    prereq: ['oxygen-delivery'], related: ['septic-shock', 'rv-failure', 'cardiogenic-shock'],
    vocabulary: ['flow', 'tone', 'congestion', 'perfusion'],
    performance: ['Recognize mixed shock.', 'Choose an intervention that tests a physiologic hypothesis and define the response expected if that hypothesis is correct.'],
  },
  {
    id: 'lactate', name: 'Lactate physiology', domain: 'renal-metabolic', level: 3,
    summary: 'Lactate reflects production and clearance across multiple pathways and is not a direct tissue-hypoxia meter.',
    prereq: ['oxygen-delivery'], related: ['shock', 'septic-shock'],
    vocabulary: ['adrenergic glycolysis', 'clearance'],
    performance: ['Generate hypoxic and non-hypoxic explanations for elevated lactate.', 'Interpret trajectory alongside perfusion rather than in isolation.'],
  },
  {
    id: 'acid-base', name: 'Advanced acid-base reasoning', domain: 'renal-metabolic', level: 4,
    summary: 'Integrate respiratory and metabolic processes, compensation, anion gap, albumin, chloride and mixed disorders.',
    prereq: [], related: ['strong-ion', 'dka'],
    vocabulary: ['delta gap', 'expected compensation'],
    performance: ['Identify mixed disorders that a single pH label hides.', 'Connect acid-base abnormalities to the underlying physiology and treatment.'],
  },
  {
    id: 'strong-ion', name: 'Strong-ion approach', domain: 'renal-metabolic', level: 5,
    summary: 'A physicochemical framework using strong-ion difference, total weak acids and PCO2 to explain acid-base state.',
    prereq: ['acid-base'], related: [],
    vocabulary: ['SID', 'Atot'],
    performance: ['Use the framework to explain hyperchloremic acidosis and effects of albumin without treating it as a competing religion to bicarbonate-based analysis.'],
  },
  {
    id: 'icp-cpp', name: 'ICP, CPP & cerebral perfusion', domain: 'neuro', level: 3,
    summary: 'Cerebral perfusion depends on the gradient across the cerebral circulation and is influenced by pressure, venous outflow, CO2 and intracranial compliance.',
    prereq: [], related: ['herniation', 'evd'],
    vocabulary: ['CPP', 'autoregulation', 'Monro-Kellie'],
    performance: ['Predict how systemic pressure, CO2 and venous pressure affect cerebral perfusion.', 'Recognize when a normal MAP does not guarantee adequate CPP.'],
  },
  {
    id: 'evd', name: 'EVD management', domain: 'procedures', level: 3,
    summary: 'External ventricular drainage requires correct leveling, clamping during movement and interpretation of drainage and ICP.',
    prereq: ['icp-cpp'], related: ['herniation'],
    vocabulary: ['tragus', 'foramen of Monro'],
    performance: ['Explain over-drainage versus under-drainage from transducer/chamber position.', 'Mentally rehearse safe movement and re-leveling.'],
  },
  {
    id: 'arterial-line', name: 'Arterial line', domain: 'procedures', level: 3,
    summary: 'Placement, setup, leveling, zeroing, waveform interpretation and troubleshooting of invasive arterial pressure monitoring.',
    prereq: [], related: ['waveform-damping'],
    vocabulary: ['phlebostatic axis', 'dynamic response'],
    performance: ['Differentiate patient physiology from damping/resonance artifact.', 'Mentally rehearse sterile insertion and transducer setup.'],
  },
  {
    id: 'waveform-damping', name: 'Arterial waveform damping & resonance', domain: 'imaging-monitoring', level: 4,
    summary: 'The monitoring system can distort systolic and diastolic pressures while mean pressure is relatively preserved.',
    prereq: ['arterial-line'], related: [],
    vocabulary: ['square-wave test', 'natural frequency'],
    performance: ['Recognize over- and under-damped systems and troubleshoot tubing, bubbles, clot and excessive resonance.'],
  },
  {
    id: 'efast', name: 'eFAST', domain: 'imaging-monitoring', level: 3,
    summary: 'Structured point-of-care ultrasound for pericardial, intraperitoneal and pleural pathology in trauma.',
    prereq: [], related: ['ptx-us', 'hemoperitoneum'],
    vocabulary: ['Morison pouch', 'splenorenal', 'lung sliding'],
    performance: ['Acquire and orient the core windows.', 'Recognize free fluid and common false positives/negatives while integrating the clinical context.'],
  },
  {
    id: 'transfusion', name: 'Blood product initiation & monitoring', domain: 'hematology', level: 3,
    summary: 'Safe preparation, verification, administration, monitoring and recognition of transfusion complications.',
    prereq: ['oxygen-delivery'], related: ['massive-transfusion', 'coagulopathy'],
    vocabulary: ['component therapy', 'transfusion reaction'],
    performance: ['Mentally rehearse the verification-to-monitoring sequence.', 'Recognize early signs that require stopping and reassessment per local policy.'],
  },
  {
    id: 'push-dose-pressor', name: 'Push-dose vasopressor workflow', domain: 'pharmacology', level: 3,
    summary: 'A high-risk, short-duration bridge that demands concentration verification, labeling, closed-loop communication and continuous reassessment.',
    prereq: ['shock'], related: ['vasopressors', 'medication-safety'],
    vocabulary: ['concentration', 'dose-response', 'extravasation'],
    performance: ['Rehearse safe preparation and independent verification without relying on memory alone.', 'Define the physiologic response and adverse response you are watching for.'],
  },
  {
    id: 'medication-safety', name: 'High-risk medication safety', domain: 'pharmacology', level: 2,
    summary: 'Use standardized concentration, labeling, independent verification, closed-loop communication and context checks for high-risk drugs.',
    prereq: [], related: ['push-dose-pressor'],
    performance: ['Catch concentration and route errors before administration.', 'Use local protocol and pharmacy-standard concentrations rather than improvised memory.'],
  },
  {
    id: 'chest-tube', name: 'Pleural drain / chest tube', domain: 'procedures', level: 3,
    summary: 'Indication, anatomy, insertion concepts, system setup, confirmation and complication recognition for pleural drainage.',
    prereq: [], related: ['ptx-us', 'drain-troubleshooting'],
    performance: ['Rehearse anatomical orientation and sterile setup.', 'Recognize a nonfunctioning drain by patient physiology and system findings.'],
  },
  {
    id: 'central-line', name: 'Ultrasound-guided central venous access', domain: 'procedures', level: 3,
    summary: 'Safe venous access requires anatomy, real-time tip awareness, vessel confirmation, wire control, sterile technique and complication recognition.',
    prereq: [], related: ['medication-safety', 'shock'],
    vocabulary: ['Seldinger technique', 'compressibility', 'guidewire'],
    performance: ['Distinguish vein from artery using more than color.', 'Rehearse seeing the wire in the intended vessel before dilation and keeping control of the wire throughout.'],
  },
  {
    id: 'io-access', name: 'Intraosseous access', domain: 'procedures', level: 2,
    summary: 'Rapid vascular access through the medullary space when conventional access is delayed or unreliable.',
    prereq: [], related: ['shock', 'medication-safety'],
    vocabulary: ['cortex', 'medullary space', 'extravasation'],
    performance: ['Identify the correct landmark for the chosen approved site and device.', 'Confirm functional placement and recognize extravasation or compartment-risk signs.'],
  },
  {
    id: 'vent-troubleshooting', name: 'Ventilator emergency troubleshooting', domain: 'respiratory', level: 3,
    summary: 'A structured patient-to-device approach to acute hypoxemia, high pressure, low pressure, dyssynchrony and post-intubation deterioration.',
    prereq: ['compliance'], related: ['dead-space', 'peep', 'ppv-hemodynamics'],
    vocabulary: ['DOPES', 'peak pressure', 'plateau pressure', 'auto-PEEP'],
    performance: ['Separate resistance, compliance, circuit and patient problems using waveforms and bedside examination.', 'Prioritize oxygenation and manual ventilation when the device or circuit cannot be trusted.'],
  },
  {
    id: 'massive-transfusion', name: 'Massive transfusion & hemorrhagic resuscitation', domain: 'hematology', level: 4,
    summary: 'Hemorrhagic resuscitation integrates source control, balanced component replacement, calcium, temperature, coagulation and perfusion.',
    prereq: ['transfusion', 'shock'], related: ['coagulopathy', 'oxygen-delivery'],
    vocabulary: ['MTP', 'fibrinogen', 'ionized calcium', 'lethal triad'],
    performance: ['Run the resuscitation as a system rather than as isolated blood-unit administration.', 'Recognize dilutional/coagulopathic, hypocalcemic and hypothermic deterioration early.'],
  },
  {
    id: 'source-control', name: 'Source control', domain: 'infectious', level: 3,
    summary: 'Definitive management of infected material, devitalized tissue or an infected device can be as important as antimicrobial therapy.',
    prereq: [], related: ['septic-shock', 'antimicrobial-pkpd'],
    vocabulary: ['drainage', 'debridement', 'device removal'],
    performance: ['Identify when antibiotics alone are unlikely to succeed.', 'Escalate procedural or surgical source control as part of the resuscitation plan.'],
  },
  {
    id: 'antimicrobial-pkpd', name: 'Antimicrobial PK/PD in critical illness', domain: 'infectious', level: 4,
    summary: 'Critical illness changes volume of distribution, clearance and target attainment, so dose strategy must match drug and patient physiology.',
    prereq: [], related: ['source-control', 'crrt'],
    vocabulary: ['time above MIC', 'AUC/MIC', 'augmented renal clearance'],
    performance: ['Explain why standard dosing can underdose a shocked or hyperdynamic patient.', 'Integrate renal support and changing clearance into antimicrobial strategy.'],
  },
  {
    id: 'crrt', name: 'CRRT physiology & prescription literacy', domain: 'renal-metabolic', level: 4,
    summary: 'Continuous renal replacement uses diffusion and/or convection to manage solute, acid-base and fluid balance in unstable patients.',
    prereq: ['acid-base'], related: ['antimicrobial-pkpd', 'shock'],
    vocabulary: ['effluent dose', 'CVVH', 'CVVHD', 'CVVHDF', 'filtration fraction'],
    performance: ['Explain diffusion versus convection and net ultrafiltration.', 'Recognize how circuit, anticoagulation and prescribed versus delivered dose change therapy.'],
  },
  {
    id: 'pa-catheter', name: 'Pulmonary artery catheter interpretation', domain: 'imaging-monitoring', level: 5,
    summary: 'A PA catheter is useful only when waveforms, zero/level, thermodilution assumptions and the clinical model are integrated correctly.',
    prereq: ['arterial-line', 'rv-failure'], related: ['oxygen-extraction', 'shock'],
    vocabulary: ['RAP', 'PAP', 'PAOP', 'thermodilution', 'PVR', 'SVR'],
    performance: ['Recognize chamber waveforms during insertion and interpret pressures in physiologic context.', 'Use serial values to test a hemodynamic model rather than treating targets in isolation.'],
  },
  {
    id: 'ecmo', name: 'ECMO circuit & physiology literacy', domain: 'multisystem', level: 5,
    summary: 'Extracorporeal support changes preload, afterload, gas exchange and oxygen delivery through a circuit whose configuration determines what it can support.',
    prereq: ['oxygen-delivery', 'shock'], related: ['rv-failure', 'ards'],
    vocabulary: ['VV ECMO', 'VA ECMO', 'sweep gas', 'recirculation', 'differential hypoxemia'],
    performance: ['Distinguish VV from VA support goals and limitations.', 'Reason from circuit flow, native heart/lung function and cannula position to common failure patterns.'],
  },
  {
    id: 'sedation-analgesia', name: 'ICU analgesia, sedation & synchrony', domain: 'pharmacology', level: 3,
    summary: 'Sedation strategy balances analgesia, comfort, ventilator synchrony, neurologic assessment, hemodynamics and delirium risk.',
    prereq: [], related: ['delirium', 'vent-troubleshooting'],
    vocabulary: ['analgosedation', 'RASS', 'daily awakening'],
    performance: ['Separate pain, anxiety, delirium and dyssynchrony before simply deepening sedation.', 'Predict major hemodynamic and respiratory tradeoffs of sedative strategies.'],
  },
  {
    id: 'delirium', name: 'Delirium, sleep & mobility', domain: 'communication-systems', level: 3,
    summary: 'Brain dysfunction in critical illness is shaped by disease, drugs, sleep disruption, immobility and environment.',
    prereq: [], related: ['sedation-analgesia'],
    vocabulary: ['CAM-ICU', 'ABCDE/ABCDEF bundle'],
    performance: ['Recognize modifiable drivers of delirium.', 'Integrate sedation reduction, sleep, mobility and family engagement into daily ICU care.'],
  },
  {
    id: 'goals-care', name: 'Goals of care & prognostic communication', domain: 'communication-systems', level: 5,
    summary: 'High-quality critical care includes eliciting values, communicating uncertainty and aligning burdensome treatments with realistic goals.',
    prereq: ['uncertainty'], related: [],
    vocabulary: ['surrogate decision-maker', 'time-limited trial', 'best case / worst case'],
    performance: ['Explain prognosis without false precision.', 'Frame a time-limited trial with explicit goals and reassessment criteria.'],
  },
  {
    id: 'septic-shock', name: 'Septic shock physiology', domain: 'infectious', level: 3,
    summary: 'Distributive shock with dynamic changes in vascular tone, venous capacitance, myocardial performance, microcirculation and oxygen extraction.',
    prereq: ['shock'], related: ['source-control', 'lactate', 'vasopressors'],
    vocabulary: ['vasoplegia', 'microcirculation', 'distributive shock'],
    performance: ['Recognize when septic shock is not simply low SVR.', 'Integrate source control, flow, tone, cardiac function and perfusion response over time.'],
  },
  {
    id: 'cardiogenic-shock', name: 'Cardiogenic shock', domain: 'cardiac', level: 4,
    summary: 'Pump failure where restoring perfusion must be balanced against congestion, myocardial oxygen demand, coronary perfusion and mechanical complications.',
    prereq: ['shock'], related: ['rv-failure', 'vasopressors', 'pa-catheter'],
    vocabulary: ['cardiac power output', 'congestion', 'inotropy'],
    performance: ['Phenotype left-, right- and biventricular pump failure.', 'Choose support based on pressure, flow, congestion and the cause of pump failure.'],
  },
  {
    id: 'pe', name: 'Pulmonary embolism physiology', domain: 'cardiac', level: 3,
    summary: 'Acute pulmonary vascular obstruction can abruptly raise RV afterload, impair LV filling and cause shock despite structurally normal lungs.',
    prereq: ['pvr'], related: ['rv-failure', 'dead-space'],
    vocabulary: ['obstructive shock', 'RV strain', 'dead space'],
    performance: ['Connect clot burden to RV pressure load, septal interaction and gas-exchange findings.', 'Recognize why intubation and excessive positive pressure may destabilize severe PE.'],
  },
  {
    id: 'tamponade', name: 'Cardiac tamponade physiology', domain: 'cardiac', level: 3,
    summary: 'Pericardial pressure constrains chamber filling, couples the ventricles and makes venous return highly sensitive to pressure gradients.',
    prereq: ['preload'], related: ['ventricular-interdependence', 'shock'],
    vocabulary: ['pericardial pressure', 'respiratory variation', 'diastolic collapse'],
    performance: ['Explain tamponade as a filling-pressure problem rather than a checklist of classic signs.', 'Predict effects of positive pressure and volume changes on a preload-limited circulation.'],
  },
  {
    id: 'vasopressors', name: 'Vasopressor & inotrope physiology', domain: 'pharmacology', level: 3,
    summary: 'Vasoactive drugs change arterial tone, venous tone, heart rate, contractility and regional flow; the desired effect depends on the shock model.',
    prereq: ['shock'], related: ['push-dose-pressor', 'septic-shock', 'cardiogenic-shock'],
    vocabulary: ['alpha-1', 'beta-1', 'inotropy', 'chronotropy', 'venoconstriction'],
    performance: ['Choose a vasoactive strategy from the physiologic deficit rather than blood pressure alone.', 'State the expected benefit, predictable tradeoff and reassessment endpoint.'],
  },
  {
    id: 'coagulopathy', name: 'Critical-illness coagulopathy', domain: 'hematology', level: 4,
    summary: 'Bleeding and thrombosis reflect platelets, fibrinogen, coagulation factors, fibrinolysis, temperature, calcium, dilution and disease-specific pathways.',
    prereq: ['transfusion'], related: ['massive-transfusion'],
    vocabulary: ['fibrinolysis', 'fibrinogen', 'viscoelastic testing'],
    performance: ['Reason from the failing component of clot formation rather than treating INR alone.', 'Anticipate temperature, calcium and dilution effects during hemorrhagic resuscitation.'],
  },
  {
    id: 'cognitive-bias', name: 'Cognitive bias & diagnostic error', domain: 'multisystem', level: 6,
    summary: 'Expert reasoning uses deliberate checks against anchoring, premature closure, confirmation bias and overconfidence while still making timely decisions.',
    prereq: ['uncertainty'], related: [],
    vocabulary: ['anchoring', 'premature closure', 'diagnostic time-out'],
    performance: ['Name the evidence that does not fit the favored diagnosis.', 'Deliberately generate an alternative model when the patient fails to respond as predicted.'],
  },
  {
    id: 'drain-troubleshooting', name: 'Pleural drain troubleshooting', domain: 'procedures', level: 3,
    summary: 'A pleural drain must be assessed as patient + tube + connections + drainage system rather than as an isolated device.',
    prereq: ['chest-tube'], related: ['ptx-us', 'vent-troubleshooting'],
    vocabulary: ['water seal', 'tidaling', 'air leak'],
    performance: ['Trace a failing drain from the patient outward.', 'Differentiate expected system behavior from kink, disconnection, migration, occlusion and ongoing pleural leak.'],
  },
  {
    id: 'etco2-gap', name: 'PaCO₂–EtCO₂ gap', domain: 'respiratory', level: 4,
    summary: 'The arterial-to-end-tidal CO₂ difference reflects how effectively perfused alveoli contribute to exhaled gas and often widens with increasing dead space.',
    prereq: ['dead-space'], related: ['pe', 'shock'],
    vocabulary: ['capnography', 'alveolar dead space'],
    performance: ['Interpret a changing PaCO₂–EtCO₂ gap in the context of ventilation and perfusion.', 'Avoid treating end-tidal CO₂ as a fixed surrogate for arterial CO₂ in unstable physiology.'],
  },
  {
    id: 'hemoperitoneum', name: 'Hemoperitoneum on ultrasound', domain: 'imaging-monitoring', level: 3,
    summary: 'Free intraperitoneal fluid is sought in dependent spaces, but sensitivity depends on volume, timing, clot and the location of bleeding.',
    prereq: ['efast'], related: ['massive-transfusion'],
    vocabulary: ['Morison pouch', 'splenorenal recess', 'pelvic free fluid'],
    performance: ['Recognize free fluid across core FAST windows.', 'Explain why a negative examination is time-stamped and does not exclude retroperitoneal hemorrhage.'],
  },
  {
    id: 'herniation', name: 'Brain herniation physiology', domain: 'neuro', level: 4,
    summary: 'Rising intracranial pressure and compartment shifts distort brain structures, impair perfusion and can produce rapidly evolving focal and brainstem signs.',
    prereq: ['icp-cpp'], related: ['evd'],
    vocabulary: ['uncal', 'central', 'tonsillar', 'Cushing response'],
    performance: ['Recognize a herniation trajectory from examination and physiology.', 'Prioritize temporizing actions while preserving cerebral perfusion and definitive neurosurgical access.'],
  },
  {
    id: 'ptx-us', name: 'Pneumothorax ultrasound', domain: 'imaging-monitoring', level: 3,
    summary: 'Pleural ultrasound combines sliding, B-lines, M-mode patterns and lung point rather than relying on a single sign.',
    prereq: [], related: ['chest-tube', 'vent-troubleshooting'],
    vocabulary: ['lung sliding', 'lung point', 'seashore', 'barcode'],
    performance: ['Use multiple pleural signs to support or weaken the diagnosis.', 'Recognize situations where absent sliding is not pneumothorax.'],
  },
  {
    id: 'dka', name: 'Diabetic ketoacidosis physiology', domain: 'renal-metabolic', level: 3,
    summary: 'Insulin deficiency produces ketogenesis, osmotic diuresis, electrolyte shifts and a high-anion-gap acidosis whose treatment changes potassium and water distribution.',
    prereq: ['acid-base'], related: ['shock'],
    vocabulary: ['ketogenesis', 'anion gap', 'corrected sodium'],
    performance: ['Track potassium and volume physiology across treatment rather than treating glucose alone.', 'Recognize mixed acid-base disorders and treatment-related complications.'],
  },
  {
    id: 'uncertainty', name: 'Clinical uncertainty & model revision', domain: 'multisystem', level: 6,
    summary: 'Expert reasoning explicitly tracks uncertainty, contradictory data and what finding would falsify the current working model.',
    prereq: ['shock'], related: ['cognitive-bias', 'multisystem-tradeoffs'],
    vocabulary: ['calibration', 'falsification', 'diagnostic time-out'],
    performance: ['State confidence, identify disconfirming evidence and update the model when the patient fails to respond as predicted.'],
  },
  {
    id: 'multisystem-tradeoffs', name: 'Multisystem treatment tradeoffs', domain: 'multisystem', level: 5,
    summary: 'A therapy that helps one organ can worsen another; expert care weighs global benefit, reversibility and monitoring.',
    prereq: ['shock', 'ppv-hemodynamics'], related: ['uncertainty'],
    performance: ['Explain at least two competing organ effects of a proposed intervention.', 'Choose the least harmful testable strategy when the optimal answer is uncertain.'],
  },
];

export const MASTERY_BY_ID = Object.fromEntries(MASTERY.map((c) => [c.id, c])) as Record<string, MasteryConcept>;

export function missingMasteryPrereqs(id: string, mastered: Set<string>) {
  return (MASTERY_BY_ID[id]?.prereq ?? []).filter((p) => !mastered.has(p));
}
