import type { CriticalCareDomain, MasteryConcept, MasteryLevel } from './types';

export const LEVELS: { level: MasteryLevel; name: string; description: string }[] = [
  { level: 1, name: 'Language & normal physiology', description: 'Anatomy, terminology, normal values and causal relationships.' },
  { level: 2, name: 'Single-system critical illness', description: 'Recognize, explain and initially manage major critical-care syndromes.' },
  { level: 3, name: 'Organ support', description: 'Ventilation, vasoactives, transfusion, sedation, invasive monitoring and procedures.' },
  { level: 4, name: 'Advanced physiology', description: 'Predict responses using pressure, flow, gas exchange, oxygen transport, acid-base and PK/PD.' },
  { level: 5, name: 'Multisystem critical care', description: 'Balance competing organ priorities and understand treatment tradeoffs.' },
  { level: 6, name: 'Expert integration', description: 'Reason through ambiguity, uncertainty, cognitive traps, evolving physiology and imperfect evidence.' },
];

export const DOMAIN_LABELS: Record<CriticalCareDomain, string> = {
  foundations: 'Foundations',
  respiratory: 'Respiratory',
  hemodynamics: 'Hemodynamics & shock',
  cardiac: 'Cardiovascular',
  neuro: 'Neurocritical care',
  'renal-metabolic': 'Renal, endocrine & metabolic',
  infectious: 'Sepsis & infection',
  hematology: 'Hematology & coagulation',
  pharmacology: 'Pharmacology',
  'imaging-monitoring': 'Imaging & monitoring',
  procedures: 'Procedures & devices',
  multisystem: 'Multisystem integration',
  'communication-systems': 'Communication, ethics & ICU systems',
  'gi-hepatic': 'Gastrointestinal & hepatic',
  endocrine: 'Endocrine emergencies',
  toxicology: 'Critical care toxicology',
  transplant: 'Transplant & immunosuppression',
  'trauma-burns': 'Trauma & burns',
  obstetric: 'Obstetric critical care',
  'peds-neonatal': 'Pediatric & neonatal critical care',
  recovery: 'Liberation & recovery',
};

export const MASTERY: MasteryConcept[] = [
  {
    id: 'preload', name: 'Preload', domain: 'foundations', level: 1,
    summary: 'The loading conditions of a ventricle before contraction; not synonymous with a single pressure or volume.',
    prereq: [], related: ['venous-return', 'fluid-responsiveness', 'rv-failure'],
    vocabulary: ['end-diastolic volume', 'transmural pressure'],
    performance: ['Distinguish preload from CVP or fluid responsiveness.', 'Predict how changes in intrathoracic pressure alter measured filling pressures.'],
  },
  {
    id: 'venous-return', name: 'Venous return', domain: 'hemodynamics', level: 4,
    summary: 'Flow back to the right heart determined by the pressure gradient from the systemic circulation and resistance to venous return.',
    prereq: ['preload'], related: ['stressed-volume', 'rv-failure', 'ppv-hemodynamics'],
    vocabulary: ['mean systemic filling pressure', 'stressed volume', 'venous return gradient'],
    performance: ['Explain why CVP can rise while venous return falls.', 'Predict effects of vasodilation, venoconstriction and positive pressure on venous return.'],
  },
  {
    id: 'stressed-volume', name: 'Stressed vs unstressed volume', domain: 'hemodynamics', level: 4,
    summary: 'The fraction of blood volume generating elastic recoil pressure versus volume that fills the vasculature without generating pressure.',
    prereq: ['preload'], related: ['venous-return'],
    vocabulary: ['mean systemic filling pressure', 'venous capacitance'],
    performance: ['Explain how venoconstriction can recruit unstressed volume without giving fluid.'],
  },
  {
    id: 'fluid-responsiveness', name: 'Fluid responsiveness', domain: 'hemodynamics', level: 3,
    summary: 'Whether stroke volume will meaningfully increase after an increase in preload; distinct from whether fluid is indicated or safe.',
    prereq: ['preload'], related: ['venous-return', 'rv-failure'],
    vocabulary: ['dynamic assessment', 'passive leg raise'],
    performance: ['Separate responsiveness from tolerance and need.', 'Interpret dynamic tests in their physiologic context and recognize limitations.'],
  },
  {
    id: 'rv-failure', name: 'Right ventricular failure', domain: 'cardiac', level: 4,
    summary: 'Failure of a thin-walled ventricle that is highly sensitive to acute afterload, volume, perfusion pressure and ventricular interaction.',
    prereq: ['preload', 'venous-return'], related: ['pvr', 'ventricular-interdependence', 'ppv-hemodynamics', 'pe'],
    vocabulary: ['RV-PA coupling', 'septal shift', 'transmural pressure'],
    performance: ['Recognize RV shock physiology before systemic hypotension becomes profound.', 'Predict how PEEP, hypercapnia, hypoxemia, fluids and vasoactives may change RV performance.'],
  },
  {
    id: 'pvr', name: 'Pulmonary vascular resistance', domain: 'cardiac', level: 4,
    summary: 'Resistance faced by the RV, influenced by lung volume, oxygenation, CO2, pH, pulmonary vascular disease and mechanical ventilation.',
    prereq: ['preload'], related: ['rv-failure', 'ppv-hemodynamics', 'ards'],
    vocabulary: ['RV afterload', 'West zones'],
    performance: ['Explain the U-shaped relationship between lung volume and pulmonary vascular resistance.', 'Identify reversible contributors to acute RV afterload.'],
  },
  {
    id: 'ventricular-interdependence', name: 'Ventricular interdependence', domain: 'cardiac', level: 4,
    summary: 'The ventricles share a septum and constrained pericardial space, so pressure or volume loading of one changes filling and geometry of the other.',
    prereq: ['rv-failure'], related: ['tamponade', 'ppv-hemodynamics'],
    vocabulary: ['septal shift', 'pericardial constraint'],
    performance: ['Use septal position and loading conditions to explain falling LV output during RV distension.'],
  },
  {
    id: 'ppv-hemodynamics', name: 'Positive-pressure ventilation & circulation', domain: 'respiratory', level: 4,
    summary: 'Positive intrathoracic pressure changes venous return, ventricular transmural pressures and pulmonary vascular resistance.',
    prereq: ['preload'], related: ['rv-failure', 'pvr', 'peep'],
    vocabulary: ['transmural pressure', 'mean airway pressure'],
    performance: ['Predict why induction and positive pressure can precipitate hypotension.', 'Distinguish effects on RV preload, RV afterload and LV transmural afterload.'],
  },
  {
    id: 'peep', name: 'PEEP', domain: 'respiratory', level: 2,
    summary: 'Positive end-expiratory pressure used to preserve recruitment and oxygenation, with important mechanical and hemodynamic effects.',
    prereq: [], related: ['ards', 'ppv-hemodynamics', 'driving-pressure'],
    vocabulary: ['recruitability', 'intrinsic PEEP'],
    performance: ['Explain when increasing PEEP may recruit lung versus overdistend it.', 'Anticipate circulatory effects in preload-dependent or RV-failing patients.'],
  },
  {
    id: 'driving-pressure', name: 'Driving pressure', domain: 'respiratory', level: 3,
    summary: 'Plateau pressure minus total PEEP; a bedside expression of tidal strain relative to respiratory-system compliance.',
    prereq: ['peep'], related: ['ards', 'compliance', 'mechanical-power'],
    vocabulary: ['plateau pressure', 'tidal strain'],
    performance: ['Calculate and interpret driving pressure.', 'Explain why the same tidal volume can have different mechanical consequences in different lungs.'],
  },
  {
    id: 'compliance', name: 'Compliance & elastance', domain: 'foundations', level: 1,
    summary: 'Compliance describes change in volume for change in pressure; elastance is its inverse.',
    prereq: [], related: ['driving-pressure', 'ards'],
    vocabulary: ['static compliance', 'elastance'],
    performance: ['Separate resistance problems from compliance problems using peak and plateau pressures.'],
  },
  {
    id: 'ards', name: 'ARDS physiology', domain: 'respiratory', level: 3,
    summary: 'Diffuse inflammatory lung injury producing heterogeneity, shunt, low aerated lung volume and risk from ventilator-induced injury.',
    prereq: ['compliance', 'peep'], related: ['driving-pressure', 'pvr', 'oxygen-delivery'],
    vocabulary: ['baby lung', 'shunt', 'recruitability'],
    performance: ['Integrate oxygenation, mechanics, recruitability and hemodynamics rather than treating a P/F ratio in isolation.'],
  },
  {
    id: 'mechanical-power', name: 'Mechanical power', domain: 'respiratory', level: 4,
    summary: 'Energy delivered to the respiratory system over time from pressure, volume, flow and respiratory rate.',
    prereq: ['driving-pressure'], related: ['ards'],
    vocabulary: ['energy load', 'ventilator-induced lung injury'],
    performance: ['Explain how respiratory rate and flow can increase ventilator energy even when tidal volume appears acceptable.'],
  },
  {
    id: 'dead-space', name: 'Dead space', domain: 'respiratory', level: 3,
    summary: 'Ventilation that does not effectively participate in CO2 exchange, from conducting airways or ventilated but poorly perfused alveoli.',
    prereq: [], related: ['pe', 'ards', 'etco2-gap'],
    vocabulary: ['VD/VT', 'alveolar dead space'],
    performance: ['Use PaCO2–EtCO2 behavior and minute ventilation requirements to reason about changing dead space.'],
  },
  {
    id: 'oxygen-delivery', name: 'Oxygen delivery', domain: 'hemodynamics', level: 3,
    summary: 'DO2 is cardiac output multiplied by arterial oxygen content; saturation alone does not describe tissue oxygen delivery.',
    prereq: [], related: ['oxygen-extraction', 'shock', 'transfusion'],
    vocabulary: ['CaO2', 'DO2', 'VO2'],
    performance: ['Predict effects of hemoglobin, saturation and flow on oxygen delivery.', 'Explain why a normal SpO2 can coexist with inadequate DO2.'],
  },
  {
    id: 'oxygen-extraction', name: 'Oxygen extraction', domain: 'hemodynamics', level: 4,
    summary: 'The relationship between delivered and consumed oxygen reflected by venous saturation and tissue extraction.',
    prereq: ['oxygen-delivery'], related: ['shock', 'lactate'],
    vocabulary: ['O2ER', 'SvO2', 'critical DO2'],
    performance: ['Interpret low or high venous saturation in context rather than labeling it simply good or bad.'],
  },
  {
    id: 'shock', name: 'Shock phenotyping', domain: 'hemodynamics', level: 3,
    summary: 'Identify inadequate effective circulation by integrating flow, vascular tone, congestion, oxygen delivery and organ response.',
    prereq: ['oxygen-delivery'], related: ['septic-shock', 'rv-failure', 'cardiogenic-shock'],
    vocabulary: ['flow', 'tone', 'congestion', 'perfusion'],
    performance: ['Recognize mixed shock.', 'Choose an intervention that tests a physiologic hypothesis and define the response expected if that hypothesis is correct.'],
  },
  {
    id: 'lactate', name: 'Lactate physiology', domain: 'renal-metabolic', level: 3,
    summary: 'Lactate reflects production and clearance across multiple pathways and is not a direct tissue-hypoxia meter.',
    prereq: ['oxygen-delivery'], related: ['shock', 'septic-shock'],
    vocabulary: ['adrenergic glycolysis', 'clearance'],
    performance: ['Generate hypoxic and non-hypoxic explanations for elevated lactate.', 'Interpret trajectory alongside perfusion rather than in isolation.'],
  },
  {
    id: 'acid-base', name: 'Advanced acid-base reasoning', domain: 'renal-metabolic', level: 4,
    summary: 'Integrate respiratory and metabolic processes, compensation, anion gap, albumin, chloride and mixed disorders.',
    prereq: [], related: ['strong-ion', 'dka'],
    vocabulary: ['delta gap', 'expected compensation'],
    performance: ['Identify mixed disorders that a single pH label hides.', 'Connect acid-base abnormalities to the underlying physiology and treatment.'],
  },
  {
    id: 'strong-ion', name: 'Strong-ion approach', domain: 'renal-metabolic', level: 5,
    summary: 'A physicochemical framework using strong-ion difference, total weak acids and PCO2 to explain acid-base state.',
    prereq: ['acid-base'], related: [],
    vocabulary: ['SID', 'Atot'],
    performance: ['Use the framework to explain hyperchloremic acidosis and effects of albumin without treating it as a competing religion to bicarbonate-based analysis.'],
  },
  {
    id: 'icp-cpp', name: 'ICP, CPP & cerebral perfusion', domain: 'neuro', level: 3,
    summary: 'Cerebral perfusion depends on the gradient across the cerebral circulation and is influenced by pressure, venous outflow, CO2 and intracranial compliance.',
    prereq: [], related: ['herniation', 'evd'],
    vocabulary: ['CPP', 'autoregulation', 'Monro-Kellie'],
    performance: ['Predict how systemic pressure, CO2 and venous pressure affect cerebral perfusion.', 'Recognize when a normal MAP does not guarantee adequate CPP.'],
  },
  {
    id: 'evd', name: 'EVD management', domain: 'procedures', level: 3,
    summary: 'External ventricular drainage requires correct leveling, clamping during movement and interpretation of drainage and ICP.',
    prereq: ['icp-cpp'], related: ['herniation'],
    vocabulary: ['tragus', 'foramen of Monro'],
    performance: ['Explain over-drainage versus under-drainage from transducer/chamber position.', 'Mentally rehearse safe movement and re-leveling.'],
  },
  {
    id: 'arterial-line', name: 'Arterial line', domain: 'procedures', level: 3,
    summary: 'Placement, setup, leveling, zeroing, waveform interpretation and troubleshooting of invasive arterial pressure monitoring.',
    prereq: [], related: ['waveform-damping'],
    vocabulary: ['phlebostatic axis', 'dynamic response'],
    performance: ['Differentiate patient physiology from damping/resonance artifact.', 'Mentally rehearse sterile insertion and transducer setup.'],
  },
  {
    id: 'waveform-damping', name: 'Arterial waveform damping & resonance', domain: 'imaging-monitoring', level: 4,
    summary: 'The monitoring system can distort systolic and diastolic pressures while mean pressure is relatively preserved.',
    prereq: ['arterial-line'], related: [],
    vocabulary: ['square-wave test', 'natural frequency'],
    performance: ['Recognize over- and under-damped systems and troubleshoot tubing, bubbles, clot and excessive resonance.'],
  },
  {
    id: 'efast', name: 'eFAST', domain: 'imaging-monitoring', level: 3,
    summary: 'Structured point-of-care ultrasound for pericardial, intraperitoneal and pleural pathology in trauma.',
    prereq: [], related: ['ptx-us', 'hemoperitoneum'],
    vocabulary: ['Morison pouch', 'splenorenal', 'lung sliding'],
    performance: ['Acquire and orient the core windows.', 'Recognize free fluid and common false positives/negatives while integrating the clinical context.'],
  },
  {
    id: 'transfusion', name: 'Blood product initiation & monitoring', domain: 'hematology', level: 3,
    summary: 'Safe preparation, verification, administration, monitoring and recognition of transfusion complications.',
    prereq: ['oxygen-delivery'], related: ['massive-transfusion', 'coagulopathy'],
    vocabulary: ['component therapy', 'transfusion reaction'],
    performance: ['Mentally rehearse the verification-to-monitoring sequence.', 'Recognize early signs that require stopping and reassessment per local policy.'],
  },
  {
    id: 'push-dose-pressor', name: 'Push-dose vasopressor workflow', domain: 'pharmacology', level: 3,
    summary: 'A high-risk, short-duration bridge that demands concentration verification, labeling, closed-loop communication and continuous reassessment.',
    prereq: ['shock'], related: ['vasopressors', 'medication-safety'],
    vocabulary: ['concentration', 'dose-response', 'extravasation'],
    performance: ['Rehearse safe preparation and independent verification without relying on memory alone.', 'Define the physiologic response and adverse response you are watching for.'],
  },
  {
    id: 'medication-safety', name: 'High-risk medication safety', domain: 'pharmacology', level: 2,
    summary: 'Use standardized concentration, labeling, independent verification, closed-loop communication and context checks for high-risk drugs.',
    prereq: [], related: ['push-dose-pressor'],
    performance: ['Catch concentration and route errors before administration.', 'Use local protocol and pharmacy-standard concentrations rather than improvised memory.'],
  },
  {
    id: 'chest-tube', name: 'Pleural drain / chest tube', domain: 'procedures', level: 3,
    summary: 'Indication, anatomy, insertion concepts, system setup, confirmation and complication recognition for pleural drainage.',
    prereq: [], related: ['ptx-us', 'drain-troubleshooting'],
    performance: ['Rehearse anatomical orientation and sterile setup.', 'Recognize a nonfunctioning drain by patient physiology and system findings.'],
  },
  {
    id: 'central-line', name: 'Ultrasound-guided central venous access', domain: 'procedures', level: 3,
    summary: 'Safe venous access requires anatomy, real-time tip awareness, vessel confirmation, wire control, sterile technique and complication recognition.',
    prereq: [], related: ['medication-safety', 'shock'],
    vocabulary: ['Seldinger technique', 'compressibility', 'guidewire'],
    performance: ['Distinguish vein from artery using more than color.', 'Rehearse seeing the wire in the intended vessel before dilation and keeping control of the wire throughout.'],
  },
  {
    id: 'io-access', name: 'Intraosseous access', domain: 'procedures', level: 2,
    summary: 'Rapid vascular access through the medullary space when conventional access is delayed or unreliable.',
    prereq: [], related: ['shock', 'medication-safety'],
    vocabulary: ['cortex', 'medullary space', 'extravasation'],
    performance: ['Identify the correct landmark for the chosen approved site and device.', 'Confirm functional placement and recognize extravasation or compartment-risk signs.'],
  },
  {
    id: 'vent-troubleshooting', name: 'Ventilator emergency troubleshooting', domain: 'respiratory', level: 3,
    summary: 'A structured patient-to-device approach to acute hypoxemia, high pressure, low pressure, dyssynchrony and post-intubation deterioration.',
    prereq: ['compliance'], related: ['dead-space', 'peep', 'ppv-hemodynamics'],
    vocabulary: ['DOPES', 'peak pressure', 'plateau pressure', 'auto-PEEP'],
    performance: ['Separate resistance, compliance, circuit and patient problems using waveforms and bedside examination.', 'Prioritize oxygenation and manual ventilation when the device or circuit cannot be trusted.'],
  },
  {
    id: 'massive-transfusion', name: 'Massive transfusion & hemorrhagic resuscitation', domain: 'hematology', level: 4,
    summary: 'Hemorrhagic resuscitation integrates source control, balanced component replacement, calcium, temperature, coagulation and perfusion.',
    prereq: ['transfusion', 'shock'], related: ['coagulopathy', 'oxygen-delivery'],
    vocabulary: ['MTP', 'fibrinogen', 'ionized calcium', 'lethal triad'],
    performance: ['Run the resuscitation as a system rather than as isolated blood-unit administration.', 'Recognize dilutional/coagulopathic, hypocalcemic and hypothermic deterioration early.'],
  },
  {
    id: 'source-control', name: 'Source control', domain: 'infectious', level: 3,
    summary: 'Definitive management of infected material, devitalized tissue or an infected device can be as important as antimicrobial therapy.',
    prereq: [], related: ['septic-shock', 'antimicrobial-pkpd'],
    vocabulary: ['drainage', 'debridement', 'device removal'],
    performance: ['Identify when antibiotics alone are unlikely to succeed.', 'Escalate procedural or surgical source control as part of the resuscitation plan.'],
  },
  {
    id: 'antimicrobial-pkpd', name: 'Antimicrobial PK/PD in critical illness', domain: 'infectious', level: 4,
    summary: 'Critical illness changes volume of distribution, clearance and target attainment, so dose strategy must match drug and patient physiology.',
    prereq: [], related: ['source-control', 'crrt'],
    vocabulary: ['time above MIC', 'AUC/MIC', 'augmented renal clearance'],
    performance: ['Explain why standard dosing can underdose a shocked or hyperdynamic patient.', 'Integrate renal support and changing clearance into antimicrobial strategy.'],
  },
  {
    id: 'crrt', name: 'CRRT physiology & prescription literacy', domain: 'renal-metabolic', level: 4,
    summary: 'Continuous renal replacement uses diffusion and/or convection to manage solute, acid-base and fluid balance in unstable patients.',
    prereq: ['acid-base'], related: ['antimicrobial-pkpd', 'shock'],
    vocabulary: ['effluent dose', 'CVVH', 'CVVHD', 'CVVHDF', 'filtration fraction'],
    performance: ['Explain diffusion versus convection and net ultrafiltration.', 'Recognize how circuit, anticoagulation and prescribed versus delivered dose change therapy.'],
  },
  {
    id: 'pa-catheter', name: 'Pulmonary artery catheter interpretation', domain: 'imaging-monitoring', level: 5,
    summary: 'A PA catheter is useful only when waveforms, zero/level, thermodilution assumptions and the clinical model are integrated correctly.',
    prereq: ['arterial-line', 'rv-failure'], related: ['oxygen-extraction', 'shock'],
    vocabulary: ['RAP', 'PAP', 'PAOP', 'thermodilution', 'PVR', 'SVR'],
    performance: ['Recognize chamber waveforms during insertion and interpret pressures in physiologic context.', 'Use serial values to test a hemodynamic model rather than treating targets in isolation.'],
  },
  {
    id: 'ecmo', name: 'ECMO circuit & physiology literacy', domain: 'multisystem', level: 5,
    summary: 'Extracorporeal support changes preload, afterload, gas exchange and oxygen delivery through a circuit whose configuration determines what it can support.',
    prereq: ['oxygen-delivery', 'shock'], related: ['rv-failure', 'ards'],
    vocabulary: ['VV ECMO', 'VA ECMO', 'sweep gas', 'recirculation', 'differential hypoxemia'],
    performance: ['Distinguish VV from VA support goals and limitations.', 'Reason from circuit flow, native heart/lung function and cannula position to common failure patterns.'],
  },
  {
    id: 'sedation-analgesia', name: 'ICU analgesia, sedation & synchrony', domain: 'pharmacology', level: 3,
    summary: 'Sedation strategy balances analgesia, comfort, ventilator synchrony, neurologic assessment, hemodynamics and delirium risk.',
    prereq: [], related: ['delirium', 'vent-troubleshooting'],
    vocabulary: ['analgosedation', 'RASS', 'daily awakening'],
    performance: ['Separate pain, anxiety, delirium and dyssynchrony before simply deepening sedation.', 'Predict major hemodynamic and respiratory tradeoffs of sedative strategies.'],
  },
  {
    id: 'delirium', name: 'Delirium, sleep & mobility', domain: 'communication-systems', level: 3,
    summary: 'Brain dysfunction in critical illness is shaped by disease, drugs, sleep disruption, immobility and environment.',
    prereq: [], related: ['sedation-analgesia'],
    vocabulary: ['CAM-ICU', 'ABCDE/ABCDEF bundle'],
    performance: ['Recognize modifiable drivers of delirium.', 'Integrate sedation reduction, sleep, mobility and family engagement into daily ICU care.'],
  },
  {
    id: 'goals-care', name: 'Goals of care & prognostic communication', domain: 'communication-systems', level: 5,
    summary: 'High-quality critical care includes eliciting values, communicating uncertainty and aligning burdensome treatments with realistic goals.',
    prereq: ['uncertainty'], related: [],
    vocabulary: ['surrogate decision-maker', 'time-limited trial', 'best case / worst case'],
    performance: ['Explain prognosis without false precision.', 'Frame a time-limited trial with explicit goals and reassessment criteria.'],
  },
  {
    id: 'septic-shock', name: 'Septic shock physiology', domain: 'infectious', level: 3,
    summary: 'Distributive shock with dynamic changes in vascular tone, venous capacitance, myocardial performance, microcirculation and oxygen extraction.',
    prereq: ['shock'], related: ['source-control', 'lactate', 'vasopressors'],
    vocabulary: ['vasoplegia', 'microcirculation', 'distributive shock'],
    performance: ['Recognize when septic shock is not simply low SVR.', 'Integrate source control, flow, tone, cardiac function and perfusion response over time.'],
  },
  {
    id: 'cardiogenic-shock', name: 'Cardiogenic shock', domain: 'cardiac', level: 4,
    summary: 'Pump failure where restoring perfusion must be balanced against congestion, myocardial oxygen demand, coronary perfusion and mechanical complications.',
    prereq: ['shock'], related: ['rv-failure', 'vasopressors', 'pa-catheter'],
    vocabulary: ['cardiac power output', 'congestion', 'inotropy'],
    performance: ['Phenotype left-, right- and biventricular pump failure.', 'Choose support based on pressure, flow, congestion and the cause of pump failure.'],
  },
  {
    id: 'pe', name: 'Pulmonary embolism physiology', domain: 'cardiac', level: 3,
    summary: 'Acute pulmonary vascular obstruction can abruptly raise RV afterload, impair LV filling and cause shock despite structurally normal lungs.',
    prereq: ['pvr'], related: ['rv-failure', 'dead-space'],
    vocabulary: ['obstructive shock', 'RV strain', 'dead space'],
    performance: ['Connect clot burden to RV pressure load, septal interaction and gas-exchange findings.', 'Recognize why intubation and excessive positive pressure may destabilize severe PE.'],
  },
  {
    id: 'tamponade', name: 'Cardiac tamponade physiology', domain: 'cardiac', level: 3,
    summary: 'Pericardial pressure constrains chamber filling, couples the ventricles and makes venous return highly sensitive to pressure gradients.',
    prereq: ['preload'], related: ['ventricular-interdependence', 'shock'],
    vocabulary: ['pericardial pressure', 'respiratory variation', 'diastolic collapse'],
    performance: ['Explain tamponade as a filling-pressure problem rather than a checklist of classic signs.', 'Predict effects of positive pressure and volume changes on a preload-limited circulation.'],
  },
  {
    id: 'vasopressors', name: 'Vasopressor & inotrope physiology', domain: 'pharmacology', level: 3,
    summary: 'Vasoactive drugs change arterial tone, venous tone, heart rate, contractility and regional flow; the desired effect depends on the shock model.',
    prereq: ['shock'], related: ['push-dose-pressor', 'septic-shock', 'cardiogenic-shock'],
    vocabulary: ['alpha-1', 'beta-1', 'inotropy', 'chronotropy', 'venoconstriction'],
    performance: ['Choose a vasoactive strategy from the physiologic deficit rather than blood pressure alone.', 'State the expected benefit, predictable tradeoff and reassessment endpoint.'],
  },
  {
    id: 'coagulopathy', name: 'Critical-illness coagulopathy', domain: 'hematology', level: 4,
    summary: 'Bleeding and thrombosis reflect platelets, fibrinogen, coagulation factors, fibrinolysis, temperature, calcium, dilution and disease-specific pathways.',
    prereq: ['transfusion'], related: ['massive-transfusion'],
    vocabulary: ['fibrinolysis', 'fibrinogen', 'viscoelastic testing'],
    performance: ['Reason from the failing component of clot formation rather than treating INR alone.', 'Anticipate temperature, calcium and dilution effects during hemorrhagic resuscitation.'],
  },
  {
    id: 'cognitive-bias', name: 'Cognitive bias & diagnostic error', domain: 'multisystem', level: 6,
    summary: 'Expert reasoning uses deliberate checks against anchoring, premature closure, confirmation bias and overconfidence while still making timely decisions.',
    prereq: ['uncertainty'], related: [],
    vocabulary: ['anchoring', 'premature closure', 'diagnostic time-out'],
    performance: ['Name the evidence that does not fit the favored diagnosis.', 'Deliberately generate an alternative model when the patient fails to respond as predicted.'],
  },
  {
    id: 'drain-troubleshooting', name: 'Pleural drain troubleshooting', domain: 'procedures', level: 3,
    summary: 'A pleural drain must be assessed as patient + tube + connections + drainage system rather than as an isolated device.',
    prereq: ['chest-tube'], related: ['ptx-us', 'vent-troubleshooting'],
    vocabulary: ['water seal', 'tidaling', 'air leak'],
    performance: ['Trace a failing drain from the patient outward.', 'Differentiate expected system behavior from kink, disconnection, migration, occlusion and ongoing pleural leak.'],
  },
  {
    id: 'etco2-gap', name: 'PaCO₂–EtCO₂ gap', domain: 'respiratory', level: 4,
    summary: 'The arterial-to-end-tidal CO₂ difference reflects how effectively perfused alveoli contribute to exhaled gas and often widens with increasing dead space.',
    prereq: ['dead-space'], related: ['pe', 'shock'],
    vocabulary: ['capnography', 'alveolar dead space'],
    performance: ['Interpret a changing PaCO₂–EtCO₂ gap in the context of ventilation and perfusion.', 'Avoid treating end-tidal CO₂ as a fixed surrogate for arterial CO₂ in unstable physiology.'],
  },
  {
    id: 'hemoperitoneum', name: 'Hemoperitoneum on ultrasound', domain: 'imaging-monitoring', level: 3,
    summary: 'Free intraperitoneal fluid is sought in dependent spaces, but sensitivity depends on volume, timing, clot and the location of bleeding.',
    prereq: ['efast'], related: ['massive-transfusion'],
    vocabulary: ['Morison pouch', 'splenorenal recess', 'pelvic free fluid'],
    performance: ['Recognize free fluid across core FAST windows.', 'Explain why a negative examination is time-stamped and does not exclude retroperitoneal hemorrhage.'],
  },
  {
    id: 'herniation', name: 'Brain herniation physiology', domain: 'neuro', level: 4,
    summary: 'Rising intracranial pressure and compartment shifts distort brain structures, impair perfusion and can produce rapidly evolving focal and brainstem signs.',
    prereq: ['icp-cpp'], related: ['evd'],
    vocabulary: ['uncal', 'central', 'tonsillar', 'Cushing response'],
    performance: ['Recognize a herniation trajectory from examination and physiology.', 'Prioritize temporizing actions while preserving cerebral perfusion and definitive neurosurgical access.'],
  },
  {
    id: 'ptx-us', name: 'Pneumothorax ultrasound', domain: 'imaging-monitoring', level: 3,
    summary: 'Pleural ultrasound combines sliding, B-lines, M-mode patterns and lung point rather than relying on a single sign.',
    prereq: [], related: ['chest-tube', 'vent-troubleshooting'],
    vocabulary: ['lung sliding', 'lung point', 'seashore', 'barcode'],
    performance: ['Use multiple pleural signs to support or weaken the diagnosis.', 'Recognize situations where absent sliding is not pneumothorax.'],
  },
  {
    id: 'dka', name: 'Diabetic ketoacidosis physiology', domain: 'renal-metabolic', level: 3,
    summary: 'Insulin deficiency produces ketogenesis, osmotic diuresis, electrolyte shifts and a high-anion-gap acidosis whose treatment changes potassium and water distribution.',
    prereq: ['acid-base'], related: ['shock'],
    vocabulary: ['ketogenesis', 'anion gap', 'corrected sodium'],
    performance: ['Track potassium and volume physiology across treatment rather than treating glucose alone.', 'Recognize mixed acid-base disorders and treatment-related complications.'],
  },
  {
    id: 'acute-liver-failure', name: 'Acute liver failure', domain: 'gi-hepatic', level: 4,
    summary: 'Acute hepatic failure couples coagulopathy, ammonia handling, cerebral edema risk, hypoglycemia, vasodilation and multiorgan dysfunction.',
    prereq: ['coagulopathy', 'icp-cpp'], related: ['hepatic-encephalopathy', 'crrt'],
    vocabulary: ['ammonia', 'synthetic failure', 'cerebral edema'],
    performance: ['Recognize the physiology that makes acute liver failure different from stable chronic cirrhosis.', 'Prioritize neuroprotection, glucose control, hemodynamics and early transplant-center escalation.'],
  },
  {
    id: 'hepatic-encephalopathy', name: 'Hepatic encephalopathy', domain: 'gi-hepatic', level: 3,
    summary: 'Neurocognitive dysfunction from hepatic failure reflects ammonia and other mechanisms, with severity ranging from subtle change to coma.',
    prereq: [], related: ['acute-liver-failure'],
    vocabulary: ['asterixis', 'ammonia', 'precipitating factor'],
    performance: ['Look for reversible precipitants instead of attributing all altered mental status to ammonia.', 'Separate chronic encephalopathy from acute cerebral-edema risk.'],
  },
  {
    id: 'gi-hemorrhage', name: 'Severe GI hemorrhage', domain: 'gi-hepatic', level: 3,
    summary: 'Upper and lower GI bleeding require simultaneous hemorrhagic resuscitation, airway judgment, coagulopathy assessment and definitive source control.',
    prereq: ['massive-transfusion'], related: ['coagulopathy', 'source-control'],
    vocabulary: ['variceal', 'nonvariceal', 'endoscopy'],
    performance: ['Run resuscitation and definitive-control planning in parallel.', 'Recognize when airway, portal-hypertension or anticoagulation issues change the strategy.'],
  },
  {
    id: 'acute-pancreatitis', name: 'Severe acute pancreatitis', domain: 'gi-hepatic', level: 4,
    summary: 'Pancreatitis can produce capillary leak, third spacing, respiratory failure, shock, renal injury and later infectious complications.',
    prereq: ['shock'], related: ['ards', 'crrt', 'nutrition'],
    vocabulary: ['necrosis', 'third spacing', 'organ failure'],
    performance: ['Treat pancreatitis as a multisystem inflammatory illness rather than an isolated abdominal diagnosis.', 'Balance fluids, respiratory support, nutrition and infection decisions over time.'],
  },
  {
    id: 'nutrition', name: 'ICU nutrition & refeeding risk', domain: 'gi-hepatic', level: 3,
    summary: 'Nutrition in critical illness is a metabolic therapy with timing, route, protein, glycemic and electrolyte consequences.',
    prereq: [], related: ['refeeding', 'recovery-weakness'],
    vocabulary: ['enteral nutrition', 'protein target', 'caloric debt'],
    performance: ['Explain why early enteral nutrition is often preferred when feasible.', 'Recognize when feeding strategy, aspiration risk or hemodynamic instability changes the plan.'],
  },
  {
    id: 'refeeding', name: 'Refeeding syndrome', domain: 'endocrine', level: 3,
    summary: 'Insulin-driven intracellular shifts after refeeding can rapidly lower phosphate, potassium and magnesium and precipitate cardiopulmonary or neurologic deterioration.',
    prereq: ['nutrition'], related: [],
    vocabulary: ['phosphate', 'thiamine', 'intracellular shift'],
    performance: ['Identify high-risk patients before feeding escalates.', 'Connect electrolyte shifts to respiratory, cardiac and neurologic failure.'],
  },
  {
    id: 'hhs', name: 'Hyperosmolar hyperglycemic state', domain: 'endocrine', level: 3,
    summary: 'HHS combines profound free-water deficit and hyperosmolality with less ketogenesis than DKA, creating distinct neurologic and correction-rate concerns.',
    prereq: [], related: ['dka'],
    vocabulary: ['effective osmolality', 'free-water deficit', 'corrected sodium'],
    performance: ['Distinguish HHS physiology from DKA rather than treating both as hyperglycemia.', 'Track sodium and osmolality during therapy to avoid overly rapid shifts.'],
  },
  {
    id: 'adrenal-crisis', name: 'Adrenal crisis', domain: 'endocrine', level: 3,
    summary: 'Cortisol deficiency can cause refractory hypotension, hyponatremia, hyperkalemia, hypoglycemia and shock under stress.',
    prereq: ['shock'], related: ['vasopressors'],
    vocabulary: ['cortisol', 'mineralocorticoid', 'stress dose'],
    performance: ['Recognize adrenal crisis in otherwise unexplained refractory shock.', 'Understand why steroid replacement can rapidly change vascular responsiveness.'],
  },
  {
    id: 'thyroid-storm', name: 'Thyroid storm', domain: 'endocrine', level: 4,
    summary: 'Extreme thyrotoxicosis drives hypermetabolism, adrenergic symptoms, arrhythmia, heart failure, fever and CNS dysfunction.',
    prereq: [], related: ['cardiogenic-shock'],
    vocabulary: ['thyrotoxicosis', 'hyperadrenergic', 'high-output failure'],
    performance: ['Recognize multisystem decompensation rather than relying on a single thyroid value.', 'Sequence therapies around adrenergic control, hormone synthesis/release and precipitant treatment.'],
  },
  {
    id: 'myxedema-coma', name: 'Myxedema coma', domain: 'endocrine', level: 4,
    summary: 'Severe hypothyroidism can produce hypothermia, bradycardia, hypoventilation, hyponatremia, hypotension and altered consciousness.',
    prereq: [], related: ['vent-troubleshooting'],
    vocabulary: ['hypothyroidism', 'hypoventilation', 'adrenal coverage'],
    performance: ['Recognize the syndrome despite nonspecific presentation.', 'Anticipate airway, temperature, sodium and adrenal considerations during treatment.'],
  },
  {
    id: 'toxic-alcohols', name: 'Toxic alcohols', domain: 'toxicology', level: 4,
    summary: 'Methanol and ethylene glycol toxicity evolve through parent-compound intoxication, toxic metabolites, anion-gap acidosis and end-organ injury.',
    prereq: ['acid-base'], related: ['crrt'],
    vocabulary: ['osmolar gap', 'anion gap', 'formate', 'oxalate'],
    performance: ['Use timing, gaps and organ findings together rather than waiting for a confirmatory level.', 'Understand the roles of alcohol dehydrogenase blockade and extracorporeal removal.'],
  },
  {
    id: 'salicylate-toxicity', name: 'Salicylate toxicity', domain: 'toxicology', level: 4,
    summary: 'Salicylates create respiratory alkalosis plus metabolic acidosis, uncouple oxidative phosphorylation and become more CNS-penetrant as pH falls.',
    prereq: ['acid-base'], related: ['crrt'],
    vocabulary: ['alkalinization', 'mixed disorder', 'ion trapping'],
    performance: ['Recognize why a near-normal pH can hide severe mixed acid-base disease.', 'Explain why airway management can be hazardous if compensatory ventilation is lost.'],
  },
  {
    id: 'bb-ccb-toxicity', name: 'Beta-blocker & calcium-channel blocker toxicity', domain: 'toxicology', level: 4,
    summary: 'These overdoses can produce profound bradycardia, vasodilation and myocardial depression through different receptor and metabolic mechanisms.',
    prereq: ['shock'], related: ['vasopressors'],
    vocabulary: ['high-dose insulin', 'calcium', 'chronotropy'],
    performance: ['Differentiate dominant pump versus vasodilatory physiology.', 'Understand why therapy often requires multiple simultaneous mechanisms rather than one antidote.'],
  },
  {
    id: 'sodium-channel-toxicity', name: 'Sodium-channel blockade', domain: 'toxicology', level: 4,
    summary: 'Fast sodium-channel blockade slows depolarization and can widen QRS, cause ventricular dysrhythmia, hypotension and seizures.',
    prereq: [], related: ['acid-base'],
    vocabulary: ['QRS widening', 'terminal R', 'alkalinization'],
    performance: ['Recognize ECG evidence of sodium-channel toxicity.', 'Connect alkalinization and sodium loading to the electrophysiologic mechanism.'],
  },
  {
    id: 'transplant-physiology', name: 'Transplant critical-care physiology', domain: 'transplant', level: 4,
    summary: 'Transplant recipients combine altered anatomy/physiology, immunosuppression, unusual infection risk, rejection and drug-interaction problems.',
    prereq: ['antimicrobial-pkpd'], related: ['immunosuppression', 'source-control'],
    vocabulary: ['rejection', 'opportunistic infection', 'allograft'],
    performance: ['Build a broader differential for shock, hypoxemia and organ dysfunction in transplant recipients.', 'Avoid stopping immunosuppression or attributing graft dysfunction to rejection without context.'],
  },
  {
    id: 'immunosuppression', name: 'Immunosuppression & opportunistic infection', domain: 'transplant', level: 4,
    summary: 'Immune deficits and immunosuppressive drugs reshape infection timing, presentation, diagnostic yield and antimicrobial strategy.',
    prereq: ['antimicrobial-pkpd'], related: ['transplant-physiology'],
    vocabulary: ['neutropenia', 'calcineurin inhibitor', 'opportunistic infection'],
    performance: ['Match likely pathogens to the host immune defect and time course.', 'Recognize major drug-toxicity and interaction risks during critical illness.'],
  },
  {
    id: 'burn-shock', name: 'Burn shock & resuscitation', domain: 'trauma-burns', level: 4,
    summary: 'Major burns create capillary leak, evaporative loss, inflammatory shock and evolving fluid requirements that cannot be managed by formula alone.',
    prereq: ['shock'], related: ['inhalation-injury', 'coagulopathy'],
    vocabulary: ['TBSA', 'burn shock', 'urine output'],
    performance: ['Use formulas only as a starting estimate and titrate to physiologic response.', 'Recognize both under-resuscitation and fluid creep.'],
  },
  {
    id: 'inhalation-injury', name: 'Inhalation injury', domain: 'trauma-burns', level: 3,
    summary: 'Thermal upper-airway injury, chemical tracheobronchial injury and systemic toxic exposure are distinct problems that can coexist after fire.',
    prereq: [], related: ['burn-shock', 'toxicology'],
    vocabulary: ['carbon monoxide', 'cyanide', 'bronchoscopy'],
    performance: ['Separate impending airway edema from lower-airway injury and systemic toxic exposure.', 'Recognize when early airway control may be safer than waiting for visible obstruction.'],
  },
  {
    id: 'traumatic-brain-injury', name: 'Severe traumatic brain injury', domain: 'trauma-burns', level: 4,
    summary: 'TBI management centers on preventing secondary brain injury by protecting oxygenation, perfusion and intracranial dynamics.',
    prereq: ['icp-cpp'], related: ['herniation', 'coagulopathy'],
    vocabulary: ['secondary injury', 'CPP', 'intracranial compliance'],
    performance: ['Prioritize avoidance of hypoxemia and hypotension.', 'Integrate ICP, CPP, ventilation and extracranial injuries without creating competing harm.'],
  },
  {
    id: 'ob-hemorrhage', name: 'Obstetric hemorrhage', domain: 'obstetric', level: 4,
    summary: 'Major obstetric bleeding couples rapidly changing uterine source control with transfusion, coagulopathy and pregnancy-specific physiology.',
    prereq: ['massive-transfusion'], related: ['coagulopathy'],
    vocabulary: ['uterine atony', 'fibrinogen', 'peripartum'],
    performance: ['Recognize that apparently preserved blood pressure may coexist with major blood loss.', 'Run uterotonic/source-control strategy and hemorrhagic resuscitation in parallel.'],
  },
  {
    id: 'preeclampsia-eclampsia', name: 'Preeclampsia & eclampsia', domain: 'obstetric', level: 4,
    summary: 'Hypertensive disease of pregnancy can involve cerebral, hepatic, renal, hematologic and placental dysfunction with seizure and pulmonary-edema risk.',
    prereq: [], related: ['icp-cpp', 'coagulopathy'],
    vocabulary: ['severe features', 'magnesium', 'HELLP'],
    performance: ['Recognize severe features across organ systems.', 'Balance blood-pressure control, seizure prevention and definitive obstetric management.'],
  },
  {
    id: 'peripartum-cardiomyopathy', name: 'Peripartum cardiomyopathy', domain: 'obstetric', level: 4,
    summary: 'Pregnancy-associated systolic heart failure can present from late pregnancy into the postpartum period and may mimic normal peripartum symptoms.',
    prereq: ['cardiogenic-shock'], related: ['rv-failure'],
    vocabulary: ['postpartum', 'systolic failure', 'pulmonary edema'],
    performance: ['Recognize decompensated heart failure in the peripartum period.', 'Account for pregnancy/postpartum medication and hemodynamic considerations.'],
  },
  {
    id: 'pediatric-shock', name: 'Pediatric shock physiology', domain: 'peds-neonatal', level: 3,
    summary: 'Children often preserve blood pressure until late while compensating with tachycardia and vasoconstriction; age and size alter interpretation and therapy.',
    prereq: ['shock'], related: ['oxygen-delivery'],
    vocabulary: ['compensated shock', 'age-adjusted', 'weight-based'],
    performance: ['Recognize compensated pediatric shock before hypotension.', 'Use age, size and disease-specific physiology rather than scaled-down adult assumptions.'],
  },
  {
    id: 'neonatal-transition', name: 'Neonatal cardiopulmonary transition', domain: 'peds-neonatal', level: 4,
    summary: 'Birth requires a rapid shift from placental to pulmonary gas exchange with falling PVR and changing shunt flow through the ductus and foramen ovale.',
    prereq: ['pvr'], related: ['congenital-heart'],
    vocabulary: ['ductus arteriosus', 'foramen ovale', 'persistent pulmonary hypertension'],
    performance: ['Explain normal transition from fetal to neonatal circulation.', 'Recognize how failed transition can produce hypoxemia and right-to-left shunting.'],
  },
  {
    id: 'congenital-heart', name: 'Critical congenital heart disease physiology', domain: 'peds-neonatal', level: 5,
    summary: 'Critical congenital lesions are best understood by whether systemic or pulmonary blood flow depends on shunts, mixing or ductal patency.',
    prereq: ['neonatal-transition'], related: ['oxygen-delivery'],
    vocabulary: ['ductal-dependent', 'mixing lesion', 'Qp:Qs'],
    performance: ['Reason from circulation topology rather than memorizing lesion names.', 'Predict how oxygen, ventilation and vascular resistance can alter shunt balance.'],
  },
  {
    id: 'pediatric-airway', name: 'Pediatric airway & ventilation', domain: 'peds-neonatal', level: 3,
    summary: 'Smaller airways, higher metabolic demand and lower reserve make pediatric respiratory deterioration faster and equipment sizing more consequential.',
    prereq: ['vent-troubleshooting'], related: [],
    vocabulary: ['airway resistance', 'dead space', 'uncuffed/cuffed'],
    performance: ['Anticipate rapid desaturation and pressure consequences in small airways.', 'Use age/size-appropriate airway and ventilation strategy.'],
  },
  {
    id: 'vent-weaning', name: 'Liberation from mechanical ventilation', domain: 'recovery', level: 4,
    summary: 'Liberation requires separating readiness, spontaneous breathing performance, airway protection and post-extubation risk.',
    prereq: ['vent-troubleshooting'], related: ['sedation-analgesia', 'recovery-weakness'],
    vocabulary: ['SBT', 'RSBI', 'airway protection'],
    performance: ['Distinguish failure of respiratory mechanics from cardiac, neurologic or airway causes of failed liberation.', 'Plan extubation support based on risk rather than a single breathing-trial number.'],
  },
  {
    id: 'recovery-weakness', name: 'ICU-acquired weakness & recovery', domain: 'recovery', level: 3,
    summary: 'Critical illness, immobility, inflammation, sedation and organ failure can produce profound weakness and long-term functional loss.',
    prereq: ['delirium'], related: ['nutrition', 'vent-weaning'],
    vocabulary: ['critical illness myopathy', 'critical illness neuropathy', 'PICS'],
    performance: ['Recognize weakness as an ICU outcome, not merely a discharge problem.', 'Connect sedation, mobility, nutrition and ventilator liberation to recovery.'],
  },
  {
    id: 'iabp', name: 'Intra-aortic balloon pump physiology', domain: 'cardiac', level: 4,
    summary: 'IABP timing uses diastolic augmentation and presystolic deflation to alter coronary perfusion and LV afterload.',
    prereq: ['cardiogenic-shock', 'arterial-line'], related: ['mechanical-circulatory-support'],
    vocabulary: ['diastolic augmentation', 'deflation', 'trigger'],
    performance: ['Identify correct inflation/deflation timing from the arterial waveform.', 'Predict the hemodynamic consequence of early or late timing errors.'],
  },
  {
    id: 'mechanical-circulatory-support', name: 'Mechanical circulatory support', domain: 'cardiac', level: 5,
    summary: 'Temporary circulatory support devices unload or bypass different parts of the circulation and must be matched to the failing ventricle and oxygenation problem.',
    prereq: ['cardiogenic-shock'], related: ['iabp', 'ecmo'],
    vocabulary: ['LV unloading', 'VA ECMO', 'axial flow'],
    performance: ['Match support strategy to LV, RV, biventricular or cardiopulmonary failure.', 'Anticipate loading, limb, hemolysis and device-interaction complications.'],
  },
  {
    id: 'status-epilepticus', name: 'Status epilepticus', domain: 'neuro', level: 4,
    summary: 'Ongoing seizures become a time-dependent systemic and neurologic emergency requiring rapid recognition, medication sequencing and search for cause.',
    prereq: [], related: ['icp-cpp'],
    vocabulary: ['convulsive', 'nonconvulsive', 'EEG'],
    performance: ['Treat persistent seizure activity as a trajectory rather than isolated episodes.', 'Recognize when ongoing altered mental status requires EEG evaluation for nonconvulsive status.'],
  },
  {
    id: 'brain-death-neuroprognosis', name: 'Neuroprognostication & death by neurologic criteria', domain: 'communication-systems', level: 5,
    summary: 'Neuroprognostication requires timing, confounder control and multimodal evidence; death by neurologic criteria is a separate formal determination process.',
    prereq: ['uncertainty'], related: ['goals-care'],
    vocabulary: ['confounder', 'multimodal prognosis', 'apnea test'],
    performance: ['Separate prognosis from formal death determination.', 'Avoid premature certainty in the presence of sedation, hypothermia, metabolic confounding or insufficient observation time.'],
  },
  {
    id: 'ultrasound-piv', name: 'Ultrasound-guided peripheral IV', domain: 'procedures', level: 2,
    summary: 'Ultrasound-guided peripheral access combines vessel selection, needle-tip tracking, catheter length and post-placement assessment.',
    prereq: [], related: ['central-line'],
    vocabulary: ['short axis', 'long axis', 'tip tracking', 'catheter-to-vein ratio'],
    performance: ['Choose an appropriate target by depth, diameter and course.', 'Keep the true needle tip accounted for and anticipate failure from a catheter that is too short for the vessel depth.'],
  },
  {
    id: 'airway-rsi', name: 'RSI preparation & peri-intubation physiology', domain: 'procedures', level: 4,
    summary: 'RSI is a physiologic resuscitation that includes preoxygenation, hemodynamic preparation, drug strategy, positioning, backup planning and post-intubation care.',
    prereq: ['oxygen-delivery','ppv-hemodynamics'], related: ['sedation-analgesia','vent-troubleshooting','rv-failure'],
    vocabulary: ['preoxygenation', 'apneic oxygenation', 'first-pass success', 'peri-intubation arrest'],
    performance: ['Identify physiologically difficult airways before induction.', 'Build an airway plan that includes hemodynamics and the first five minutes after tube placement.'],
  },
  {
    id: 'post-intubation', name: 'Post-intubation stabilization', domain: 'procedures', level: 3,
    summary: 'Tube confirmation is the beginning of post-intubation care: oxygenation, ventilation, hemodynamics, sedation, ventilator setup and diagnosis must be reassessed together.',
    prereq: ['airway-rsi'], related: ['vent-troubleshooting','sedation-analgesia','ppv-hemodynamics'],
    vocabulary: ['waveform capnography', 'post-intubation hypotension', 'analgosedation'],
    performance: ['Run a reproducible first-five-minutes stabilization sequence.', 'Treat hypotension or hypoxemia as a physiology problem rather than simply changing one ventilator or medication setting.'],
  },
  {
    id: 'uncertainty', name: 'Clinical uncertainty & model revision', domain: 'multisystem', level: 6,
    summary: 'Expert reasoning explicitly tracks uncertainty, contradictory data and what finding would falsify the current working model.',
    prereq: ['shock'], related: ['cognitive-bias', 'multisystem-tradeoffs'],
    vocabulary: ['calibration', 'falsification', 'diagnostic time-out'],
    performance: ['State confidence, identify disconfirming evidence and update the model when the patient fails to respond as predicted.'],
  },
  {
    id: 'multisystem-tradeoffs', name: 'Multisystem treatment tradeoffs', domain: 'multisystem', level: 5,
    summary: 'A therapy that helps one organ can worsen another; expert care weighs global benefit, reversibility and monitoring.',
    prereq: ['shock', 'ppv-hemodynamics'], related: ['uncertainty'],
    performance: ['Explain at least two competing organ effects of a proposed intervention.', 'Choose the least harmful testable strategy when the optimal answer is uncertain.'],
  },
];

export const MASTERY_BY_ID = Object.fromEntries(MASTERY.map((c) => [c.id, c])) as Record<string, MasteryConcept>;

export function missingMasteryPrereqs(id: string, mastered: Set<string>) {
  return (MASTERY_BY_ID[id]?.prereq ?? []).filter((p) => !mastered.has(p));
}
