/**
 * Guided lessons for the invasive-lines module. Each step declares the bedside state it needs;
 * `applyStep` builds it on the live session (scenario, breathing, faults, levelling, view).
 */
import type { Fault } from './transducer';
import type { LinesView } from './linesStore';

export interface LStepDo {
  scenario?: string; view?: LinesView; vent?: 'spont' | 'ppv'; vt?: number;
  art?: Fault; cvp?: Fault; /** cm the transducer sits BELOW the axis (negative = above) */ below?: number; hob?: number; bedH?: number; /** leave the transducer where it was levelled for this head-of-bed angle */ fromHob?: number;
  flush?: 'art' | 'cvp'; showTrue?: boolean; freeze?: boolean; zeroWrong?: 'art' | 'cvp'; fluids?: number; nore?: number; tap?: boolean;
}
export interface LStep { id: string; title: string; say: string; do: LStepDo }
export interface LLesson { id: string; title: string; level: 'Novice' | 'Intermediate' | 'Advanced'; blurb: string; steps: LStep[] }

export const LINES_LESSONS: LLesson[] = [
  { id: 'ln-setup', title: 'From artery to monitor', level: 'Novice', blurb: 'What an arterial line and a central line actually are, and where the numbers come from.', steps: [
    { id: 'ln-setup-1', title: 'A column of saline carries the pressure', say: 'An arterial line is a short cannula in an artery — here the right radial — joined by stiff, saline-filled tubing to a pressure transducer. The fluid column transmits every pressure change to the transducer, which turns it into the waveform and the numbers on the monitor.', do: { scenario: 'normal', view: 'bed' } },
    { id: 'ln-setup-2', title: 'The radial cannula', say: 'A 20-gauge cannula sits in the radial artery at the wrist. A bag of saline squeezed to 300 mmHg pushes about 3 mL an hour through the line, so blood cannot back up and clot. The bag must stay above the patient’s systolic pressure.', do: { view: 'wrist' } },
    { id: 'ln-setup-3', title: 'The central line', say: 'The central venous catheter enters the right internal jugular vein and runs down through the superior vena cava. Its tip should sit at the cavo-atrial junction, where the SVC meets the right atrium. The pressure there is the central venous pressure — essentially right-atrial pressure.', do: { view: 'neck' } },
    { id: 'ln-setup-4', title: 'Inside the chest', say: 'Watch the chambers. The atria contract just after each P wave, the ventricles after each QRS. The right atrium glows brighter as its pressure rises, and a pulse wave runs from the aorta to the wrist — it arrives about a tenth of a second after the heart ejects.', do: { view: 'heart' } },
    { id: 'ln-setup-5', title: 'One reference level for everything', say: 'All the pressures are measured against one reference point: the phlebostatic axis — the fourth intercostal space in the mid-axillary line, roughly the level of the right atrium. The transducer’s air–fluid interface, the zeroing stopcock, must sit level with it.', do: { view: 'level' } },
  ] },
  { id: 'ln-art', title: 'Reading the arterial waveform', level: 'Novice', blurb: 'Upstroke, systolic peak, dicrotic notch, diastolic run-off — and why MAP is the number to trust.', steps: [
    { id: 'ln-art-1', title: 'Each beat, drawn', say: 'The steep upstroke is the left ventricle ejecting into the aorta. The rounded top is the systolic peak. As ejection ends the aortic valve snaps shut, making the dicrotic notch. Then pressure runs off through the arterioles until the next beat: that low point is the diastolic pressure.', do: { scenario: 'normal', view: 'bed' } },
    { id: 'ln-art-2', title: 'Wrist versus aorta', say: 'The radial systolic peak is taller and spikier than in the central aorta and diastolic slightly lower, so the pulse pressure is wider — the wave steepens as it travels out to smaller, stiffer arteries. The mean pressure hardly changes, which is one reason MAP is the number to trust for decisions. Compare the columns in the table: radial versus central aorta.', do: { showTrue: true } },
    { id: 'ln-art-3', title: 'A low dicrotic notch', say: 'This patient is in vasodilated septic shock. Resistance is so low that blood runs off before the valve even closes: the notch slides down toward the diastolic level, diastolic pressure falls and MAP is below 65.', do: { scenario: 'sepsis' } },
    { id: 'ln-art-4', title: 'Vasopressor effect', say: 'Norepinephrine restores vascular tone. Watch diastolic pressure and MAP climb and the notch rise back up the downstroke.', do: { nore: 0.1 } },
    { id: 'ln-art-5', title: 'Stiff arteries', say: 'An older, hypertensive patient: the stiff aorta cannot stretch to absorb each stroke, and the reflected wave returns early, during systole. Systolic pressure climbs, diastolic falls, and the pulse pressure widens past 60 mmHg — with a late systolic shoulder.', do: { scenario: 'stiff' } },
  ] },
  { id: 'ln-cvp', title: 'Reading the CVP waveform', level: 'Intermediate', blurb: 'a, c, x, v, y — lined up against the ECG — and reading the number at end-expiration.', steps: [
    { id: 'ln-cvp-1', title: 'Three peaks, two descents', say: 'The a wave follows the P wave: the atrium contracts. The small c wave comes just after the QRS, as the closing tricuspid valve bulges back into the atrium. The x descent is the atrium relaxing and the valve ring being pulled down. The v wave is the atrium filling against the closed valve, near the end of the T wave. The y descent is the valve opening and blood rushing into the ventricle.', do: { scenario: 'normal', view: 'heart' } },
    { id: 'ln-cvp-2', title: 'Breathing moves the whole trace', say: 'The shaded bands are breaths in. Breathing spontaneously, each breath in lowers the pressure in the chest, so the whole CVP trace dips. The monitor’s number averages every phase, so it reads a little low.', do: { vent: 'spont' } },
    { id: 'ln-cvp-3', title: 'Measure it yourself', say: 'The monitor is frozen. Drag across the CVP trace and read the pressure at end-expiration — just before a shaded breath begins — at the base of the c wave. That is the value to record. Compare it with the monitor’s mean.', do: { freeze: true } },
    { id: 'ln-cvp-4', title: 'On the ventilator it flips', say: 'With positive-pressure ventilation, inspiration raises the pressure in the chest, so the CVP rises with each breath. End-expiration is now the lowest part of the respiratory cycle — still just before the next breath. The rule stays the same: read at end-expiration.', do: { vent: 'ppv' } },
    { id: 'ln-cvp-5', title: 'Cannon a waves', say: 'Complete heart block: atria and ventricles beat independently. When the atrium happens to contract while the tricuspid valve is shut, the blood is pushed back up the jugular: a giant cannon a wave.', do: { scenario: 'chb' } },
    { id: 'ln-cvp-6', title: 'No a wave in AF', say: 'Atrial fibrillation: the atria quiver and never contract as one, so the a wave disappears. You see only c and v, and the arterial pulse varies with every irregular R-R interval.', do: { scenario: 'af' } },
    { id: 'ln-cvp-7', title: 'Giant c-v waves', say: 'Severe tricuspid regurgitation: the right ventricle pumps backwards into the atrium in every systole. The x descent is filled in by a giant c-v wave that can look almost like a ventricular trace.', do: { scenario: 'tr' } },
  ] },
  { id: 'ln-level', title: 'Levelling and zeroing', level: 'Novice', blurb: 'Two different jobs: levelling fixes the reference height, zeroing removes atmospheric pressure.', steps: [
    { id: 'ln-level-1', title: 'Levelled', say: 'The transducers are level with the phlebostatic axis. Levelling and zeroing are different jobs: levelling sets the reference height; zeroing tells the monitor what atmospheric pressure reads.', do: { scenario: 'normal', view: 'level', showTrue: true } },
    { id: 'ln-level-2', title: 'Ten centimetres too low', say: 'The transducer has slipped 10 cm below the axis. The extra 10 cm of saline adds 10 × 0.74 = 7.4 mmHg to every reading. An arterial MAP of 95 becomes 102 — but a CVP of 5 becomes 12, more than double. Low transducer, high reading.', do: { below: 10 } },
    { id: 'ln-level-3', title: 'Raising the head of the bed', say: 'The line was levelled with the bed flat. Now the head of the bed goes up to 30 degrees: the chest — and the phlebostatic axis — rises about 27 cm, but the transducer on the pole stays where it was. Every pressure now reads about 20 mmHg high. Re-level after any change in bed height or position.', do: { hob: 30, fromHob: 0 } },
    { id: 'ln-level-4', title: 'Zero to air', say: 'Zeroing: turn the stopcock off to the patient and open to air, press zero, then turn it back. The monitor now knows what atmospheric pressure looks like at the level of the stopcock.', do: { below: 0, hob: 30 } },
    { id: 'ln-level-5', title: 'The classic mistake', say: 'This line was zeroed while the stopcock was still open to the patient. The monitor subtracted the patient’s own pressure: the trace sits around zero and swings negative. The shape is right; the numbers are wrong. Zero again, open to air.', do: { zeroWrong: 'art' } },
  ] },
  { id: 'ln-damp', title: 'Damping and the square-wave test', level: 'Intermediate', blurb: 'Why a line rings or smears, and how a one-second flush tells you which.', steps: [
    { id: 'ln-damp-1', title: 'An optimally damped line', say: 'Pull the flush for a second and let go. The trace jumps to the bag pressure, drops back, bounces one and a half to two times, then the waveform resumes. That is an optimally damped system: trust the systolic and diastolic values.', do: { scenario: 'normal', flush: 'art', showTrue: true } },
    { id: 'ln-damp-2', title: 'Underdamped: it rings', say: 'Extra extension tubing and stopcocks lower the natural frequency of the line. Now the flush bounces many times, and each heartbeat sets the line ringing: a spiky systolic overshoot. Systolic reads too high, diastolic slightly low — MAP is the least affected. It gets worse at faster heart rates.', do: { art: 'longTubing', flush: 'art', showTrue: true } },
    { id: 'ln-damp-3', title: 'A small bubble does the same', say: 'A tiny air bubble is very compliant. It drops the natural frequency sharply, so the line resonates and overshoots. Turn the stopcock off to the patient and flush the bubble out through the side port to waste.', do: { art: 'smallBubble', flush: 'art', showTrue: true } },
    { id: 'ln-damp-4', title: 'Overdamped: it smears', say: 'A clot at the tip, a kink, a large bubble or a soft pressure bag absorbs the pulse. The flush slides back with no bounce, the notch disappears, systolic reads low and diastolic high. MAP still holds — until the line blocks completely.', do: { art: 'clot', flush: 'art', showTrue: true } },
    { id: 'ln-damp-5', title: 'Never flush a clot forward', say: 'An overdamped arterial line with sluggish blood return: aspirate first, then flush. Flushing a clot forward can embolise into the hand; flushing a bubble toward the patient puts air into the circulation — from a radial line it can even travel back up to the brain. Always clear air out of the side port to waste.', do: { art: 'clot', view: 'wrist' } },
  ] },
  { id: 'ln-heartlung', title: 'Heart–lung interactions', level: 'Advanced', blurb: 'Pulse-pressure variation, fluid responsiveness and pulsus paradoxus.', steps: [
    { id: 'ln-hl-1', title: 'Pulse-pressure variation', say: 'This patient has lost blood and is on the ventilator. Each positive-pressure breath squeezes blood out of the lungs into the left heart, then limits venous return for the next few beats. An underfilled heart is sensitive to that: the pulse pressure swings by more than 13 %.', do: { scenario: 'hypovol', vent: 'ppv', vt: 8 } },
    { id: 'ln-hl-2', title: 'Give fluid, watch PPV fall', say: 'Three 500 mL boluses. Stroke volume rises, the heart moves up the steep part of its Starling curve onto the flat part, and the variation shrinks. The patient was fluid-responsive.', do: { fluids: 3 } },
    { id: 'ln-hl-3', title: 'When PPV lies', say: 'PPV only predicts fluid response with controlled breaths of at least 8 mL/kg, a regular rhythm, no spontaneous effort and a closed chest — and it is unreliable with very stiff lungs, RV failure or raised abdominal pressure. Here the patient breathes on their own: the variation is meaningless.', do: { scenario: 'hypovol', vent: 'spont' } },
    { id: 'ln-hl-4', title: 'Irregular rhythm', say: 'In atrial fibrillation every beat has a different filling time, so pulse pressure varies whatever the volume status. PPV cannot be used.', do: { scenario: 'af', vent: 'ppv' } },
    { id: 'ln-hl-5', title: 'Pulsus paradoxus', say: 'Cardiac tamponade, breathing spontaneously. The pericardium limits total heart volume: when the right heart fills on inspiration, the septum bows left and the left ventricle ejects less. Systolic pressure falls more than 10 mmHg with every breath in, the CVP is high, and there is no y descent.', do: { scenario: 'tamponade', vent: 'spont' } },
    { id: 'ln-hl-6', title: 'Drain it', say: 'Pericardiocentesis. As the fluid comes off, the paradox disappears, the CVP falls, the y descent returns and the heart rate slows.', do: { tap: true } },
  ] },
  { id: 'ln-disease', title: 'Waveforms of disease', level: 'Intermediate', blurb: 'Aortic stenosis and regurgitation, LV failure, PVCs, RV failure.', steps: [
    { id: 'ln-dz-1', title: 'Aortic stenosis', say: 'A narrow valve slows ejection: the upstroke is slow and late (pulsus tardus), the peak small (parvus), often with an anacrotic shoulder, and the notch is faint.', do: { scenario: 'as' } },
    { id: 'ln-dz-2', title: 'Aortic regurgitation', say: 'Blood falls back into the ventricle in diastole: diastolic pressure is very low, and the ventricle ejects a huge stroke — a steep upstroke, a wide pulse pressure, often a double systolic peak, and no notch.', do: { scenario: 'ar' } },
    { id: 'ln-dz-3', title: 'Failing left ventricle', say: 'Cardiogenic shock: a weak ventricle ejects slowly against high resistance. The upstroke is sluggish, the pulse pressure narrow, and the CVP high. Little pulse-pressure variation: more fluid will not help.', do: { scenario: 'cardiogenic', vent: 'ppv' } },
    { id: 'ln-dz-4', title: 'PVCs', say: 'A premature beat fires before the ventricle has filled: a small or absent pulse. The pause that follows lets the next beat fill more, and it is bigger than normal.', do: { scenario: 'pvc' } },
    { id: 'ln-dz-5', title: 'Right ventricular failure', say: 'Massive pulmonary embolism: the right ventricle is pressure-loaded. The CVP is high with large a and v waves, the left heart is underfilled and the arterial pulse is narrow.', do: { scenario: 'rvfail' } },
  ] },
];
