/** Exact shipped, attributed comparators; never pretend the model predicts this reference patient's scan. */
export const ATLAS_MEDIA: Record<string, { ids:string[]; context:string }> = {
  ards:{ids:['cxr-ards-2019','cxr-ards-ecmo-recovery-2026'],context:'Compare bilateral opacities with the schematic alveolar injury.'},
  pneumonia:{ids:['lus-hepatisation-gillman'],context:'Compare a real consolidation pattern; ultrasound alone does not establish its cause.'},
  'pulmonary-edema':{ids:['cxr-chf-haggstrom','cxr-flash-edema-portable-2026'],context:'Compare hydrostatic pulmonary congestion with the model.'},
  atelectasis:{ids:['cxr-collapse-before-after-2021','cxr-left-whiteout-mucus-plug-2026'],context:'Compare lung volume loss and re-expansion in a reference patient.'},
  'simple-pneumothorax':{ids:['cxr-ptx-right-spontaneous-2026','ptx-expiratory','cxr-ptx-left-large-2024','lus-lung-point-gillman'],context:'Compare pleural air findings. Imaging does not by itself determine hemodynamic tension.'},
  'tension-pneumothorax':{ids:['cxr-tension-ptx-right-olv-2024','ptx-series-bonilla','cxr-pigtail-drain-reexpanded-2026'],context:'Compare a collapsed lung with mediastinal shift, then re-expansion after drainage. The film supports, but does not by itself prove, tension physiology.'},
  tamponade:{ids:['tamponade-ginghina'],context:'Compare right-heart collapse in a real pericardial effusion.'},
  lvo:{ids:['stroke-cta-m1-2025','stroke-ctp-mismatch-2025'],context:'Compare an occluded MCA and perfusion mismatch in reference scans.'},
  'core-penumbra':{ids:['stroke-ctp-mismatch-2025'],context:'Compare core and threatened tissue in a reference perfusion study.'},
  ich:{ids:['ich-deep-locations-2016','ich-ivh-commons'],context:'Compare parenchymal blood and possible ventricular extension.'},
  sah:{ids:['sah-ct-mirza'],context:'Compare blood in subarachnoid spaces.'},
  'cerebral-edema':{ids:['stroke-malignant-edema-2023'],context:'This reference illustrates edema after an infarct; other causes of edema differ.'},
  'rising-icp':{ids:['stroke-mass-effect-2021','ich-thalamic-hydro-yadav'],context:'Compare mass effect and hydrocephalus. A scan is not an ICP measurement.'},
  aaa:{ids:['aaa-us-sagittal-haggstrom','aaa-us-axial-haggstrom','ct-aaa-intact-66mm-coronal-2025'],context:'Compare the aneurysmal abdominal aorta on ultrasound in two views and on CT.'},
  'rupturing-aaa':{ids:['ct-aaa-rupture-96mm-2026','ct-aaa-rupture-right-hematoma-2025','aaa-us-sagittal-haggstrom'],context:'Compare a ruptured aneurysm with retroperitoneal blood on CT; the ultrasound shows aneurysmal anatomy only. Retroperitoneal blood may be missed by FAST.'},
  'abdominal-hemorrhage':{ids:['fast-ruq-positive','fast-pelvis-positive-vats','fast-luq-positive-scandj-2023','ct-splenic-laceration-hemoperitoneum-2025'],context:'Compare free fluid in the right upper quadrant; the image alone does not identify its source.'},
  'acute-heart-failure':{ids:['cxr-flash-edema-portable-2026'],context:'Compare acute cardiogenic pulmonary oedema on a portable film with the model.'},
  'aortic-dissection':{ids:['ct-dissection-type-a-arch-flap-2025','ct-dissection-type-b-flap-2026','ct-renal-malperfusion-dissection-fl-2025'],context:'Compare an intimal flap reaching the arch (type A), one confined to the descending aorta (type B), and a kidney starved by the false lumen.'},
  'pediatric-asthma':{ids:['cxr-hyperinflation-asthma-2025'],context:'Compare hyperinflation in near-fatal asthma in a 12-year-old: flat diaphragms, long lung fields.'},
  croup:{ids:['peds-croup-steeple-2019'],context:'Compare the tapered subglottic narrowing (steeple sign) on a frontal neck film; the diagnosis is clinical and most children need no film.'},
  'pediatric-airway':{ids:['peds-epiglottitis-thumb-2026','peds-croup-steeple-2019'],context:'Compare supraglottic swelling (thumb sign) with subglottic narrowing (steeple sign); never send an unstable child to radiology for this.'},
  'neonatal-rds':{ids:['peds-irds-preterm-haggstrom'],context:'Compare the fine granular lungs and air bronchograms of surfactant deficiency in a preterm infant.'},
  'obstructive-shock':{ids:['cxr-tension-ptx-right-olv-2024','fast-pericardial-positive-focus-2026'],context:'Two causes of obstructive shock in reference patients: tension pneumothorax and a large pericardial effusion.'},
};
