import type { ClinicalVideo, VideoCategoryDefinition, VideoFilters } from './types';

export const VIDEO_CATEGORIES: VideoCategoryDefinition[] = [
  {
    id: 'devices',
    label: 'Medical devices',
    description: 'Setup, operation, transport use and troubleshooting of critical-care equipment.',
    subcategories: [
      { id: 'chest-drainage', label: 'Chest drainage systems' },
      { id: 'ventilators', label: 'Ventilators' },
      { id: 'infusion-pumps', label: 'Infusion pumps' },
      { id: 'high-flow', label: 'HFNC / high flow' },
      { id: 'evd', label: 'EVD / ICP systems' },
      { id: 'iabp', label: 'IABP' },
      { id: 'ecmo', label: 'ECMO' },
      { id: 'monitors', label: 'Transport monitors' },
      { id: 'peds-neonatal', label: 'Pediatric / neonatal devices' },
    ],
  },
  {
    id: 'procedures',
    label: 'Procedures',
    description: 'Hands-on setup, performance, management and complication recognition.',
    subcategories: [
      { id: 'chest-tube', label: 'Chest tube' },
      { id: 'thoracostomy', label: 'Needle / finger thoracostomy' },
      { id: 'airway', label: 'RSI / difficult airway' },
      { id: 'cricothyrotomy', label: 'Cricothyrotomy' },
      { id: 'vascular-access', label: 'Arterial / central access' },
      { id: 'blood', label: 'Blood administration' },
      { id: 'tracheostomy', label: 'Tracheostomy care' },
      { id: 'enteral-access', label: 'NG / enteral access' },
      { id: 'venipuncture', label: 'Venipuncture / blood draw' },
      { id: 'medication-admin', label: 'Medication administration' },
      { id: 'pressors', label: 'Push-dose pressors' },
      { id: 'transducers', label: 'Transducer setup / leveling' },
    ],
  },
  {
    id: 'airway-vent',
    label: 'Airway & ventilation',
    description: 'Ventilator modes, waveforms, oxygenation, obstruction and troubleshooting.',
    subcategories: [
      { id: 'vent-setup', label: 'Ventilator setup' },
      { id: 'modes', label: 'Modes' },
      { id: 'aprv', label: 'APRV' },
      { id: 'peep', label: 'PEEP' },
      { id: 'waveforms', label: 'Waveforms' },
      { id: 'auto-peep', label: 'Auto-PEEP' },
      { id: 'ards', label: 'ARDS' },
      { id: 'asthma-copd', label: 'Asthma / COPD' },
    ],
  },
  {
    id: 'hemodynamics',
    label: 'Hemodynamics & shock',
    description: 'Pressure, flow, perfusion, vasoactives and shock phenotypes.',
    subcategories: [
      { id: 'shock', label: 'Shock' },
      { id: 'arterial-lines', label: 'Arterial lines' },
      { id: 'pac', label: 'PA catheter' },
      { id: 'vasoactives', label: 'Vasoactives' },
      { id: 'mechanical-support', label: 'Mechanical support' },
    ],
  },
  {
    id: 'cardiac',
    label: 'Cardiology',
    description: 'ECG, ischemia, arrhythmia, pump failure and mechanical support.',
    subcategories: [
      { id: 'ecg', label: 'ECG' },
      { id: 'stemi', label: 'STEMI' },
      { id: 'arrhythmia', label: 'Arrhythmia' },
      { id: 'cardiogenic-shock', label: 'Cardiogenic shock' },
      { id: 'aorta', label: 'Aortic emergencies' },
    ],
  },
  {
    id: 'neuro',
    label: 'Neurocritical care',
    description: 'Stroke, ICP, EVDs, seizures and neurologic emergencies.',
    subcategories: [
      { id: 'ich-sah', label: 'ICH / SAH' },
      { id: 'lvo', label: 'LVO / ischemic stroke' },
      { id: 'icp', label: 'ICP / herniation' },
      { id: 'evd', label: 'EVD management' },
      { id: 'seizure', label: 'Seizure / status' },
    ],
  },
  {
    id: 'trauma',
    label: 'Trauma',
    description: 'Resuscitation, hemorrhage control, thoracic trauma and transport.',
    subcategories: [
      { id: 'hemorrhage', label: 'Hemorrhage' },
      { id: 'thoracic', label: 'Thoracic trauma' },
      { id: 'tbi', label: 'TBI' },
      { id: 'massive-transfusion', label: 'Massive transfusion' },
    ],
  },
  {
    id: 'pharmacology',
    label: 'Critical-care pharmacology',
    description: 'High-risk medications, dilution, delivery and mechanisms.',
    subcategories: [
      { id: 'vasoactives', label: 'Vasoactives' },
      { id: 'sedation', label: 'Sedation / analgesia' },
      { id: 'paralytics', label: 'Neuromuscular blockade' },
      { id: 'electrolytes', label: 'Electrolytes' },
    ],
  },
  {
    id: 'peds-neonatal',
    label: 'Pediatric & neonatal',
    description: 'Age-specific airway, ventilation, shock and transport equipment.',
    subcategories: [
      { id: 'peds-airway', label: 'Pediatric airway' },
      { id: 'peds-shock', label: 'Pediatric shock' },
      { id: 'neonatal-vent', label: 'Neonatal ventilation' },
      { id: 'transport', label: 'Transport equipment' },
    ],
  },
  {
    id: 'labs-pocus',
    label: 'Labs, ABGs & POCUS',
    description: 'Acid-base, laboratory interpretation and bedside ultrasound.',
    subcategories: [
      { id: 'abg', label: 'ABG / acid-base' },
      { id: 'electrolytes', label: 'Electrolytes' },
      { id: 'lung-us', label: 'Lung ultrasound' },
      { id: 'fast', label: 'FAST' },
      { id: 'vascular-us', label: 'Vascular ultrasound' },
    ],
  },
];


export const CHANNEL_COLLECTIONS = [
  {
    id: 'criticalcarenow',
    label: 'CriticalCareNow',
    channelId: 'UCDDtgNzqvUC8235U8iq4SUA',
    uploadsPlaylistId: 'UUDDtgNzqvUC8235U8iq4SUA',
    description: 'Critical care, resuscitation, airway, POCUS, procedures and ICU practice.',
  },
  {
    id: 'lecturio-medical',
    label: 'Lecturio Medical',
    channelId: 'UCbYmF43dpGHz8gi2ugiXr0Q',
    uploadsPlaylistId: 'UUbYmF43dpGHz8gi2ugiXr0Q',
    description: 'Medical physiology, pathology, pharmacology and clinical medicine.',
  },
  {
    id: 'lecturio-nursing',
    label: 'Lecturio Nursing',
    channelId: 'UCLpMl5BTrOwTDwAJ69Q4-sg',
    uploadsPlaylistId: 'UULpMl5BTrOwTDwAJ69Q4-sg',
    description: 'Nursing clinical skills, devices, disease management and bedside care.',
  },
] as const;

export const VIDEO_SKILL_COLLECTIONS = [
  { id: 'all', label: 'All skills & devices' },
  { id: 'ventilators', label: 'Ventilators' },
  { id: 'infusion', label: 'Infusion pumps & tubing' },
  { id: 'chest-drains', label: 'Chest tubes & drains' },
  { id: 'evd-icp', label: 'EVD / ICP' },
  { id: 'arterial-lines', label: 'Arterial lines & transducers' },
  { id: 'central-lines', label: 'Central lines' },
  { id: 'hfnc', label: 'HFNC / AIRVO' },
  { id: 'iabp', label: 'IABP' },
  { id: 'ecmo', label: 'ECMO' },
  { id: 'airway-trach', label: 'Airway & trach' },
  { id: 'iv-vascular', label: 'IV & vascular access' },
  { id: 'blood', label: 'Blood & transfusion' },
  { id: 'tubes', label: 'NG & tubes' },
] as const;

export type VideoSkillCollectionId = typeof VIDEO_SKILL_COLLECTIONS[number]['id'];

export function isSkillVideo(video: ClinicalVideo) {
  return video.category === 'devices'
    || video.category === 'procedures'
    || video.intents.some((intent) => intent === 'setup' || intent === 'perform' || intent === 'troubleshoot');
}

export function videoMatchesSkill(video: ClinicalVideo, skill: VideoSkillCollectionId) {
  if (skill === 'all') return isSkillVideo(video);
  const haystack = [video.title, video.subcategory, ...video.tags].join(' ').toLowerCase();
  if (skill === 'ventilators') return /ventilator|mechanical ventilation|vent management|peep|plateau pressure|peak pressure|revel|ltv|hamilton|servo/.test(haystack);
  if (skill === 'infusion') return /infusion pump|iv tubing|piggyback|primary line|secondary line|sapphire|infusomat|braun|pump setup/.test(haystack);
  if (skill === 'chest-drains') return /chest tube|chest drain|pleural|water seal|thoracic drainage/.test(haystack);
  if (skill === 'evd-icp') return /evd|external ventricular|ventriculostomy|icp|csf drainage|leveling|zeroing/.test(haystack);
  if (skill === 'arterial-lines') return /arterial line|a-line|transducer|square wave|leveling|zeroing|femoral arterial/.test(haystack);
  if (skill === 'central-lines') return /central line|central venous|cvc|picc|central-line/.test(haystack);
  if (skill === 'hfnc') return /hfnc|high flow|high-flow|airvo|optiflow/.test(haystack);
  if (skill === 'iabp') return /iabp|intra-aortic balloon|balloon pump|counterpulsation/.test(haystack);
  if (skill === 'ecmo') return /ecmo|extracorporeal|vv ecmo|va ecmo|membrane oxygenation/.test(haystack);
  if (skill === 'airway-trach') return /airway|intubat|trach|cric|suction/.test(haystack);
  if (skill === 'iv-vascular') return /\b(iv|intravenous|venipuncture|vascular|catheter)\b/.test(haystack);
  if (skill === 'blood') return /blood|transfusion|whole blood|massive transfusion/.test(haystack);
  if (skill === 'tubes') return /nasogastric|\bng\b|enteral|feeding tube/.test(haystack);
  return false;
}

export const VIDEO_LIBRARY: ClinicalVideo[] = [
  {
    id: 'bbraun-infusomat-space-official-media',
    title: 'Infusomat Space — Official Product Media & Training',
    channel: 'B. Braun',
    provider: 'external',
    sourceClass: 'manufacturer',
    sourceUrl: 'https://catalogs.bbraun.com/en-01/p/PRID00001229/infusomat-space',
    sourceLabel: 'Official B. Braun product media',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['learn', 'setup', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['B. Braun', 'Infusomat Space', 'infusion pump', 'manufacturer training', 'official media'],
    summary: 'Official B. Braun Infusomat Space product resource with product documentation and manufacturer media.',
    reviewStatus: 'listed',
    featured: true,
    published: '2026-09-30',
  },
  {
    id: 'bbraun-perfusor-space-official-media',
    title: 'Perfusor Space — Official Product Media & Training',
    channel: 'B. Braun',
    provider: 'external',
    sourceClass: 'manufacturer',
    sourceUrl: 'https://catalogs.bbraun.com/en-gb/p/PRID00001226/perfusor-space',
    sourceLabel: 'Official B. Braun product media',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['learn', 'setup', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['B. Braun', 'Perfusor Space', 'syringe pump', 'manufacturer training', 'official media'],
    summary: 'Official B. Braun Perfusor Space product resource with manufacturer media and device documentation.',
    reviewStatus: 'listed',
    featured: true,
  },
  {
    id: 'bbraun-spaceplus-mri-handling',
    title: 'Spaceplus MRI Station Handling Video',
    channel: 'B. Braun',
    provider: 'external',
    sourceClass: 'manufacturer',
    sourceUrl: 'https://www.bbraun.com/en/products-and-solutions/therapies/infusion-therapy/automated-infusion-pumps-spaceplus/registration-form-for-mri-video.html',
    sourceLabel: 'Official B. Braun handling video',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['setup', 'manage'],
    level: 'intermediate',
    tags: ['B. Braun', 'Spaceplus', 'MRI station', 'Infusomat', 'Perfusor', 'manufacturer video'],
    summary: 'Official B. Braun Spaceplus MRI Station handling video covering pump placement, line insertion and station locking.',
    reviewStatus: 'listed',
    featured: true,
  },
  {
    id: 'bbraun-space-technical-training',
    title: 'Space Infusion System — Official Technical Training',
    channel: 'B. Braun',
    provider: 'external',
    sourceClass: 'manufacturer',
    sourceUrl: 'https://www.bbraunusa.com/en/products-and-partnerships/smart-infusion/smart-infusion-pumps/infusion-systems-technical-training.html',
    sourceLabel: 'Official B. Braun USA training',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['learn', 'setup', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['B. Braun', 'Infusomat Space', 'Perfusor Space', 'SpaceStation', 'SpaceCom', 'technical training'],
    summary: 'Official B. Braun USA Space-system technical training covering system design, use, operation, calibration, maintenance and components.',
    reviewStatus: 'listed',
  },
  {
    id: 'criticalcarenow-vent-trauma-management',
    title: 'Vent Management In The Critical Trauma Patient',
    channel: 'CriticalCareNow',
    youtubeId: 'QEXZuGAerh0',
    format: 'long',
    category: 'airway-vent',
    subcategory: 'vent-setup',
    intents: ['learn', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['ventilator', 'vent management', 'peak pressure', 'plateau pressure', 'PEEP', 'trauma', 'air leak'],
    summary: 'Stepwise ventilator troubleshooting in a crashing trauma patient, including peak-versus-plateau pressure, air leak, positioning and PEEP/hemodynamic tradeoffs.',
    reviewStatus: 'listed',
    featured: true,
    published: '2026-06-18',
  },
  {
    id: 'criticalcarenow-arterial-lines',
    title: 'Arterial Lines in Cardiac Arrest',
    channel: 'CriticalCareNow',
    youtubeId: 'kVdMjkl4UHY',
    format: 'long',
    category: 'procedures',
    subcategory: 'vascular-access',
    intents: ['learn', 'perform', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['arterial line', 'femoral arterial line', 'a-line', 'waveform', 'cardiac arrest', 'hemodynamics'],
    summary: 'Placement and interpretation of arterial-line monitoring during cardiac arrest, with emphasis on continuous pressure feedback.',
    reviewStatus: 'listed',
    featured: true,
    published: '2023-04-09',
  },
  {
    id: 'criticalcarenow-arterial-lines-short',
    title: 'Please Arterial Lines in Cardiac Arrest',
    channel: 'CriticalCareNow',
    youtubeId: 'mH_Yqy2jMdg',
    format: 'short',
    category: 'procedures',
    subcategory: 'vascular-access',
    intents: ['learn', 'perform'],
    level: 'advanced',
    tags: ['arterial line', 'a-line', 'cardiac arrest', 'resuscitation'],
    summary: 'Short CriticalCareNow pearl on using arterial lines during cardiac arrest.',
    reviewStatus: 'listed',
    published: '2023-04-11',
  },
  {
    id: 'lecturio-nursing-blood-transfusion',
    title: 'Blood Transfusions: A Step by Step Guide for Nurses',
    channel: 'Lecturio Nursing',
    youtubeId: '-AbU1m-zpq4',
    format: 'long',
    category: 'procedures',
    subcategory: 'blood',
    intents: ['setup', 'perform', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['blood transfusion', 'blood administration', 'verification', 'transfusion reaction', 'blood tubing'],
    summary: 'Step-by-step blood-product administration including verification, assessment timing and transfusion-safety workflow.',
    reviewStatus: 'listed',
    featured: true,
    published: '2022-01-18',
  },
  {
    id: 'sapphire-pump-setup-official',
    title: 'Sapphire Infusion Pump - Setup Training Video',
    channel: 'Eitan Medical',
    youtubeId: 'IOHzN6B_qXg',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['setup', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['Sapphire', 'infusion pump', 'pump setup', 'administration set', 'Eitan Medical'],
    summary: 'Manufacturer training covering Sapphire pump setup for infusion and basic system operation.',
    reviewStatus: 'listed',
    featured: true,
    published: '2020-04-19',
  },
  {
    id: 'sapphire-pump-overview-official',
    title: 'Sapphire Infusion Pump: System Overview Training Video',
    channel: 'Eitan Medical',
    youtubeId: '-4yEB7XE9gQ',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['learn', 'setup', 'manage'],
    level: 'foundational',
    tags: ['Sapphire', 'infusion pump', 'system overview', 'administration sets', 'Eitan Medical'],
    summary: 'Manufacturer overview of the Sapphire pump, power supply, administration sets and basic operation.',
    reviewStatus: 'listed',
    published: '2020-04-19',
  },
  {
    id: 'airvo2-setup-official',
    title: 'How to set-up your F&P Airvo 2 for Optiflow Nasal High Flow therapy',
    channel: 'F&P Healthcare',
    youtubeId: 'f_OkSQshJQU',
    format: 'long',
    category: 'devices',
    subcategory: 'high-flow',
    intents: ['setup', 'manage'],
    level: 'foundational',
    tags: ['AIRVO 2', 'HFNC', 'high flow', 'Optiflow', 'Fisher Paykel', 'device setup'],
    summary: 'Manufacturer step-by-step setup of the AIRVO 2 high-flow system and patient interfaces.',
    reviewStatus: 'listed',
    featured: true,
    published: '2019-02-17',
  },
  {
    id: 'evd-system-setup-head2toe',
    title: 'External Ventricular Drain (EVD) Insertion and Drainage System Set-up',
    channel: 'Head2Toe Academy',
    youtubeId: 'aM6NkpdEc1I',
    format: 'long',
    category: 'devices',
    subcategory: 'evd',
    intents: ['setup', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['EVD', 'external ventricular drain', 'ICP', 'CSF drainage', 'leveling', 'zeroing', 'waveform'],
    summary: 'Detailed EVD drainage-system setup with equipment, sterile preparation, leveling, zeroing, waveforms and documentation.',
    reviewStatus: 'listed',
    featured: true,
    published: '2025-05-16',
  },
  {
    id: 'icu-advantage-iabp-management',
    title: 'Management of the Intra-Aortic Balloon Pump (IABP)',
    channel: 'ICU Advantage',
    youtubeId: 'iZsaV9qQczs',
    format: 'long',
    category: 'devices',
    subcategory: 'iabp',
    intents: ['learn', 'setup', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['IABP', 'intra-aortic balloon pump', 'balloon pump', 'counterpulsation', 'timing', 'weaning'],
    summary: 'IABP setup, pump assessment, patient assessment, timing concepts and weaning considerations.',
    reviewStatus: 'listed',
    featured: true,
    published: '2021-10-12',
  },
  {
    id: 'wbm-ecmo-basics',
    title: 'Extracorporeal Membrane Oxygenation (ECMO) Basics - Comprehensive Overview',
    channel: 'WBM Emergency & Critical Care',
    youtubeId: 'WPf5I0CP_yE',
    format: 'long',
    category: 'devices',
    subcategory: 'ecmo',
    intents: ['learn', 'manage', 'troubleshoot'],
    level: 'advanced',
    tags: ['ECMO', 'VV ECMO', 'VA ECMO', 'extracorporeal', 'oxygenator', 'circuit', 'mechanical support'],
    summary: 'Overview of VV/VA ECMO, circuit components, indications, daily management and common complications.',
    reviewStatus: 'listed',
    featured: true,
    published: '2021-02-08',
  },
  {
    id: 'central-line-dressing-change-cassie',
    title: 'How to Perform a Central Line Dressing Change',
    channel: 'Nursing Skills with Cassie',
    youtubeId: 'qpR9U8dRtek',
    format: 'long',
    category: 'procedures',
    subcategory: 'vascular-access',
    intents: ['setup', 'perform', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['central line', 'CVC', 'PICC', 'dressing change', 'sterile technique', 'CLABSI'],
    summary: 'Step-by-step central-line dressing change covering sterile setup, site assessment, catheter-length checks, CHG cleaning and dressing application.',
    reviewStatus: 'listed',
    published: '2025-12-13',
  },
  {
    id: 'lecturio-nursing-clinical-skills-compilation',
    title: 'Clinical Skills for NCLEX — Full Nursing Skills Compilation',
    channel: 'Lecturio Nursing',
    youtubeId: 'hXlFNILv2w8',
    format: 'long',
    category: 'procedures',
    subcategory: 'vascular-access',
    intents: ['learn', 'setup', 'perform', 'manage'],
    level: 'foundational',
    tags: ['clinical skills', 'IV catheter', 'IM injection', 'venipuncture', 'blood transfusion', 'NG tube', 'wound care', 'sterile technique'],
    summary: 'Large clinical-skills compilation covering IV insertion, injections, venipuncture, blood transfusion, NG insertion, wound care, ostomy care and sterile technique.',
    reviewStatus: 'listed',
    featured: true,
    published: '2026-05-24',
  },
  {
    id: 'lecturio-nursing-iv-start',
    title: 'How to Start an IV: Setup, Supplies & Patient Prep',
    channel: 'Lecturio Nursing',
    youtubeId: '3bdiwHIlJQk',
    format: 'long',
    category: 'procedures',
    subcategory: 'vascular-access',
    intents: ['setup', 'perform', 'troubleshoot'],
    level: 'foundational',
    tags: ['IV', 'intravenous catheter', 'IV start', 'vascular access', 'supplies', 'priming'],
    summary: 'Step-by-step IV-start setup, equipment, patient preparation and catheter priming.',
    reviewStatus: 'listed',
    featured: true,
    published: '2021-08-26',
  },
  {
    id: 'lecturio-nursing-ng-insertion',
    title: 'How to Insert a Nasogastric Tube Like a Pro',
    channel: 'Lecturio Nursing',
    youtubeId: 'ief6SBTHqrw',
    format: 'long',
    category: 'procedures',
    subcategory: 'enteral-access',
    intents: ['setup', 'perform', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['NG tube', 'nasogastric tube', 'Salem sump', 'gastric decompression', 'enteral access'],
    summary: 'NG-tube preparation, measurement, insertion, placement confirmation and troubleshooting.',
    reviewStatus: 'listed',
    featured: true,
    published: '2022-10-26',
  },
  {
    id: 'lecturio-nursing-trach-care',
    title: 'Tracheostomy Care: How To Perform Trach Care',
    channel: 'Lecturio Nursing',
    youtubeId: 'J5cxrht6t-c',
    format: 'long',
    category: 'procedures',
    subcategory: 'tracheostomy',
    intents: ['setup', 'perform', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['tracheostomy', 'trach care', 'airway', 'inner cannula', 'stoma'],
    summary: 'Theory plus live demonstration of routine tracheostomy care and airway-device maintenance.',
    reviewStatus: 'listed',
    featured: true,
    published: '2023-06-24',
  },
  {
    id: 'lecturio-nursing-venipuncture',
    title: 'How To Draw Labs Via Venipuncture for Nurses',
    channel: 'Lecturio Nursing',
    youtubeId: 'uizbFDmlJFM',
    format: 'long',
    category: 'procedures',
    subcategory: 'venipuncture',
    intents: ['setup', 'perform'],
    level: 'foundational',
    tags: ['venipuncture', 'blood draw', 'labs', 'vascular access'],
    summary: 'Step-by-step venipuncture demonstration from client preparation through needle removal and post-procedure care.',
    reviewStatus: 'listed',
    published: '2022-12-20',
  },
  {
    id: 'lecturio-nursing-iv-tubing',
    title: 'IV Tubing Explained: Primary Line, Secondary Line and Piggy Back',
    channel: 'Lecturio Nursing',
    youtubeId: 'DAVMm09spXI',
    format: 'long',
    category: 'devices',
    subcategory: 'infusion-pumps',
    intents: ['learn', 'setup', 'manage', 'troubleshoot'],
    level: 'foundational',
    tags: ['IV tubing', 'primary line', 'secondary line', 'IV piggyback', 'infusion pump'],
    summary: 'Walkthrough of primary and secondary IV tubing, piggyback setup and common line-management concepts.',
    reviewStatus: 'listed',
    published: '2026-02-04',
  },
  {
    id: 'lecturio-nursing-med-rights-short',
    title: 'Master the 7 Rights of Medication Administration',
    channel: 'Lecturio Nursing',
    youtubeId: 'GGE4wi9UzOI',
    format: 'short',
    category: 'procedures',
    subcategory: 'medication-admin',
    intents: ['learn', 'perform'],
    level: 'foundational',
    tags: ['medication administration', '7 rights', 'med safety', 'nursing skill'],
    summary: 'Quick medication-safety review of the seven rights of medication administration.',
    reviewStatus: 'listed',
    published: '2024-07-08',
  },
  {
    id: 'lecturio-nursing-chest-tube',
    title: 'How To Assess and Manage A Chest Tube For Nurses',
    channel: 'Lecturio Nursing',
    youtubeId: 'gegJV4_vtO0',
    format: 'long',
    category: 'devices',
    subcategory: 'chest-drainage',
    intents: ['setup', 'manage', 'troubleshoot'],
    level: 'foundational',
    tags: ['chest tube', 'wet suction', 'dry suction', 'air leak', 'crepitus', 'drainage'],
    summary: 'Clinical-skills review of wet and dry suction chest-tube assessment, insertion-site checks, air leaks and positioning.',
    reviewStatus: 'listed',
    featured: true,
    published: '2022-04-12',
  },
  {
    id: 'lecturio-nursing-dka-definition',
    title: 'Diabetic Ketoacidosis (DKA) | Definition & Causes',
    channel: 'Lecturio Nursing',
    youtubeId: 'wBr2ZEmL7IQ',
    format: 'long',
    category: 'labs-pocus',
    subcategory: 'electrolytes',
    intents: ['learn'],
    level: 'foundational',
    tags: ['DKA', 'diabetes', 'ketosis', 'metabolic acidosis'],
    summary: 'Foundational DKA definition and causes, useful before advanced resuscitation and electrolyte management.',
    reviewStatus: 'listed',
    published: '2023-05-02',
  },
  {
    id: 'lecturio-nursing-dka-assessment',
    title: 'Diabetic Ketoacidosis (DKA) | Symptoms, Diagnosis, Clinical Presentation, Assessment',
    channel: 'Lecturio Nursing',
    youtubeId: 'EasfhBIaNHE',
    format: 'long',
    category: 'labs-pocus',
    subcategory: 'electrolytes',
    intents: ['learn', 'case-review'],
    level: 'intermediate',
    tags: ['DKA', 'laboratory abnormalities', 'severity', 'assessment', 'pediatric'],
    summary: 'Clinical presentation, severity assessment and laboratory abnormalities in DKA.',
    reviewStatus: 'listed',
    published: '2023-05-06',
  },
  {
    id: 'criticalcarenow-pregnancy-airway',
    title: 'Watch the Airway',
    channel: 'CriticalCareNow',
    youtubeId: 'mqaI5LH6wCI',
    format: 'short',
    category: 'procedures',
    subcategory: 'airway',
    intents: ['learn', 'perform'],
    level: 'advanced',
    tags: ['airway', 'pregnancy', 'intubation', 'aspiration', 'difficult airway'],
    summary: 'Short airway pearl on anticipating difficult intubation and aspiration risk in critically ill pregnancy.',
    reviewStatus: 'listed',
    featured: true,
    published: '2025-05-16',
  },
  {
    id: 'criticalcarenow-airway-blood-debate',
    title: 'Critical Care Rapid-Fire Debate: Bougie, Prehospital Whole Blood, Paralytics and Intubation',
    channel: 'CriticalCareNow',
    youtubeId: 'g7Vl3zS3tsQ',
    format: 'long',
    category: 'procedures',
    subcategory: 'airway',
    intents: ['learn', 'case-review'],
    level: 'advanced',
    tags: ['bougie', 'airway', 'whole blood', 'paralytics', 'intubation', 'prehospital'],
    summary: 'Expert debate covering bougie use, prehospital whole blood, paralytics in neurologic patients and teaching intubation.',
    reviewStatus: 'listed',
    featured: true,
    published: '2025-05-17',
  },
  {
    id: 'lecturio-medical-acid-base-intro',
    title: 'Acid-Base Reaction: Introduction – Chemistry',
    channel: 'Lecturio Medical',
    youtubeId: 'bE6rw1xp9gY',
    format: 'long',
    category: 'labs-pocus',
    subcategory: 'abg',
    intents: ['learn'],
    level: 'foundational',
    tags: ['acid-base', 'acidity', 'base', 'chemistry', 'pH'],
    summary: 'Foundational acid-base chemistry that supports later ABG and metabolic-acid-base interpretation.',
    reviewStatus: 'listed',
    published: '2015-07-21',
  },
  {
    id: 'chest-drain-setup-maintenance',
    title: 'Chest Tubes: Setup and Maintenance',
    channel: 'Nurse Skills',
    youtubeId: 'Ui0eKmEk38M',
    format: 'long',
    category: 'devices',
    subcategory: 'chest-drainage',
    intents: ['setup', 'manage', 'troubleshoot'],
    level: 'foundational',
    tags: ['chest tube', 'atrium', 'oasis', 'water seal', 'suction', 'air leak', 'tidaling'],
    summary: 'Setup of an Atrium Oasis chest drain with air-leak, tidaling and troubleshooting review.',
    reviewStatus: 'listed',
    featured: true,
    published: '2017-05-09',
  },
  {
    id: 'evd-care-setup',
    title: 'External Ventricular Drain EVD',
    channel: 'EmpoweRN',
    youtubeId: 'ALeEdTAQHA8',
    format: 'long',
    category: 'devices',
    subcategory: 'evd',
    intents: ['setup', 'manage', 'troubleshoot'],
    level: 'intermediate',
    tags: ['EVD', 'ICP', 'CSF', 'leveling', 'transducer', 'zeroing', 'drainage'],
    summary: 'EVD setup, priming, leveling, zeroing and bedside management concepts.',
    reviewStatus: 'listed',
    featured: true,
    published: '2025-05-05',
  },
  {
    id: 'evd-overview-cleveland-clinic',
    title: 'External Ventricular Drain (EVD)',
    channel: 'Cleveland Clinic',
    youtubeId: 'Tul9sm30QNo',
    format: 'long',
    category: 'neuro',
    subcategory: 'evd',
    intents: ['learn', 'manage'],
    level: 'foundational',
    tags: ['EVD', 'ICP', 'CSF', 'hydrocephalus', 'ventricular drain'],
    summary: 'Clinical overview of why an EVD is placed, what it drains and how it fits into neurocritical care.',
    reviewStatus: 'listed',
    featured: true,
    published: '2019-07-12',
  },
  {
    id: 'evd-quick-overview',
    title: 'External Ventricular Drain (EVD), ICP monitoring and CSF drainage',
    channel: 'Two Minute Anaesthesia & Critical Care',
    youtubeId: 'xUbMVNoeEcM',
    format: 'long',
    category: 'neuro',
    subcategory: 'evd',
    intents: ['learn'],
    level: 'intermediate',
    tags: ['EVD', 'ICP', 'CSF drainage', 'indications', 'complications'],
    summary: 'Concise overview of EVD indications, placement, drainage and complications.',
    reviewStatus: 'listed',
    published: '2024-05-05',
  },
];

export const videoProvider = (video: ClinicalVideo) => video.provider ?? 'youtube';

export const youtubeWatchUrl = (video: ClinicalVideo) => {
  if (!video.youtubeId) return video.sourceUrl ?? '#';
  return video.format === 'short'
    ? `https://www.youtube.com/shorts/${video.youtubeId}`
    : `https://www.youtube.com/watch?v=${video.youtubeId}`;
};

export const videoSourceUrl = (video: ClinicalVideo) =>
  video.sourceUrl ?? youtubeWatchUrl(video);

export const youtubeThumbnailUrl = (video: ClinicalVideo) =>
  video.thumbnailUrl ?? (video.youtubeId ? `https://i.ytimg.com/vi/${video.youtubeId}/hqdefault.jpg` : '');

export const canAutoplayInFeed = (video: ClinicalVideo) => {
  const provider = videoProvider(video);
  if (provider === 'youtube') return Boolean(video.youtubeId);
  if (provider === 'html5') return Boolean(video.mediaUrl);
  if (provider === 'embed') return Boolean(video.embedUrl);
  return false;
};

export function filterVideoLibrary(filters: VideoFilters, source = VIDEO_LIBRARY) {
  const q = filters.query.trim().toLowerCase();
  return source.filter((video) => {
    if (video.reviewStatus !== 'listed') return false;
    if (filters.category && video.category !== filters.category) return false;
    if (filters.subcategory && video.subcategory !== filters.subcategory) return false;
    if (filters.format && video.format !== filters.format) return false;
    if (filters.level && video.level !== filters.level) return false;
    if (filters.intent && !video.intents.includes(filters.intent)) return false;
    if (!q) return true;
    const haystack = [video.title, video.channel, video.summary, video.category, video.subcategory, ...video.tags, ...video.intents].join(' ').toLowerCase();
    return haystack.includes(q);
  });
}

export function pairedLongForm(video: ClinicalVideo, source = VIDEO_LIBRARY) {
  if (!video.pairedLongFormId) return undefined;
  return source.find((candidate) => candidate.id === video.pairedLongFormId && candidate.reviewStatus === 'listed');
}
