/** Links to OPENPediatrics' public learning resources.
 * These are external references, not copies of the underlying media,
 * interactive code or copyrighted course content.
 */
import type { ClinicalVideo } from './types';

export const OPENPEDIATRICS_RESOURCES: ClinicalVideo[] = [
  {
    id: 'openpediatrics-ventilator-simulator',
    title: 'OPENPediatrics — Ventilator Simulator',
    channel: 'OPENPediatrics',
    provider: 'external',
    sourceClass: 'educator',
    sourceUrl: 'https://www.openpediatrics.org/interactive-media/ventilator-simulator',
    sourceLabel: 'Original OPENPediatrics simulator and enrollment',
    format: 'long',
    category: 'devices',
    subcategory: 'ventilators',
    intents: ['learn','manage','troubleshoot','case-review'],
    level: 'advanced',
    tags: ['pediatric mechanical ventilation','interactive simulator','ventilator settings','monitoring','oxygenation','ventilation','case feedback'],
    summary: 'Open the original interactive training experience with ventilator fundamentals, scenario-based decisions, troubleshooting and individualized learning feedback.',
    reviewStatus: 'listed',
    featured: true,
  },
  {
    id: 'openpediatrics-modes-of-mechanical-ventilation',
    title: 'OPENPediatrics — Modes of Mechanical Ventilation',
    channel: 'OPENPediatrics',
    provider: 'external',
    sourceClass: 'educator',
    sourceUrl: 'https://www.openpediatrics.org/critical-care-videos/modes-of-mechanical-ventilation',
    sourceLabel: 'OPENPediatrics original instructional video',
    format: 'long',
    category: 'airway-vent',
    subcategory: 'modes',
    intents: ['learn','manage'],
    level: 'intermediate',
    tags: ['volume control','assist control','SIMV','pressure support','ventilator modes'],
    summary: 'A reference lesson on mechanical ventilation modes, their operating differences, tradeoffs and clinical indications.',
    reviewStatus: 'listed',
  },
  {
    id: 'openpediatrics-general-ventilator-setup',
    title: 'OPENPediatrics — General Ventilator Set-Up',
    channel: 'OPENPediatrics',
    provider: 'external',
    sourceClass: 'educator',
    sourceUrl: 'https://www.openpediatrics.org/critical-care-videos/general-ventilator-set-up',
    sourceLabel: 'OPENPediatrics original instructional video',
    format: 'long',
    category: 'airway-vent',
    subcategory: 'vent-setup',
    intents: ['learn','setup','manage'],
    level: 'foundational',
    tags: ['mechanical ventilation','initial setup','ventilator configuration'],
    summary: 'External clinical teaching reference for familiarizing learners with ventilator setup and initial parameters.',
    reviewStatus: 'listed',
  },
  {
    id: 'openpediatrics-ventilator-waveforms',
    title: 'OPENPediatrics — Ventilator Waveforms',
    channel: 'OPENPediatrics',
    provider: 'external',
    sourceClass: 'educator',
    sourceUrl: 'https://www.openpediatrics.org/critical-care-videos/ventilator-waveforms',
    sourceLabel: 'OPENPediatrics original instructional video',
    format: 'long',
    category: 'airway-vent',
    subcategory: 'waveforms',
    intents: ['learn','manage','troubleshoot'],
    level: 'intermediate',
    tags: ['pressure','flow','volume','ventilator scalars','waveform interpretation'],
    summary: 'External reference for learning to interpret ventilator waveform patterns during patient assessment and troubleshooting.',
    reviewStatus: 'listed',
  },
  {
    id: 'openpediatrics-introduction-to-mechanical-ventilation',
    title: 'OPENPediatrics — Introduction to Mechanical Ventilation',
    channel: 'OPENPediatrics',
    provider: 'external',
    sourceClass: 'educator',
    sourceUrl: 'https://www.openpediatrics.org/critical-care-videos/introduction-to-mechanical-ventilation',
    sourceLabel: 'OPENPediatrics original instructional video',
    format: 'long',
    category: 'airway-vent',
    subcategory: 'vent-setup',
    intents: ['learn'],
    level: 'foundational',
    tags: ['mechanical ventilation','respiratory failure','ventilation basics','critical care'],
    summary: 'Introductory OPENPediatrics lesson for foundational mechanical-ventilation learning.',
    reviewStatus: 'listed',
  },
];
